language: java
sudo: true

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS="-Xmx512m"


#after_success:
#- ./gradlew codeCoverageReport --debug --info --stacktrace

#after_failure:
#- ./gradlew clean check --debug --info --stacktrace

script:
  - ./gradlew build --stacktrace --info --no-daemon

after_success:
- ./gradlew jacocoRootReport coveralls --no-daemon

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    secure: 0Nf9Bk3lFW+35ifBhO25JnX23ZKUC+Eqo6YaRZ+6jQ8aKHHbPsf9DuaWX3+8C7pGzBTK0Ho7dNXVfNz4pYjrvv8b4rukKY6wEFSzMMJrCW0udRfHNEa3jj5VAm/BDXMypbzjkMm9XJ5aAPBUweb+oyHJBCWwNNCyHElQDp2TggE=
