{
 PlotTheme -> {
  {"\"Web\"", "PlotTheme-AnatomyPlot3D-Web.png"}, 
  {"\"Minimal\"", "PlotTheme-AnatomyPlot3D-Minimal.png"}, 
  {"\"Detailed\"", "PlotTheme-AnatomyPlot3D-Detailed.png"}, 
  {"\"Business\"", "PlotTheme-AnatomyPlot3D-Business.png"}, 
  {"\"Marketing\"", "PlotTheme-AnatomyPlot3D-Marketing.png"}, 
  {"\"Scientific\"", "PlotTheme-AnatomyPlot3D-Scientific.png"}, 
  {"\"Monochrome\"", "PlotTheme-AnatomyPlot3D-Monochrome.png"}, 
  {"\"Classic\"", "PlotTheme-AnatomyPlot3D-Classic.png"}, 
  {"\"Default\"", "PlotTheme-AnatomyPlot3D-Default.png"}, 
  {"\"XRay\"", "PlotTheme-AnatomyPlot3D-XRay.png"}, 
  {"\"Transparent\"", "PlotTheme-AnatomyPlot3D-Transparent.png"}, 
  {"\"Vintage\"", "PlotTheme-AnatomyPlot3D-Vintage.png"}, 
  {"\"BoldColor\"", "PlotTheme-AnatomyPlot3D-BoldColor.png"}, 
  {"\"CoolColor\"", "PlotTheme-AnatomyPlot3D-CoolColor.png"}, 
  {"\"DarkColor\"", "PlotTheme-AnatomyPlot3D-DarkColor.png"}, 
  {"\"NeonColor\"", "PlotTheme-AnatomyPlot3D-NeonColor.png"}, 
  {"\"PastelColor\"", "PlotTheme-AnatomyPlot3D-PastelColor.png"}, 
  {"\"RoyalColor\"", "PlotTheme-AnatomyPlot3D-RoyalColor.png"}, 
  {"\"VibrantColor\"", "PlotTheme-AnatomyPlot3D-VibrantColor.png"}, 
  {"\"WarmColor\"", "PlotTheme-AnatomyPlot3D-WarmColor.png"}, 
  {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
  {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
  {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
  {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
  {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
  {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
  {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
  {"\"Icon\"", "PlotTheme-Icon.png"}, 
  {"\"Thumbnail\"", "PlotTheme-Thumbnail.png"}, 
  {"\"Square\"", "PlotTheme-Square.png"}, 
  {"\"Tall\"", "PlotTheme-Tall.png"}, 
  {"\"Wide\"", "PlotTheme-Wide.png"}, 
  {"\"SizeScale\"", "PlotTheme-SizeScale.png"}
  }
}
