{BubbleScale -> {"\"Diameter\""}, BubbleSizes -> 
  {"{0.2, 0.4}", "{0.3, 0.4}", "{0.4, 0.6}", "{0.1, 0.5}"}, 
 ChartElementFunction -> {"\"MarkerBubble3D\"", "\"PolyhedronBubble3D\"", 
   "\"MarkerBubble3D\"", "DataDrilldownBubble", "ChartElementDataFunction[\"M\
arkerBubble3D\",\"Shape\"\[Rule]\"Cylinder\",\"Marker\"\[Rule]\"Cuboid\",\"Ma\
rkerColor\"\[Rule]Yellow]"}, PlotTheme -> 
  {{"\"Web\"", "PlotTheme-BubbleChart3D-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-BubbleChart3D-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-BubbleChart3D-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-BubbleChart3D-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-BubbleChart3D-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-BubbleChart3D-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-BubbleChart3D-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-BubbleChart3D-Classic.png"}, 
   {"\"Default\"", "PlotTheme-BubbleChart3D-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"OpenMarkers\"", "PlotTheme-OpenMarkers.png"}, 
   {"\"OpenMarkersThick\"", "PlotTheme-OpenMarkersThick.png"}, 
   {"\"PlotMarkers\"", "PlotTheme-PlotMarkers.png"}, 
   {"\"ThinLines\"", "PlotTheme-ThinLines.png"}, 
   {"\"MediumLines\"", "PlotTheme-MediumLines.png"}, 
   {"\"ThickLines\"", "PlotTheme-ThickLines.png"}, 
   {"\"BoldScheme\"", "PlotTheme-BoldScheme.png"}, 
   {"\"FadeScheme\"", "PlotTheme-FadeScheme.png"}}}
