{PlotTheme -> {{"\"Web\"", "PlotTheme-MeshRegion-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-MeshRegion-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-MeshRegion-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-MeshRegion-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-MeshRegion-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-MeshRegion-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-MeshRegion-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-MeshRegion-Classic.png"}, 
   {"\"Default\"", "PlotTheme-MeshRegion-Default.png"}, 
   {"\"Points\"", "PlotTheme-MeshRegion-Points.png"}, 
   {"\"Lines\"", "PlotTheme-MeshRegion-Lines.png"}, 
   {"\"Polygons\"", "PlotTheme-MeshRegion-Polygons.png"}, 
   {"\"SampledPoints\"", "PlotTheme-MeshRegion-SampledPoints.png"}, 
   {"\"SphereAndTube\"", "PlotTheme-MeshRegion-SphereAndTube.png"}, 
   {"\"SmoothShading\"", "PlotTheme-MeshRegion-SmoothShading.png"}, 
   {"\"FaceNormals\"", "PlotTheme-MeshRegion-FaceNormals.png"}, 
   {"\"LargeMesh\"", "PlotTheme-MeshRegion-LargeMesh.png"}}}
