{ChartElementFunction -> {"\"BoxWhisker\"", "\"GlassQuantile\"", 
   "\"HistogramDensity\"", "\"Density\"", "\"SmoothDensity\""}, 
 Method -> {"{\"BoxWidth\" -> \"Scaled\"}", "{\"BoxWidth\" -> \"Fixed\"}"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-DistributionChart-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-DistributionChart-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-DistributionChart-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-DistributionChart-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-DistributionChart-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-DistributionChart-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-DistributionChart-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-DistributionChart-Classic.png"}, 
   {"\"Default\"", "PlotTheme-DistributionChart-Default.png"}}}
