{Method -> {"\"Prim\"", "\"Kruskal\"", "\"MinimumCostAborescence\""}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-Graph-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-Graph-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-Graph-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-Graph-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-Graph-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-Graph-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-Graph-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-Graph-Classic.png"}, 
   {"\"Default\"", "PlotTheme-Graph-Default.png"}, 
   {"\"LargeGraph\"", "PlotTheme-Graph-LargeGraph.png"}, 
   {"\"ClassicDiagram\"", "PlotTheme-Graph-ClassicDiagram.png"}}}
