{DataReversed -> {"True", "{False, True}"}, 
 MaxPlotPoints -> {"50", "200", "100", "Infinity"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-MatrixPlot-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-MatrixPlot-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-MatrixPlot-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-MatrixPlot-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-MatrixPlot-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-MatrixPlot-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-MatrixPlot-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-MatrixPlot-Classic.png"}, 
   {"\"Default\"", "PlotTheme-MatrixPlot-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}}}
