{MaxRecursion -> {"20", "50", "100"}, 
 Method -> {"\"GlobalAdaptive\"", "\"LocalAdaptive\"", 
   "\"DoubleExponential\"", "\"Trapezoidal\"", "\"MultiPeriodic\"", 
   "\"MonteCarlo\"", "\"QuasiMonteCarlo\"", "\"AdaptiveMonteCarlo\"", 
   "\"AdaptiveQuasiMonteCarlo\"", "\"DoubleExponentialOscillatory\"", 
   "\"ExtrapolatingOscillatory\"", "\"TrapezoidalRule\"", 
   "\"NewtonCotesRule\"", "\"GaussBerntsenEspelidRule\"", 
   "\"GaussKronrodRule\"", "\"LobattoKronrodRule\"", 
   "\"ClenshawCurtisRule\"", "\"MultipanelRule\"", "\"CartesianRule\"", 
   "\"MultidimensionalRule\"", "\"LevinRule\"", "\"MonteCarloRule\""}, 
 PrecisionGoal -> {"2", "4", "6", "8", "10"}, 
 WorkingPrecision -> {"10", "20", "100"}}
