{AxesEdge -> {"{Automatic,None,Automatic}"}, 
 BoxStyle -> {"GrayLevel[0.6]", "Directive[Opacity[0.6]]", 
   "{Dashing[Medium], Gray}"}, Exclusions -> {"None", "True"}, 
 FaceGridsStyle -> {"GrayLevel[0.4]", "Directive[Gray, Dotted]", "Orange"}, 
 Lighting -> {"\"Neutral\"", "{{\"Ambient\", Lighter[Blue, 2/3]}}", 
   "{{\"Directional\", Yellow, {5,5,5}}}", "{{\"Point\", Green, {0,0,5}}}"}, 
 MaxRecursion -> {"1", "2", "3", "Infinity"}, 
 MeshShading -> {"{{Red, Yellow}, {Pink, Orange}}", 
   "{{Automatic, None}, {None, Automatic}}"}, 
 PlotPoints -> {"10", "25", "{20, 20}", "{40, 15}"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-ParametricPlot3D-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-ParametricPlot3D-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-ParametricPlot3D-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-ParametricPlot3D-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-ParametricPlot3D-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-ParametricPlot3D-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-ParametricPlot3D-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-ParametricPlot3D-Classic.png"}, 
   {"\"Default\"", "PlotTheme-ParametricPlot3D-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"ThinLines\"", "PlotTheme-ThinLines.png"}, 
   {"\"MediumLines\"", "PlotTheme-MediumLines.png"}, 
   {"\"ThickLines\"", "PlotTheme-ThickLines.png"}, 
   {"\"BoldScheme\"", "PlotTheme-BoldScheme.png"}, 
   {"\"DarkMesh\"", "PlotTheme-DarkMesh.png"}, 
   {"\"GrayMesh\"", "PlotTheme-GrayMesh.png"}, 
   {"\"LightMesh\"", "PlotTheme-LightMesh.png"}, 
   {"\"ZMesh\"", "PlotTheme-ZMesh.png"}, {"\"ThickSurface\"", 
    "PlotTheme-Plot3D-ThickSurface.png"}}, TextureCoordinateScaling -> 
  {"False", "True"}}
