{ChartElementFunction -> {"\"Sector\"", "\"PlateauSector\"", 
   "\"GlassSector\""}, PlotTheme -> 
  {{"\"Web\"", "PlotTheme-PieChart-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-PieChart-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-PieChart-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-PieChart-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-PieChart-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-PieChart-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-PieChart-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-PieChart-Classic.png"}, 
   {"\"Default\"", "PlotTheme-PieChart-Default.png"}, 
   {"\"BackgroundColor\"", "PlotTheme-BackgroundColor.png"}, 
   {"\"BoldColor\"", "PlotTheme-BoldColor.png"}, 
   {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"BoldScheme\"", "PlotTheme-BoldScheme.png"}, 
   {"\"FadeScheme\"", "PlotTheme-FadeScheme.png"}}, 
 PolarAxes -> {"False", "True", "{True, False}", "Automatic"}, 
 PolarTicks -> {"{\"Degrees\",Automatic}", "{\"Percent\",Automatic}", 
   "None"}, SectorOrigin -> {"Left", "Right", "Top", "Bottom"}, 
 SectorSpacing -> {"Tiny", "Small", "Medium", "None"}}
