{Method -> {"{\"ReferenceLineMethod\" -> \"Fit\"}", 
   "{\"ReferenceLineMethod\" -> \"Reference\"}"}, PlotMarkers -> {"None"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-QuantilePlot-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-QuantilePlot-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-QuantilePlot-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-QuantilePlot-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-QuantilePlot-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-QuantilePlot-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-QuantilePlot-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-QuantilePlot-Classic.png"}, 
   {"\"Default\"", "PlotTheme-QuantilePlot-Default.png"}}, 
 ReferenceLineStyle -> {"None", "Red"}}
