{DataReversed -> {"True", "False"}, Epilog -> {"{}"}, 
 Frame -> {"False", "True"}, FrameLabel -> {"{j, i}"}, 
 FrameTicks -> {"False", "True"}, ImagePadding -> {"None"}, 
 LightingAngle -> {"180*Degree", "{0, Pi/12}", "None"}, 
 MaxPlotPoints -> {"200", "300", "Infinity", "10", "30"}, 
 MeshStyle -> {"Directive[Red, Dashed]", "Orange"}, 
 Method -> {"\"AspectBasedShading\"", "\"DiffuseReflection\""}, 
 PerformanceGoal -> {"\"Quality\"", "\"Speed\""}, 
 PlotRangePadding -> {"None"}, PlotTheme -> 
  {{"\"Web\"", "PlotTheme-ReliefPlot-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-ReliefPlot-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-ReliefPlot-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-ReliefPlot-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-ReliefPlot-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-ReliefPlot-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-ReliefPlot-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-ReliefPlot-Classic.png"}, 
   {"\"Default\"", "PlotTheme-ReliefPlot-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}}}
