{ChartElementFunction -> {"\"ProfileSector3D\"", "\"CylindricalSector3D\"", 
   "\"TorusSector3D\""}, PlotTheme -> 
  {{"\"Web\"", "PlotTheme-PieChart3D-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-PieChart3D-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-PieChart3D-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-PieChart3D-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-PieChart3D-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-PieChart3D-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-PieChart3D-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-PieChart3D-Classic.png"}, 
   {"\"Default\"", "PlotTheme-PieChart3D-Default.png"}, 
   {"\"BackgroundColor\"", "PlotTheme-BackgroundColor.png"}, 
   {"\"BoldColor\"", "PlotTheme-BoldColor.png"}, 
   {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"BoldScheme\"", "PlotTheme-BoldScheme.png"}, 
   {"\"FadeScheme\"", "PlotTheme-FadeScheme.png"}}}
