{MaxRecursion -> {"0", "2", "5", "10", "Infinity"}, 
 MeshShading -> {"{{Red, Yellow}, {Pink, Orange}}", 
   "{{Automatic, None}, {None, Automatic}}"}, 
 NormalsFunction -> {"None", "Automatic"}, 
 PlotPoints -> {"10", "20", "50", "100"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-ParametricPlot3D-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-ParametricPlot3D-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-ParametricPlot3D-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-ParametricPlot3D-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-ParametricPlot3D-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-ParametricPlot3D-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-ParametricPlot3D-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-ParametricPlot3D-Classic.png"}, 
   {"\"Default\"", "PlotTheme-ParametricPlot3D-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"BoldScheme\"", "PlotTheme-BoldScheme.png"}, 
   {"\"DarkMesh\"", "PlotTheme-DarkMesh.png"}, 
   {"\"GrayMesh\"", "PlotTheme-GrayMesh.png"}, 
   {"\"LightMesh\"", "PlotTheme-LightMesh.png"}, 
   {"\"ZMesh\"", "PlotTheme-ZMesh.png"}, {"\"ThickSurface\"", 
    "PlotTheme-Plot3D-ThickSurface.png"}}, TextureCoordinateFunction -> 
  {"({#1, #2} &)"}}
