{MaxRecursion -> {"10", "20", "30"}, 
 MeshShading -> {"{Red, Yellow, Green, None}", "{Red, None}"}, 
 PlotTheme -> {{"\"Web\"", "PlotTheme-StreamPlot-Web.png"}, 
   {"\"Minimal\"", "PlotTheme-StreamPlot-Minimal.png"}, 
   {"\"Detailed\"", "PlotTheme-StreamPlot-Detailed.png"}, 
   {"\"Business\"", "PlotTheme-StreamPlot-Business.png"}, 
   {"\"Marketing\"", "PlotTheme-StreamPlot-Marketing.png"}, 
   {"\"Scientific\"", "PlotTheme-StreamPlot-Scientific.png"}, 
   {"\"Monochrome\"", "PlotTheme-StreamPlot-Monochrome.png"}, 
   {"\"Classic\"", "PlotTheme-StreamPlot-Classic.png"}, 
   {"\"Default\"", "PlotTheme-StreamPlot-Default.png"}, 
   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, {"\"MinimalAxes\"", 
    "PlotTheme-MinimalAxis.png"}, {"\"Grid\"", "PlotTheme-Grid.png"}, 
   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
   {"\"Frame\"", "PlotTheme-Frame.png"}, {"\"HeightGrid\"", 
    "PlotTheme-SingleAxisGrid.png"}, {"\"FullAxesGrid\"", 
    "PlotTheme-DoubleAxisGrid.png"}, {"\"FrameGrid\"", 
    "PlotTheme-FrameGrid.png"}, {"\"BackgroundColor\"", 
    "PlotTheme-BackgroundColor.png"}, {"\"BoldColor\"", 
    "PlotTheme-BoldColor.png"}, {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
   {"\"Icon\"", "PlotTheme-Icon.png"}, {"\"Thumbnail\"", 
    "PlotTheme-Thumbnail.png"}, {"\"Square\"", "PlotTheme-Square.png"}, 
   {"\"Tall\"", "PlotTheme-Tall.png"}, {"\"Wide\"", "PlotTheme-Wide.png"}, 
   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
   {"\"ThinLines\"", "PlotTheme-ThinLines.png"}, 
   {"\"MediumLines\"", "PlotTheme-MediumLines.png"}, 
   {"\"ThickLines\"", "PlotTheme-ThickLines.png"}}}
