{Language -> {"\"Afrikaans\"", "\"Albanian\"", "\"Azerbaijani\"", "\"Belarusian\"", "\"Bosnian\"", 
 "\"Bulgarian\"", "\"Catalan\"", "\"Cebuano\"", "\"Chinese\"", "\"Croatian\"", 
 "\"Czech\"", "\"Danish\"", "\"Dutch\"", "\"English\"", "\"Esperanto\"", "\"Estonian\"", 
 "\"Finnish\"", "\"French\"", "\"Galician\"", "\"Georgian\"", "\"German\"", "\"Greek\"", 
 "\"Haitian\"", "\"Hungarian\"", "\"Icelandic\"", "\"Indonesian\"", "\"Irish\"", 
 "\"Italian\"", "\"Japanese\"", "\"Kazakh\"", "\"Kirghiz\"", "\"Korean\"", "\"Lao\"", 
 "\"Latin\"", "\"Lithuanian\"", "\"Macedonian\"", "\"Malay\"", "\"Norwegian\"", 
 "\"Polish\"", "\"Portuguese\"", "\"Romanian\"", "\"Russian\"", "\"Serbian\"", 
 "\"Slovak\"", "\"Slovenian\"", "\"Spanish\"", "\"Swahili\"", "\"Swedish\"", 
 "\"Tajik\"", "\"Turkish\"", "\"Ukrainian\"", "\"Uzbek\"", "\"Vietnamese\"", "\"Welsh\""}}
