{
	GaugeFaceStyle -> {"None", "White", "LightBlue", "LightGray", "LightOrange"}, 
	GaugeFrameElementFunction -> {"\"Rectangle\"", "\"GlassRectangle\"", "\"ArrowRectangle\"", 
	   "\"FadingRectangle\"", "\"GradientScaleRectangle\""}, 
	PlotTheme -> {{"\"Web\"", "PlotTheme-VerticalGauge-Web.png"}, 
	   {"\"Minimal\"", "PlotTheme-VerticalGauge-Minimal.png"}, 
	   {"\"Detailed\"", "PlotTheme-VerticalGauge-Detailed.png"}, 
	   {"\"Business\"", "PlotTheme-VerticalGauge-Business.png"}, 
	   {"\"Marketing\"", "PlotTheme-VerticalGauge-Marketing.png"}, 
	   {"\"Scientific\"", "PlotTheme-VerticalGauge-Scientific.png"}, 
	   {"\"Monochrome\"", "PlotTheme-VerticalGauge-Monochrome.png"}, 
	   {"\"Classic\"", "PlotTheme-VerticalGauge-Classic.png"}, 
	   {"\"Default\"", "PlotTheme-VerticalGauge-Default.png"}, 
	   {"\"NoAxes\"", "PlotTheme-NoAxes.png"}, 
	   {"\"MinimalAxes\"", "PlotTheme-MinimalAxis.png"}, 
	   {"\"Grid\"", "PlotTheme-Grid.png"}, 
	   {"\"SingleAxis\"", "PlotTheme-SingleAxis.png"}, 
	   {"\"FullAxes\"", "PlotTheme-DoubleAxis.png"}, 
	   {"\"Frame\"", "PlotTheme-Frame.png"}, 
	   {"\"HeightGrid\"", "PlotTheme-SingleAxisGrid.png"}, 
	   {"\"FullAxesGrid\"", "PlotTheme-DoubleAxisGrid.png"}, 
	   {"\"FrameGrid\"", "PlotTheme-FrameGrid.png"}, 
	   {"\"BackgroundColor\"", "PlotTheme-BackgroundColor.png"}, 
	   {"\"BoldColor\"", "PlotTheme-BoldColor.png"}, 
	   {"\"CoolColor\"", "PlotTheme-CoolColor.png"}, 
	   {"\"DarkColor\"", "PlotTheme-DarkColor.png"}, 
	   {"\"GrayColor\"", "PlotTheme-GrayColor.png"}, 
	   {"\"NeonColor\"", "PlotTheme-NeonColor.png"}, 
	   {"\"PastelColor\"", "PlotTheme-PastelColor.png"}, 
	   {"\"RoyalColor\"", "PlotTheme-RoyalColor.png"}, 
	   {"\"VibrantColor\"", "PlotTheme-VibrantColor.png"}, 
	   {"\"WarmColor\"", "PlotTheme-WarmColor.png"}, 
	   {"\"BoldLabels\"", "PlotTheme-BoldLabels.png"}, 
	   {"\"ItalicLabels\"", "PlotTheme-ItalicLabels.png"}, 
	   {"\"LargeLabels\"", "PlotTheme-LargeLabels.png"}, 
	   {"\"SmallLabels\"", "PlotTheme-SmallLabels.png"}, 
	   {"\"SansLabels\"", "PlotTheme-SansLabels.png"}, 
	   {"\"SerifLabels\"", "PlotTheme-SerifLabels.png"}, 
	   {"\"Sparkline\"", "PlotTheme-Sparkline.png"}, 
	   {"\"Icon\"", "PlotTheme-Icon.png"}, 
	   {"\"Thumbnail\"", "PlotTheme-Thumbnail.png"}, 
	   {"\"Square\"", "PlotTheme-Square.png"}, 
	   {"\"Tall\"", "PlotTheme-Tall.png"}, 
	   {"\"Wide\"", "PlotTheme-Wide.png"}, 
	   {"\"SizeScale\"", "PlotTheme-SizeScale.png"}, 
	   {"\"ThinLines\"", "PlotTheme-ThinLines.png"}, 
	   {"\"MediumLines\"", "PlotTheme-MediumLines.png"}, 
	   {"\"ThickLines\"", "PlotTheme-ThickLines.png"}},
 	ScalePadding -> {"None", "Scaled[0.2]", "0.2"}
 }
