(* Created with the Wolfram Language : www.wolfram.com *)
<|"3DS" -> "3DS", "ACO" -> "ACO", "AIFF" -> "AIFF", "AU" -> "AU", 
 "AVI" -> "AVI", "Base64" -> "Base64", "Binary" -> "Binary", "Bit" -> "Bit", 
 "BMP" -> "BMP", "Byte" -> "Byte", "BYU" -> "BYU", "BZIP2" -> "BZIP2", 
 "C" -> "C", "CDF" -> "CDF", "Character16" -> "Character16", 
 "Character8" -> "Character8", "Complex128" -> "Complex128", 
 "Complex256" -> "Complex256", "Complex64" -> "Complex64", "CSV" -> "CSV", 
 "CUR" -> "CUR", "DICOM" -> "DICOM", "DIF" -> "DIF", "DIMACS" -> "DIMACS", 
 "DOT" -> "DOT", "DXF" -> "DXF", "EMF" -> "EMF", "EPS" -> "EPS", 
 "ExpressionML" -> "Expression\nML", "FASTA" -> "FASTA", "FASTQ" -> "FASTQ", 
 "FCS" -> "FCS", "FITS" -> "FITS", "FLAC" -> "FLAC", "FLV" -> "FLV", 
 "GIF" -> "GIF", "Graph6" -> "Graph6", "Graphlet" -> "Graphlet", 
 "GraphML" -> "GraphML", "GXL" -> "GXL", "GZIP" -> "GZIP", 
 "HarwellBoeing" -> "Harwell\nBoeing", "HDF" -> "HDF", "HDF5" -> "HDF5", 
 "HTML" -> "HTML", "HTMLFragment" -> "HTML\nFragment", "ICNS" -> "ICNS", 
 "ICO" -> "ICO", "Integer128" -> "Integer128", "Integer16" -> "Integer16", 
 "Integer24" -> "Integer24", "Integer32" -> "Integer32", 
 "Integer64" -> "Integer64", "Integer8" -> "Integer8", "JPEG" -> "JPEG", 
 "JPEG2000" -> "JPEG2000", "JSON" -> "JSON", "JVX" -> "JVX", "KML" -> "KML", 
 "LEDA" -> "LEDA", "List" -> "List", "LWO" -> "LWO", "MAT" -> "MAT", 
 "MathML" -> "MathML", "Maya" -> "Maya", "MGF" -> "MGF", "MIDI" -> "MIDI", 
 "MOL" -> "MOL", "MOL2" -> "MOL2", "MP3" -> "MP3", "MTX" -> "MTX", 
 "MX" -> "MX", "NASACDF" -> "NASACDF", "NB" -> "NB", "NetCDF" -> "NetCDF", 
 "NEXUS" -> "NEXUS", "NOFF" -> "NOFF", "OBJ" -> "OBJ", "OFF" -> "OFF", 
 "OGG" -> "OGG", "Package" -> "Package", "Pajek" -> "Pajek", "PBM" -> "PBM", 
 "PCX" -> "PCX", "PDB" -> "PDB", "PDF" -> "PDF", "PGM" -> "PGM", 
 "PICT" -> "PICT", "PLY" -> "PLY", "PNG" -> "PNG", "PNM" -> "PNM", 
 "POV" -> "POV", "PPM" -> "PPM", "PXR" -> "PXR", "QuickTime" -> "QuickTime", 
 "RawBitmap" -> "RawBitmap", "Real128" -> "Real128", "Real32" -> "Real32", 
 "Real64" -> "Real64", "RIB" -> "RIB", "RTF" -> "RTF", "SCT" -> "SCT", 
 "SDF" -> "SDF", "SND" -> "SND", "Sparse6" -> "Sparse6", "STL" -> "STL", 
 "String" -> "String", "SurferGrid" -> "SurferGrid", "SVG" -> "SVG", 
 "SWF" -> "SWF", "Table" -> "Table", "TAR" -> "TAR", 
 "TerminatedString" -> "Terminated\nString", "TeX" -> "TeX", 
 "TeXFragment" -> "TeX\nFragment", "Text" -> "Text", "TGA" -> "TGA", 
 "TGF" -> "TGF", "TIFF" -> "TIFF", "TSV" -> "TSV", 
 "UnsignedInteger128" -> "Unsigned\nInteger128", 
 "UnsignedInteger16" -> "Unsigned\nInteger16", 
 "UnsignedInteger24" -> "Unsigned\nInteger24", 
 "UnsignedInteger32" -> "Unsigned\nInteger32", 
 "UnsignedInteger64" -> "Unsigned\nInteger64", 
 "UnsignedInteger8" -> "Unsigned\nInteger8", "UUE" -> "UUE", 
 "VideoFrames" -> "Video\nFrames", "VRML" -> "VRML", "VTK" -> "VTK", 
 "WAV" -> "WAV", "Wave64" -> "Wave64", "WDX" -> "WDX", "WebP" -> "WebP", 
 "X3D" -> "X3D", "XBM" -> "XBM", "XHTML" -> "XHTML", 
 "XHTMLMathML" -> "XHTML\nMathML", "XLS" -> "XLS", "XLSX" -> "XLSX", 
 "XML" -> "XML", "XYZ" -> "XYZ", "ZIP" -> "ZIP", "ZPR" -> "ZPR"|>
