
{
"X" -> "X Axis",
"Y" -> (-"Y Axis"),
"Z" -> "Z Axis",
"X1" -> "X Axis",
"Y1" -> (-"Y Axis"),
"Z1" -> "Z Axis",
"X2" -> "Z Rotation",
"Y2" -> (-"Slider"),
"Z2" -> None,
"X3" -> "Hatswitch X Axis",
"Y3" -> (-"Hatswitch Y Axis"),
"Z3" -> None,
"X4" -> Switch[{"Button 1", "Button 3"}, {False, False}, 0, {True, False}, -1, {False, True}, 1, {True, True}, 0.00001],
"Y4" -> Switch[{"Button 2", "Button 4"}, {False, False}, 0, {True, False}, -1, {False, True}, 1, {True, True}, 0.00001],
"X5" -> Switch[{"Button 7", "Button 5"}, {False, False}, 0, {True, False}, -1, {False, True}, 1, {True, True}, 0.00001],
"Y5" -> Switch[{"Button 8", "Button 6"}, {False, False}, 0, {True, False}, -1, {False, True}, 1, {True, True}, 0.00001],
"X6" -> Switch[{"Button 9", "Button 10"}, {False, False}, 0, {True, False}, -1, {False, True}, 1, {True, True}, 0.00001],
"B1" -> "Button 1",
"B2" -> "Button 2",
"B3" -> "Button 3",
"B4" -> "Button 4",
"B5" -> "Button 5",
"B6" -> "Button 6",
"B7" -> "Button 7",
"B8" -> "Button 8",
"B9" -> "Button 9",
"B10" -> "Button 10",
"B11" -> "Button 11",
"B12" -> "Button 12",
"DefaultAbsolute" -> False
}

