(* Paclet Info File *)

(* created 2008/02/13*)

Paclet[
	Name -> "RobotTools",
	Version -> "2.2.0",
	MathematicaVersion -> "11+",
	Creator ->"Ian Johnson <ijohnson@wolfram.com>",
	Loading->Automatic,
	Extensions ->
	{
		{"Kernel",
			Context -> {"RobotToolsLoader`","RobotTools`"},
			"Root" -> "Kernel",
			Symbols -> {
				"System`CurrentScreenImage",
				"System`CurrentNotebookImage"
(*				"AllCells",
				"AppleScriptExecute",
				"BasicBox",
				"BottomLeft",
				"BottomRight", 
				"BoxInformation",
				"Clicks",
				"Delay",
				"DialogAction",
				"DummyPrimitiveBox", 
				"FocusedNotebook",
				"GetAutoDelay",
				"GetBoxRectangles",
				"GetPixelColor",
				"GetSelectionBoundingBoxes",
				"GetWindowRectangle",
				"InlineGraphicBox",
				"InstallAppleScript",
				"InstallExternalPackages",
				"InstallRobotTools",
				"IsAutoWaitForIdle",
				"ItemActivate",
				"ItemKeys",
				"KeyboardForm",
				"KeyPress",
				"KeyRelease",
				"KeyType",
				"LineWrapBox",
				"Modifiers",
				"MouseButton",
				"MouseClick", 
				"MouseClicks",
				"MouseDoubleClick",
				"MouseDrag",
				"MouseMove",
				"MousePress", 
				"MouseRelease",
				"MouseSingleClick",
				"MouseSteps",
				"MouseTripleClick",
				"MouseWheel", 
				"NotebookImage",
				"NumberBox",
				"PrunedBoxes",
				"RasterizeNotebook", 
				"RasterizeScreenShot",
				"RasterizeSelection",
				"RescaleRectangle",
				"Scaling", 
				"ScreenShot",
				"SetAutoDelay",
				"SetAutoWaitForIdle",
				"SetFocusedNotebook",
				"Steps", 
				"ToKeys",
				"TopLeft",
				"TopRight",
				"UninstallRobotTools",
				"UseRobotFacadeClass", 
				"VerticalSpanBox",
				"WaitForIdle",
				"$AutoDelay",
				"$AutoWaitForIdle", 
				"$InitialKeyTypeDelay",
				"$InterfaceLanguage",
				"$KeyPressDelay",
				"$KeyReleaseDelay", 
				"$KeyTypeDelay",
				"$MenuLanguage",
				"$MouseClickDelay",
				"$MouseMoveDelay", 
				"$MousePressDelay",
				"$MouseReleaseDelay",
				"$MouseWheelDelay",
				"$PanModifiers", 
				"$RotateModifiers",
				"$ZoomModifiers"*)
			}
		}(*,
		{"Documentation",
			MainPage -> "Guides/RobotTools",
			Language -> "English"
		},
	    {"FrontEnd"}*)
    }
]
