Paclet[Name -> "ChannelFramework", Description -> "The Channel Framework", 
 Creator -> "Igor Bakshee <bakshee@wolfram.com>", 
 MathematicaVersion -> "10+", Version -> "0.6.1807031425", 
 Loading -> Automatic, Extensions -> 
  {{"Kernel", Root -> "Kernel", Context -> {"ChannelFrameworkLoader`", 
      "ChannelFramework`"}, Symbols -> {"System`ChannelListen", 
      "System`ChannelListener", "System`ChannelListenerWait", 
      "System`ChannelListeners", "System`RemoveChannelListener", 
      "System`ChannelSend", "System`$ChannelBase", "System`CreateChannel", 
      "System`DeleteChannel", "System`ChannelBase", 
      "System`ChannelPreSendFunction", "System`ChannelHistoryLength", 
      "System`ChannelDatabin", "System`ChannelObject", "System`FindChannels", 
      "System`ChannelBrokerAction", "System`ChannelReceiverFunction", 
      "System`ChannelSubscribers", "System`RemoveChannelSubscribers"}}, 
   {"ChannelFramework"}}]
