
Get["DataResource`Dependencies`"]
Get["DataResource`CommonTools`"]
Get["DataResource`Utilities`"]
Get["DataResource`Copy`"]
Get["DataResource`CreateResources`"]
Get["DataResource`Deploy`"]
Get["DataResource`Examples`"]
Get["DataResource`Metadata`"]
Get["DataResource`Objects`"]
Get["DataResource`ReadData`"]
Get["DataResource`ResourceData`"]
Get["DataResource`Submit`"]
Get["DataResource`UpValues`"]
Get["DataResource`Messages`"]
Get["DataResource`Notebooks`"]
Get["DataResource`ElementData`"]
Get["DataResource`Register`"]

