Paclet[
	Name->"NETLink",
	Version->"1.7.0",
	Extensions->{
	    {"Kernel", Root -> ".", Context -> "NETLink`"},
		{"Documentation", Language->All, Resources->{"Guides/DotNETInterface"}},
		{"Documentation", Language->All},
		{"Documentation", Language->All, Resources->
			{{"ReferencePages/NET/NETLink", "apidocs/index.html"},
			 {"ReferencePages/NET/IMathLink", "apidocs/Wolfram.NETLink.IMathLink.html"},
			 {"ReferencePages/NET/IKernelLink", "apidocs/Wolfram.NETLink.IKernelLink.html"},
			 {"ReferencePages/NET/ILoopbackLink", "apidocs/Wolfram.NETLink.ILoopbackLink.html"},
			 {"ReferencePages/NET/ILinkMark", "apidocs/Wolfram.NETLink.ILinkMark.html"},
			 {"ReferencePages/NET/Expr", "apidocs/Wolfram.NETLink.Expr.html"},
			 {"ReferencePages/NET/ExpressionType", "apidocs/Wolfram.NETLink.ExpressionType.html"},
			 {"ReferencePages/NET/ExprFormatException", "apidocs/Wolfram.NETLink.ExpressionFormatException.html"},
			 {"ReferencePages/NET/MathDelegate", "apidocs/Wolfram.NETLink.MathDelegate.html"},
			 {"ReferencePages/NET/MathematicaNotReadyException", "apidocs/Wolfram.NETLink.MathematicaNotReadyException.html"},
			 {"ReferencePages/NET/MathKernel", "apidocs/Wolfram.NETLink.MathKernel.html"},
			 {"ReferencePages/NET/MathLinkException", "apidocs/Wolfram.NETLink.MathLinkException.html"},
			 {"ReferencePages/NET/MathLinkFactory", "apidocs/Wolfram.NETLink.MathLinkFactory.html"},
			 {"ReferencePages/NET/MessageHandler", "apidocs/Wolfram.NETLink.MessageHandler.html"},
			 {"ReferencePages/NET/NETLinkConstants", "apidocs/Wolfram.NETLink.NETLinkConstants.html"},
			 {"ReferencePages/NET/PacketHandler", "apidocs/Wolfram.NETLink.PacketHandler.html"},
			 {"ReferencePages/NET/PacketType", "apidocs/Wolfram.NETLink.PacketType.html"},
			 {"ReferencePages/NET/StdLink", "apidocs/Wolfram.NETLink.StdLink.html"},
			 {"ReferencePages/NET/TypeLoader", "apidocs/Wolfram.NETLink.TypeLoader.html"},
			 {"ReferencePages/NET/YieldFunction", "apidocs/Wolfram.NETLink.YieldFunction.html"},
			 {"ReferencePages/NET/ConsoleWindow", "apidocs/Wolfram.NETLink.UI.ConsoleWindow.html"},
			 {"ReferencePages/NET/DoubleBufferedPanel", "apidocs/Wolfram.NETLink.UI.DoubleBufferedPanel.html"},
			 {"ReferencePages/NET/MathPictureBox", "apidocs/Wolfram.NETLink.UI.MathPictureBox.html"},
			 {"ReferencePages/NET/IKernelLink/Evaluate", "apidocs/Wolfram.NETLink.IKernelLink.Evaluate_overloads.html"},
			 {"ReferencePages/NET/IKernelLink/EvaluateToOutputForm", "apidocs/Wolfram.NETLink.IKernelLink.EvaluateToOutputForm_overloads.html"},
			 {"ReferencePages/NET/IKernelLink/EvaluateToImage", "apidocs/Wolfram.NETLink.IKernelLink.EvaluateToImage_overloads.html"},
			 {"ReferencePages/NET/IKernelLink/Put", "apidocs/Wolfram.NETLink.IKernelLink.Put.html"},
			 {"ReferencePages/NET/IKernelLink/GetInteger", "apidocs/Wolfram.NETLink.IMathLink.GetInteger.html"},
			 {"ReferencePages/NET/IKernelLink/GetObject", "apidocs/Wolfram.NETLink.IKernelLink.GetObject.html"},
			 {"ReferencePages/NET/IKernelLink/WaitForAnswer", "apidocs/Wolfram.NETLink.IKernelLink.WaitForAnswer.html"},
			 {"ReferencePages/NET/MathLinkFactory/CreateKernelLink", "apidocs/Wolfram.NETLink.MathLinkFactory.CreateKernelLink_overloads.html"},
			 {"ExamplePages/Part1/ProcessPriority", "../Examples/Part1/ProcessPriority.nb"},
			 {"ExamplePages/Part1/WindowsAndDialogs/Circumcircle", "../Examples/Part1/Windows and Dialogs/Circumcircle.nb"},
			 {"ExamplePages/Part1/WindowsAndDialogs/PackageHelper", "../Examples/Part1/Windows and Dialogs/PackageHelper.nb"},
			 {"ExamplePages/Part1/WindowsAndDialogs/RealTimeAlgebra", "../Examples/Part1/Windows and Dialogs/RealTimeAlgebra.nb"},
			 {"ExamplePages/Part1/WindowsAndDialogs/SimpleAnimationWindow", "../Examples/Part1/Windows and Dialogs/SimpleAnimationWindow.nb"},
			 {"ExamplePages/Part1/WindowsAndDialogs/AsteroidsGame", "../Examples/Part1/Windows and Dialogs/AsteroidsGame/AsteroidsGame.nb"},
			 {"ExamplePages/Part1/CallingDLLs/EnumWindows", "../Examples/Part1/Calling DLLs/EnumWindows.nb"},
			 {"ExamplePages/Part1/CallingDLLs/WindowsAPI", "../Examples/Part1/Calling DLLs/WindowsAPI.nb"},
			 {"ExamplePages/Part1/CallingDLLs/BZip2Compression", "../Examples/Part1/Calling DLLs/BZip2Compression.nb"},
			 {"ExamplePages/Part1/CallingCOM/ExcelPieChart", "../Examples/Part1/Calling COM/ExcelPieChart.nb"}
			}
		}
	}
]