(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



{
"TITLE"->"ActionApp",
"ACTIONS-NAME"->"Actions",
"STOP-NAME"->"Stop",
"STOP-TOOLTIP"->"Switch to stopped state",
"STOP-MESSAGE"->"Stop called...\n",
"START-NAME"->"Start",
"START-TOOLTIP"->"Switch to running state",
"START-MESSAGE"->"Start called...\n",
"FORWARD-NAME"->"Forward",
"FORWARD-TOOLTIP"->"Move forward one step",
"FORWARD-MESSAGE"->"Forward called...\n",
"BACK-NAME"->"Back",
"BACK-TOOLTIP"->"Move back one step",
"BACK-MESSAGE"->"Back called...\n",
"CLEAR-NAME"->"Clear",
"CLEAR-TOOLTIP"->"Clear message area"
}
