(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



{
"TITLE"->"ActionApp",
"ACTIONS-NAME"->"Actions",
"STOP-NAME"->"Arr\[EHat]t","STOP-TOOLTIP"->"Commutez \[AGrave] l'\[EAcute]tat arr\[EHat]t\[EAcute]",
"STOP-MESSAGE"->"Arr\[EHat]t appel\[EAcute]...\n",
"START-NAME"->"D\[EAcute]but",
"START-TOOLTIP"->"Commutez \[AGrave] l'\[EAcute]tat courant",
"START-MESSAGE"->"D\[EAcute]but appel\[EAcute]...\n",
"FORWARD-NAME"->"Vers l'avant",
"FORWARD-TOOLTIP"->"Faites avancer une \[EAcute]tape",
"FORWARD-MESSAGE"->"Exp\[EAcute]diez appel\[EAcute]...\n",
"BACK-NAME"->"Dos",
"BACK-TOOLTIP"->"\[CapitalEAcute]cartez une \[EAcute]tape",
"BACK-MESSAGE"->"Dos appel\[EAcute]...\n",
"CLEAR-NAME"->"Espace libre",
"CLEAR-TOOLTIP"->"Zone message claire"
}
