(* Created with the Wolfram Language : www.wolfram.com *)
{Entity["Concept", "Person::93r37"], Entity["Concept", "Bicycle::26wj9"], 
 Entity["Concept", "Auto::p735c"], Entity["Concept", "Motorcycle::4gd85"], 
 Entity["Concept", "Aeroplane::239dv"], Entity["Concept", "Autobus::v5t2j"], 
 Entity["Concept", "RailroadTrain::y7363"], 
 Entity["Concept", "Motortruck::9c7br"], Entity["Concept", "Boat::fx4n4"], 
 Entity["Concept", "TrafficLight::b4966"], 
 Entity["Concept", "FireHydrant::x7gzw"], Entity["Concept", "Stop::33h2c"], 
 Entity["Concept", "ParkingMeter::h445p"], Entity["Concept", "Bench::995ph"], 
 Entity["Concept", "Bird::56ny3"], Entity["Concept", "DomesticCat::jpx55"], 
 Entity["Concept", "CanisFamiliaris::597qc"], 
 Entity["Concept", "EquusCaballus::x93n2"], 
 Entity["Concept", "Sheep::9t384"], Entity["Concept", "Cow::3cf9b"], 
 Entity["Concept", "Elephant::72b52"], Entity["Concept", "Bear::s7w85"], 
 Entity["Concept", "Zebra::nx5qr"], Entity["Concept", "Camelopard::6b787"], 
 Entity["Concept", "BackPack::2cjsp"], Entity["Concept", "Umbrella::3mntq"], 
 Entity["Concept", "Handbag::76k33"], Entity["Concept", "Necktie::67p5x"], 
 Entity["Concept", "Suitcase::vzm4n"], Entity["Concept", "Frisbee::9h9t9"], 
 Entity["Concept", "Ski::5nbj2"], Entity["Concept", "Snowboard::25v3y"], 
 Entity["Concept", "Ball::279y7"], Entity["Concept", "Kite::789p6"], 
 Entity["Concept", "BaseballBat::2n8qr"], 
 Entity["Concept", "BaseballGlove::6c78v"], 
 Entity["Concept", "Skateboard::wvjx6"], Entity["Concept", 
  "Surfboard::367w8"], Entity["Concept", "TennisRacket::zbf7z"], 
 Entity["Concept", "Bottle::998tj"], Entity["Concept", 
  "DrinkingGlass::339c3"], Entity["Concept", "Cup::w4d7b"], 
 Entity["Concept", "Fork::9hxp6"], Entity["Concept", "Knife::9529v"], 
 Entity["Concept", "Spoon::4v83p"], Entity["Concept", "Bowl::8mv4z"], 
 Entity["Concept", "Banana::f6z73"], Entity["Concept", "Apple::857h7"], 
 Entity["Concept", "Sandwich::q3j9z"], Entity["Concept", "Orange::w579d"], 
 Entity["Concept", "BrassicaOleraceaItalica::56n93"], 
 Entity["Concept", "Carrot::7s555"], Entity["Concept", "RedHot::3j848"], 
 Entity["Concept", "Pizza::56w88"], Entity["Concept", "Donut::332td"], 
 Entity["Concept", "Cake::pq6mk"], Entity["Concept", "Chair::ptj48"], 
 Entity["Concept", "Sofa::kfh45"], Entity["Concept", "PotPlant::f84td"], 
 Entity["Concept", "Bed::3924t"], Entity["Concept", "DiningTable::6ypqf"], 
 Entity["Concept", "FlushToilet::c8456"], 
 Entity["Concept", "BoobTube::b9272"], Entity["Concept", "Laptop::zdd33"], 
 Entity["Concept", "Mouse::5wd97"], Entity["Concept", "Remote::h4drx"], 
 Entity["Concept", "Keyboard::yzdk7"], Entity["Concept", "Cellphone::5k4s4"], 
 Entity["Concept", "MicrowaveOven::fs7tb"], Entity["Concept", "Oven::8t665"], 
 Entity["Concept", "Toaster::rp6v2"], Entity["Concept", "Sink::4xnh2"], 
 Entity["Concept", "ElectricRefrigerator::t4bt7"], 
 Entity["Concept", "Book::t8bc6"], Entity["Concept", "Clock::jq868"], 
 Entity["Concept", "Vase::4x594"], Entity["Concept", 
  "PairOfScissors::3gyct"], Entity["Concept", "TeddyBear::f56q9"], 
 Entity["Concept", "BlowDrier::t4dpz"], Entity["Concept", 
  "Toothbrush::7p83q"]}
