{
"ActionMenu_Appearance_Palette" -> "paleta", 
"ActionMenu_Appearance_PopupMenu" -> "men\[UAcute] emergente", 
"ActionMenu_Method_Queued" -> "en cola", 
"AirPressureData_UnitSystem_Imperial" -> "imperial", 
"AirPressureData_UnitSystem_Metric" -> "m\[EAcute]trico", 
"AirTemperatureData_UnitSystem_Imperial" -> "imperial", 
"AirTemperatureData_UnitSystem_Metric" -> "m\[EAcute]trico", 
"AndersonDarlingTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"AngularGauge_GaugeFaceElementFunction_GlassSector" -> "sector de vidrio", 
"AngularGauge_GaugeFaceElementFunction_PlateauSector" -> "sector de meseta", 
"AngularGauge_GaugeFrameElementFunction_BezelSector" -> "sector de bisel", 
"AngularGauge_GaugeFrameElementFunction_GlassSector" -> "sector de vidrio", 
"AngularGauge_GaugeFrameElementFunction_GradientSector" -> "sector de gradiente", 
"AngularGauge_GaugeFrameElementFunction_NoiseSector" -> "sector de ruido", 
"AngularGauge_GaugeFrameElementFunction_Sector" -> "sector", 
"Animator_Appearance_Labeled" -> "etiquetado", 
"Animator_Appearance_PlayPauseButton" -> "bot\[OAcute]n de ejecutar y pausar", 
"Animator_Appearance_ProgressSlider" -> "control deslizante de progreso", 
"Animator_Appearance_StepLeftButton" -> "bot\[OAcute]n hacia la izquierda", 
"Animator_Appearance_StepRightButton" -> "bot\[OAcute]n hacia la derecha", 
"ArcLength_Method_Integrate" -> "integrar", 
"ArcLength_Method_NIntegrate" -> "integrar num\[EAcute]ricamente", 
"ArrayPad_Padding_Extrapolated" -> "extrapolado", 
"ArrayPad_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ArrayPad_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"ArrayPad_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"ArrayPad_Padding_Reversed" -> "reversiones de todo el arreglo",
"Arrowheads_Appearance_Flat" -> "plano", 
"Arrowheads_Appearance_Projected" -> "proyectado", 
"BandpassFilter_Padding_Periodic" -> "peri\[OAcute]dico", 
"BandstopFilter_Padding_Periodic" -> "peri\[OAcute]dico", 
"BarChart3D_ChartElementFunction_Cone" -> "cono", 
"BarChart3D_ChartElementFunction_Cube" -> "cubo", 
"BarChart3D_ChartElementFunction_Cylinder" -> "cilindro", 
"BarChart3D_ChartElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"BarChart3D_ChartElementFunction_ProfileCube" -> "perfil de cubo", 
"BarChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"BarChart_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"BarChart_ChartElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"BarChart_LegendAppearance_Column" -> "columna", 
"BarChart_LegendAppearance_Row" -> "fila", 
"BarLegend_LegendFunction_Frame" -> "marco", 
"BarLegend_LegendFunction_Panel" -> "panel", 
"BarLegend_LegendLayout_Column" -> "columna", 
"BarLegend_LegendLayout_ReversedColumn" -> "columna revertida", 
"BarLegend_LegendLayout_ReversedRow" -> "fila revertida", 
"BarLegend_LegendLayout_Row" -> "fila", 
"Binarize_Method_Cluster" -> "agrupaci\[OAcute]n", 
"Binarize_Method_Entropy" -> "histograma de minimizaci\[OAcute]n de entrop\[IAcute]a", 
"Binarize_Method_Mean" -> "use la media como umbral", 
"Binarize_Method_Median" -> "use la mediana como umbral", 
"Binarize_Method_MinimumError" -> "error m\[IAcute]nimo", 
"BlomqvistBetaTest_AlternativeHypothesis_Greater" -> "mayor", 
"BlomqvistBetaTest_AlternativeHypothesis_Less" -> "menor", 
"BlomqvistBetaTest_AlternativeHypothesis_Unequal" -> "desigual",
"BlomqvistBetaTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"BlomqvistBetaTest_Method_Permutation" -> "permutaci\[OAcute]n",
"BodePlot_PlotLayout_HorizontalGrid" -> "parilla horizontal", 
"BodePlot_PlotLayout_List" -> "lista", 
"BodePlot_PlotLayout_VerticalGrid" -> "parrilla vertical", 
"BoxWhiskerChart_ChartElementFunction_BoxWhisker" -> "diagrama de caja y bigotes", 
"BoxWhiskerChart_ChartElementFunction_FadingBoxWhisker" -> "diagrama de caja y bigotes que desvanece", 
"BoxWhiskerChart_ChartElementFunction_GlassBoxWhisker" -> "diagrama de caja y bigotes de vidrio", 
"BoxWhiskerChart_ChartElementFunction_GradientScaleBoxWhisker" -> "diagrama de caja y bigotes de escala gradiente", 
"BoxWhiskerChart_ChartElementFunction_PlateauBoxWhisker" -> "diagrama de caja y bigotes de meseta", 
"BrownForsytheTest_AlternativeHypothesis_Greater" -> "mayor", 
"BrownForsytheTest_AlternativeHypothesis_Less" -> "menor", 
"BrownForsytheTest_AlternativeHypothesis_Unequal" -> "desigual",
"BrownForsytheTest_VerifyTestAssumptions_" -> "verifica que todos los datos se distribuyen normalmente", 
"BrownForsytheTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"BubbleChart3D_BubbleScale_Diameter" -> "di\[AAcute]metro", 
"BubbleChart3D_ChartElementFunction_MarkerBubble3D" -> "burbuja de marcador en 3D", 
"BubbleChart3D_ChartElementFunction_MarkerBubble3D" -> "burbuja de marcador en 3D", 
"BubbleChart3D_ChartElementFunction_PolyhedronBubble3D" -> "burbuja de poliedro en 3D", 
"BubbleChart_BubbleScale_Area" -> "\[AAcute]rea", 
"BubbleChart_BubbleScale_Diameter" -> "di\[AAcute]metro", 
"BubbleChart_ChartElementFunction_Bubble" -> "burbuja", 
"BubbleChart_ChartElementFunction_FadingBubble" -> "burbuja que desvanece", 
"BubbleChart_ChartElementFunction_MarkerBubble" -> "burbuja de marcador", 
"BubbleChart_ChartElementFunction_NoiseBubble" -> "burbuja de ruido", 
"BubbleChart_ChartElementFunction_SphereBubble" -> "burbuja de esfera", 
"BusinessDayQ_CalendarType_Gregorian" -> "calendario solar gregoriano", 
"BusinessDayQ_CalendarType_Islamic" -> "isl\[AAcute]mico", 
"BusinessDayQ_CalendarType_Jewish" -> "jud\[IAcute]o", 
"BusinessDayQ_HolidayCalendar_Brazil" -> "Brasil", 
"BusinessDayQ_HolidayCalendar_HongKong" -> "Hong Kong", 
"BusinessDayQ_HolidayCalendar_Israel" -> "Israel", 
"BusinessDayQ_HolidayCalendar_UnitedStates" -> "Estados Unidos",
"Button_Appearance_DialogBox" -> "caja de di\[AAcute]logo", 
"Button_Appearance_FramedPalette" -> "paleta enmarcada", 
"Button_Appearance_Frameless" -> "sin marco", 
"Button_Appearance_Palette" -> "paleta", 
"ButtonBar_Appearance_Horizontal" -> "horizontal", 
"ButtonBar_Appearance_Row" -> "fila", 
"ButtonBar_Appearance_Vertical" -> "vertical", 
"ButtonBar_Method_Queued" -> "en cola", 
"ButtonBox_Appearance_DialogBox" -> "caja de di\[AAcute]logo", 
"ButtonBox_Evaluator_Local" -> "local", 
"ButtonBox_Method_Preemptive" -> "preventido", 
"Button_Evaluator_Local" -> "local", 
"Button_Method_Preemptive" -> "preventivo", 
"Button_Method_Queued" -> "en cola", 
"CandlestickChart_ChartElementFunction_ArrowCandlestick" -> "flecha tipo candelero", 
"CandlestickChart_ChartElementFunction_Candlestick" -> "candelero", 
"CandlestickChart_ChartElementFunction_FadingOHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado que desvanece", 
"CandlestickChart_ChartElementFunction_HLC" -> "gr\[AAcute]fico alto-bajo-cerrado", 
"CandlestickChart_ChartElementFunction_OHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado", 
"CandlestickChart_ScalingFunctions_Log" -> "log", 
"CandlestickChart_TrendStyle_BlackWhite" -> "blanco y negro", 
"CandlestickChart_TrendStyle_RedGreen" -> "verde y rojo", 
"CDFDeploy_Method_Standalone" -> "aut\[OAcute]nomo", 
"Cell_CellDingbat_\[FilledCircle]" -> "\[FilledCircle]", 
"Cell_CellDingbat_\[FilledCircle]" -> "\[FilledCircle]", 
"Cell_CellGroupingRules_SectionGrouping" -> "agrupamiento de secciones", 
"Cell_LanguageCategory_Formula" -> "f\[OAcute]rmula matem\[AAcute]tica", 
"Cell_LanguageCategory_Mathematica" -> "matem\[AAcute]tica", 
"Cell_LanguageCategory_NaturalLanguage" -> "lenguaje natural", 
"Cells_CellLabel_Example" -> "ejemplo", 
"Cells_CellStyle_ExampleSubsection" -> "inciso de ejemplos", 
"Cells_CellStyle_Output" -> "salida", 
"Cells_CellStyle_Section" -> "secci\[OAcute]n", 
"Cell_TextClipboardType_InputText" -> "texto de entrada", 
"Cell_TextClipboardType_Package" -> "paquete", 
"Cell_TextClipboardType_PlainText" -> "texto sin formato", 
"CheckboxBar_Appearance_Horizontal" -> "horizontal", 
"CheckboxBar_Appearance_Row" -> "fila", 
"CheckboxBar_Appearance_Vertical" -> "vertical", 
"Classify_Method_LogisticRegression" -> "regresi\[OAcute]n log\[IAcute]stica", 
"Classify_Method_Markov" -> "m\[EAcute]todo de Markov", 
"Classify_Method_NearestNeighbors" -> "clasifica a partir de vecinos m\[AAcute]s cercanos", 
"Classify_Method_RandomForest" -> "clasifica usando los conjuntos de \[AAcute]rboles de decisi\[OAcute]n de Breiman-Cutler", 
"Classify_Method_SupportVectorMachine" -> "clasifica usando una m\[AAcute]quina de vectores de soporte", 
"Classify_PerformanceGoal_Memory" -> "minimiza los requisitos de almacenamiento del clasificador", 
"Classify_PerformanceGoal_Quality" -> "maximiza la precisi\[OAcute]n del clasificador", 
"Classify_PerformanceGoal_Speed" -> "maximiza la velocidad del clasificador", 
"Classify_PerformanceGoal_TrainingSpeed" -> "minimiza el tiempo producci\[OAcute]n del clasificador", 
"ClockGauge_GaugeFaceElementFunction_GlassSector" -> "sector de vidrio", 
"ClockGauge_GaugeFaceElementFunction_OscillatingSector" -> "sector de oscilaci\[OAcute]n", 
"ClockGauge_GaugeFrameElementFunction_BezelSector" -> "sector de basil", 
"ClockGauge_GaugeFrameElementFunction_GlassSector" -> "sector de vidrio", 
"ClockGauge_GaugeFrameElementFunction_GradientSector" -> "sector de gradiente", 
"ClockGauge_GaugeFrameElementFunction_NoiseSector" -> "sector de ruido", 
"ClockGauge_GaugeFrameElementFunction_Sector" -> "sector", 
"ClusteringComponents_Method_Agglomerate" -> "encuentre agrupamientos jer\[AAcute]rquicamente", 
"ClusteringComponents_Method_KMeans" -> "algoritmo de agrupamientos de medias k", 
"ClusteringComponents_Method_Optimize" -> "encuentre agrupamientos mediante optimizaci\[OAcute]n", 
"ClusteringComponents_Method_PAM" -> "encuentre agrupamientos mediante la separaci\[OAcute]n alrededor de medoides", 
"ColorDistance_DistanceFunction_CIE2000" -> "CIE94 con correcciones para mejorar la uniformidad de percepci\[OAcute]n de colores", 
"ColorDistance_DistanceFunction_CIE94" -> "diferencia de color definida en LCHColor", 
"ColorDistance_DistanceFunction_CIE94" -> "diferencia de color definida en LCHColor", 
"ColorSlider_AppearanceElements_Spectrum" -> "espectro", 
"ColorSlider_AppearanceElements_Swatch" -> "muestra", 
"ColorSlider_AppearanceElements_SwatchSpectrum" -> "muestra de espectro", 
"CommonOptions_AppearanceElements_HideControlsButton" -> "bot\[OAcute]n para ocultar controles", 
"CommonOptions_AppearanceElements_ResetButton" -> "bot\[OAcute]n para resetear", 
"CommonOptions_AppearanceElements_SnapshotButton" -> "bot\[OAcute]n de fotograf\[IAcute]a instant\[AAcute]nea", 
"CommonOptions_ChartLayout_Grouped" -> "agrupado", 
"CommonOptions_ChartLayout_Percentile" -> "de porcentaje", 
"CommonOptions_ChartLayout_Stacked" -> "apilado", 
"CommonOptions_ChartLayout_Stepped" -> "escalonado", 
"CommonOptions_ChartStyle_Pastel" -> "pastel", 
"CommonOptions_ColorFunction_Monochrome" -> "monocrom\[AAcute]tico", 
"CommonOptions_ColorFunction_Rainbow" -> "arcoiris", 
"CommonOptions_ColorFunction_TemperatureMap" -> "mapa de temperatura", 
"CommonOptions_EdgeLabels_Name" -> "nombre", 
"CommonOptions_EdgeShapeFunction_CarvedArrow" -> "flecha tallada", 
"CommonOptions_EdgeShapeFunction_Line" -> "l\[IAcute]nea", 
"CommonOptions_FontFamily_Arial" -> "arial", 
"CommonOptions_FontFamily_Courier" -> "courier", 
"CommonOptions_FontFamily_Helvetica" -> "helvetica", 
"CommonOptions_FontFamily_Times" -> "times", 
"CommonOptions_FontFamily_Verdana" -> "verdana", 
"CommonOptions_FontWeight_Heavy" -> "grande", 
"CommonOptions_FontWeight_Thin" -> "delgado", 
"CommonOptions_GaugeLabels_Unit" -> "unidad", 
"CommonOptions_GaugeLabels_Value" -> "valor", 
"CommonOptions_GaugeMarkers_Center" -> "centro", 
"CommonOptions_GaugeMarkers_Frame" -> "marco", 
"CommonOptions_GaugeMarkers_Scale" -> "escala", 
"CommonOptions_GaugeMarkers_ScaleRange" -> "rango de escala", 
"CommonOptions_GeoBackground_ContourMap" -> "mapa de contorno", 
"CommonOptions_GeoBackground_OutlineMap" -> "mapa de delimiado",
"CommonOptions_GeoBackground_ReliefMap" -> "mapa de relieve", 
"CommonOptions_GeoBackground_StreetMap" -> "mapa de calles", 
"CommonOptions_GeoProjection_Equirectangular" -> "equirrectangular", 
"CommonOptions_GeoProjection_Mercator" -> "de Mercator", 
"CommonOptions_GeoRange_Country" -> "pa\[IAcute]s", 
"CommonOptions_GeoRange_World" -> "mundo", 
"CommonOptions_GeoScaleBar_Kilometers" -> "kil\[OAcute]metros", 
"CommonOptions_GeoScaleBar_Miles" -> "millas", 
"CommonOptions_GraphHighlightStyle_Dashed" -> "de l\[IAcute]nea discontinua", 
"CommonOptions_GraphHighlightStyle_Dotted" -> "punteado", 
"CommonOptions_GraphHighlightStyle_VertexDiamond" -> "v\[EAcute]rtice de diamante", 
"CommonOptions_GraphLayout_CircularEmbedding" -> "v\[EAcute]rtices en un c\[IAcute]rculo", 
"CommonOptions_GraphLayout_RadialDrawing" -> "dibujo de radiales", 
"CommonOptions_GraphLayout_SpringElectricalEmbedding" -> "energ\[IAcute]a con bordes como resortes y v\[EAcute]rtices como cargas", 
"CommonOptions_GraphLayout_SpringEmbedding" -> "energ\[IAcute]a con bordes como resortes", 
"CommonOptions_GraphStyle_DiagramBlue" -> "diagrama azul", 
"CommonOptions_GraphStyle_DiagramGold" -> "diagrama dorado", 
"CommonOptions_GraphStyle_VintageDiagram" -> "diagrama de \[EAcute]poca", 
"CommonOptions_LegendFunction_Frame" -> "marco", 
"CommonOptions_LegendFunction_Panel" -> "panel", 
"CommonOptions_Lighting_Neutral" -> "neutral", 
"CommonOptions_NumberMultiplier_*" -> "*", 
"CommonOptions_NumberMultiplier_\[Times]" -> "\[Times]", 
"CommonOptions_NumberPoint_." -> ".", 
"CommonOptions_NumberPoint_," -> ",", 
"CommonOptions_NumberSeparator_," -> ",", 
"CommonOptions_NumberSeparator_ " -> "un espacio", 
"CommonOptions_PerformanceGoal_Quality" -> "calidad", 
"CommonOptions_PerformanceGoal_Speed" -> "velocidad", 
"CommonOptions_PlotLegends_Expressions" -> "expresiones", 
"CommonOptions_RotationAction_Clip" -> "recortar y no reajustar luego de rotar", 
"CommonOptions_RotationAction_Fit" -> "ajuste exacto luego de rotar", 
"CommonOptions_SplineKnots_Clamped" -> "uniformidad con fijaci\[OAcute]n", 
"CommonOptions_SplineKnots_Unclamped" -> "uniformidad sin fijaci\[OAcute]n", 
"CommonOptions_StreamColorFunction_Rainbow" -> "arcoiris", 
"CommonOptions_VectorColorFunction_Rainbow" -> "arcoiris", 
"CommonOptions_VectorStyle_Segment" -> "segmento", 
"CommonOptions_VertexLabels_Name" -> "nombre", 
"CommonOptions_VertexShapeFunction_Circle" -> "c\[IAcute]rculo",
"CommonOptions_VertexShapeFunction_ConcaveSquare" -> "cuadrado c\[OAcute]ncavo", 
"CommonOptions_VertexShapeFunction_Square" -> "cuadrado", 
"CommonOptions_WindowFrame_Generic" -> "ventana con borde gen\[EAcute]rico", 
"CommonOptions_WindowFrame_ModalDialog" -> "ventana de cuadro de di\[AAcute]logo modal", 
"CommonOptions_WindowFrame_Normal" -> "ventana ordinaria", 
"CommonOptions_WindowFrame_Palette" -> "ventana de paleta", 
"CommonOptions_WindowFrame_ThinFrame" -> "ventana ordinaria con borde delgado", 
"CommunityGraphPlot_CommunityBoundaryStyle_Pastel" -> "pastel", 
"CommunityGraphPlot_CommunityRegionStyle_Pastel" -> "pastel", 
"CommunityGraphPlot_Method_Hierarchical" -> "jer\[AAcute]rquico", 
"CommunityGraphPlot_Method_SpringElectrical" -> "energ\[IAcute]a con bordes como resortes", 
"Compile_CompilationTarget_C" -> "c\[OAcute]digo C", 
"Compile_RuntimeOptions_Quality" -> "calidad", 
"Compile_RuntimeOptions_Speed" -> "velocidad", 
"ConoverTest_AlternativeHypothesis_Greater" -> "mayor", 
"ConoverTest_AlternativeHypothesis_Less" -> "menor", 
"ConoverTest_AlternativeHypothesis_Unequal" -> "desigual", 
"ConoverTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"ConoverTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"ContinuousWaveletTransform_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ContinuousWaveletTransform_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"ContinuousWaveletTransform_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"ContinuousWaveletTransform_Padding_Reversed" -> "retrocesos de todo el arreglo", 
"ControllableModelQ_Method_Distribution" -> "distribuci\[OAcute]n", 
"ControllableModelQ_Method_Gramian" -> "prueba si la capacidad de control de Gramian es positiva definida",
"ControllableModelQ_Method_Matrix" -> "prueba si la matriz de capacidad de control tiene rango completo", 
"ControllableModelQ_Method_PBH" -> "prueba de rangos Popov\[Dash]Belevitch\[Dash]Hautus", 
"CornerFilter_Method_HarmonicMean" -> "media arm\[OAcute]nica", 
"CornerFilter_Method_HarrisStephens" -> "Harris y Stephens", 
"CornerFilter_Method_ShiTomasi" -> "ShiTomasi", 
"CorrelationTest_AlternativeHypothesis_Greater" -> "mayor", 
"CorrelationTest_AlternativeHypothesis_Less" -> "menor", 
"CorrelationTest_AlternativeHypothesis_Unequal" -> "desigual", 
"CorrelationTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"CoxModelFit_Method_Efron" -> "m\[EAcute]todo de Efron", 
"CoxModelFit_Method_Exact" -> "m\[EAcute]todo exacto", 
"CramerVonMisesTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"CreateDocument_CellDingbat_\[MathematicaIcon]" -> "\[MathematicaIcon]", 
"CreateDocument_DefaultDuplicateCellStyle_Input" -> "entrada", 
"CreateDocument_DefaultDuplicateCellStyle_Output" -> "salida", 
"CreateDocument_DefaultNewCellStyle_Input" -> "entrada", 
"CreateDocument_DefaultNewCellStyle_Text" -> "texto", 
"CreateDocument_StyleDefinitions_Default.nb" -> "Default.nb", 
"CreateWindow_CellDingbat_\[FilledSquare]" -> "\[FilledSquare]",
"CreateWindow_CellDingbat_\[MathematicaIcon]" -> "\[MathematicaIcon]", 
"CreateWindow_CellDingbat_\[SmallCircle]" -> "\[SmallCircle]", 
"DateDifference_CalendarType_Gregorian" -> "calendario solar gregoriano", 
"DateDifference_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DateDifference_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DateDifference_CalendarType_Julian" -> "calendario solar juliano", 
"DateDifference_DayCountConvention_Actual365" -> "un a\[NTilde]o de 365 d\[IAcute]as", 
"DateDifference_DayCountConvention_ActualActualICMA" -> "un a\[NTilde]o de divide en per\[IAcute]odos iguales para realizar pagos iguales", 
"DateDifference_DayCountConvention_ActualActualISDA" -> "c\[AAcute]lculo donde el primer d\[IAcute]a del per\[IAcute]odo se incluye y se excluye el \[UAcute]ltimo d\[IAcute]a", 
"DateDifference_DayCountConvention_Thirty360" -> "30 d\[IAcute]as del mes y 360 d\[IAcute]as del a\[NTilde]o", 
"DatePlus_CalendarType_Gregorian" -> "calendario solar gregoriano", 
"DatePlus_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DatePlus_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DatePlus_CalendarType_Julian" -> "calendario solar juliano", 
"DateRange_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DateRange_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DateRange_CalendarType_Julian" -> "calendario solar juliano", 
"DayCount_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DayCount_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayCount_CalendarType_Julian" -> "calendario solar juliano", 
"DayCount_HolidayCalendar_India" -> "India", 
"DayCount_HolidayCalendar_Sweden" -> "Suecia", 
"DayCount_HolidayCalendar_Turkey" -> "Turqu\[IAcute]a", 
"DayMatchQ_CalendarType_Gregorian" -> "calendario solar gregoriano", 
"DayMatchQ_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DayMatchQ_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayMatchQ_HolidayCalendar_Brazil" -> "Brasil", 
"DayMatchQ_HolidayCalendar_HongKong" -> "Hong Kong", 
"DayMatchQ_HolidayCalendar_Israel" -> "Israel", 
"DayMatchQ_HolidayCalendar_UnitedStates" -> "Estados Unidos", 
"DayName_CalendarType_Gregorian" -> "calendario solar gregoriano", 
"DayName_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayName_CalendarType_Julian" -> "calendario solar juliano", 
"DayPlus_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DayPlus_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayPlus_CalendarType_Julian" -> "calendario solar juliano", 
"DayPlus_HolidayCalendar_India" -> "India", 
"DayPlus_HolidayCalendar_Turkey" -> "Turqu\[IAcute]a", 
"DayRange_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DayRange_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayRange_CalendarType_Julian" -> "calendario solar juliano", 
"DayRange_HolidayCalendar_India" -> "India", 
"DayRange_HolidayCalendar_Turkey" -> "Turqu\[IAcute]a", 
"DayRound_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"DayRound_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"DayRound_CalendarType_Julian" -> "calendario solar juliano", 
"DeleteSmallComponents_Method_Cluster" -> "maximizaci\[OAcute]n de la varianza de cl\[UAcute]ster", 
"DeleteSmallComponents_Method_Mean" -> "usar la media de tama\[NTilde]os de componentes como umbral", 
"DeleteSmallComponents_Method_Median" -> "usar la mediana de tama\[NTilde]os de componentes como umbral", 
"DensityHistogram_ChartElementFunction_Bubble" -> "burb\[UAcute]ja", 
"DensityHistogram_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"DensityHistogram_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"DensityHistogram_ChartElementFunction_NoiseRectangle" -> "rect\[AAcute]ngulo de ruido", 
"DensityHistogram_ChartElementFunction_SphereBubble" -> "burj\[UAcute]ja de esfera", 
"DifferenceRootReduce_Method_Homogeneous" -> "homog\[EAcute]neo", 
"DifferentialRootReduce_Method_Homogeneous" -> "homog\[EAcute]neo", 
"DifferentiatorFilter_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"Dilation_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"DimensionalCombinations_IncludeQuantities_PhysicalConstants" -> "incluye una lista est\[AAcute]ndar de cantidades", 
"DiscretePlot3D_PlotMarkers_Point" -> "punto", 
"DiscretePlot3D_PlotMarkers_Sphere" -> "esfera", 
"DiscretePlot_ExtentElementFunction_ArrowRectangle" -> "flecha rectangular", 
"DiscretePlot_ExtentMarkers_Empty" -> "marcador de borde de disco vac\[IAcute]o", 
"DiscretePlot_ExtentMarkers_Filled" -> "marcador de borde de disco lleno", 
"DiscretePlot_ExtentMarkers_Point" -> "punto", 
"DiscretePlot_PlotMarkers_Point" -> "punto", 
"DiscreteRiccatiSolve_Method_Eigensystem" -> "m\[EAcute]todo basado en la descomposici\[OAcute]n de Eigen", 
"DiscreteRiccatiSolve_Method_Schur" -> "m\[EAcute]todo basado en la descomposici\[OAcute]n de Schur", 
"DiscreteWaveletData_Method_IntegerLifting" -> "elevaci\[OAcute]n de n\[UAcute]mero entero", 
"DiscreteWaveletData_Padding_Extrapolated" -> "extrapolado", 
"DiscreteWaveletData_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"DiscreteWaveletData_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"DiscreteWaveletData_Padding_ReflectedDifferences" -> "diferencias de reflexiones del arreglo en el l\[IAcute]mite", 
"DiscreteWaveletData_Padding_Reversed" -> "reversiones de todo el arreglo", 
"DiscreteWaveletPacketTransform_Padding_Extrapolated" -> "extrapolado", 
"DiscreteWaveletPacketTransform_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"DiscreteWaveletPacketTransform_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"DiscreteWaveletPacketTransform_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"DiscreteWaveletPacketTransform_Padding_Reversed" -> "reversiones de todo el arreglo", 
"DiscreteWaveletTransform_Padding_Extrapolated" -> "extrapolado", 
"DiscreteWaveletTransform_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"DiscreteWaveletTransform_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"DiscreteWaveletTransform_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"DiscreteWaveletTransform_Padding_Reversed" -> "reversiones de todo el arreglo", 
"Discriminant_Method_BezoutMatrix" -> "matriz de Bezout", 
"Discriminant_Method_Modular" -> "modular", 
"Discriminant_Method_Subresultants" -> "subresultante", 
"Discriminant_Method_SylvesterMatrix" -> "matriz de Sylvester", 
"DistributionChart_ChartElementFunction_BoxWhisker" -> "caja y bigotes", 
"DistributionChart_ChartElementFunction_Density" -> "densidad", 
"DistributionChart_ChartElementFunction_GlassQuantile" -> "cuantil de vidrio", 
"DistributionChart_ChartElementFunction_HistogramDensity" -> "densidad de histograma", 
"DistributionChart_ChartElementFunction_SmoothDensity" -> "densidad de alisado", 
"DistributionFitTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"DocumentNotebook_CellDingbat_\[FilledSquare]" -> "\[FilledSquare]", 
"DocumentNotebook_CellDingbat_\[MathematicaIcon]" -> "\[MathematicaIcon]", 
"DocumentNotebook_CellDingbat_\[SmallCircle]" -> "\[SmallCircle]", 
"EdgeDetect_Method_ShenCastan" -> "m\[EAcute]todo de Shen-Castan", 
"Eigensystem_Method_Arnoldi" -> "m\[EAcute]todo iterativo de Arnoldi", 
"Eigensystem_Method_Banded" -> "m\[EAcute]todo directo de matriz en bandas", 
"Eigensystem_Method_Direct" -> "m\[EAcute]todo directo para encontrar todos los valores propios", 
"Eigensystem_Method_FEAST" -> "m\[EAcute]todo iterativo FEAST para encontrar valores propios en un intervalo", 
"Eigenvalues_Method_Arnoldi" -> "m\[EAcute]todo iterativo de Arnoldi", 
"Eigenvalues_Method_Banded" -> "m\[EAcute]todo directo de matriz en bandas", 
"Eigenvalues_Method_Direct" -> "m\[EAcute]todo directo para encontrar todos los valores propios", 
"Eigenvalues_Method_FEAST" -> "m\[EAcute]todo iterativo FEAST para encontrar valores propios en un intervalo", 
"Eigenvectors_Method_Arnoldi" -> "m\[EAcute]todo iterativo de Arnoldi", 
"Eigenvectors_Method_Banded" -> "m\[EAcute]todo directo de matriz en bandas", 
"Eigenvectors_Method_Direct" -> "m\[EAcute]todo directo para encontrar todos los valores propios", 
"Eigenvectors_Method_FEAST" -> "m\[EAcute]todo iterativo FEAST para encontrar valores propios en un intervalo", 
"EstimatedDistribution_ParameterEstimator_MethodOfCentralMoments" -> "coincide momentos centrales", 
"EstimatedDistribution_ParameterEstimator_MethodOfCumulants" -> "coincide cumulantes", 
"EstimatedDistribution_ParameterEstimator_MethodOfFactorialMoments" -> "coincide momentos factoriales", 
"EstimatedDistribution_ParameterEstimator_MethodOfMoments" -> "coincide momentos brutos", 
"EstimatedProcess_ProcessEstimator_MaximumLikelihood" -> "maximiza la funci\[OAcute]n de log-verosimilitud", 
"EstimatedProcess_ProcessEstimator_MethodOfMoments" -> "coincide momentos brutos", 
"EstimatorGains_Method_Ackermann" -> "m\[EAcute]todo de Ackermann", 
"EstimatorGains_Method_KNVD" -> "m\[EAcute]todo de Kautsky\[Dash]Nichols\[Dash]Van Dooren", 
"Expectation_Method_Integrate" -> "Integrar", 
"Expectation_Method_Moment" -> "momento", 
"Expectation_Method_Quantile" -> "de porcentaje", 
"Expectation_Method_Sum" -> "suma", 
"ExponentialGeneratingFunction_Method_Holonomic" -> "hol\[OAcute]nico", 
"ExpressionCell_Evaluator_Local" -> "local", 
"ExpressionCell_LanguageCategory_Formula" -> "f\[OAcute]rmula matem\[AAcute]tica", 
"ExpressionCell_LanguageCategory_Mathematica" -> "matem\[AAcute]tica", 
"ExpressionCell_LanguageCategory_NaturalLanguage" -> "lenguaje natural", 
"ExpressionCell_LanguageCategory_Output" -> "salida", 
"FileNameJoin_OperatingSystem_MacOSX" -> "MacOSX", 
"FileNameJoin_OperatingSystem_Unix" -> "Unix", 
"FileNameJoin_OperatingSystem_Windows" -> "Windows", 
"FileNameSplit_OperatingSystem_MacOSX" -> "MacOSX", 
"FileNameSplit_OperatingSystem_Unix" -> "Unix", 
"FileNameSplit_OperatingSystem_Windows" -> "Windows", 
"FinancialDerivative_Method_Binomial" -> "binomios", 
"FindArgMax_Method_ConjugateGradient" -> "gradiente conjugada", 
"FindArgMax_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindArgMax_Method_PrincipalAxis" -> "eje principal", 
"FindArgMin_Method_ConjugateGradient" -> "gradiente conjugada", 
"FindArgMin_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindArgMin_Method_PrincipalAxis" -> "eje principal", 
"FindClusters_DistanceFunction_EarthMoverDistance" -> "distancia de cavadora", 
"FindClusters_Method_Agglomerate" -> "encuentre agrupamientos jer\[AAcute]rquicamente", 
"FindClusters_Method_Optimize" -> "encuentre agrupamientos mediante optimizaci\[OAcute]n", 
"FindDistributionParameters_ParameterEstimator_MethodOfCentralMoments" -> "coincide momentos centrales", 
"FindDistributionParameters_ParameterEstimator_MethodOfCumulants" -> "coincide cumulantes", 
"FindDistributionParameters_ParameterEstimator_MethodOfFactorialMoments" -> "coincide momentos factoriales", 
"FindDistributionParameters_ParameterEstimator_MethodOfMoments" -> "coincide momentos brutos", 
"FindFit_Gradient_FiniteDifference" -> "diferencia finita", 
"FindFit_Method_ConjugateGradient" -> "gradiente conjugada", 
"FindFit_Method_Gradient" -> "gradiente", 
"FindFit_Method_LevenbergMarquardt" -> "m\[EAcute]todo de Levenberg-Marquardt", 
"FindFit_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindFit_Method_QuasiNewton" -> "m\[EAcute]todo de Quasi-Newton", 
"FindGeneratingFunction_FunctionSpace_Polynomial" -> "polinomios", 
"FindGeometricTransform_Method_FindFit" -> "encuentre y ajuste",
"FindGeometricTransform_Method_ImageAlign" -> "recupera una imagen y la al\[IAcute]nea", 
"FindGeometricTransform_Method_Linear" -> "solucionador linear basado en SVD", 
"FindGeometricTransform_Method_RANSAC" -> "m\[EAcute]todo de consenso de muestra aleatoria", 
"FindGeometricTransform_Transformation_Affine" -> "transformaci\[OAcute]n linear y traslaci\[OAcute]n", 
"FindGeometricTransform_Transformation_Perspective" -> "transformaci\[OAcute]n fraccional lineal", 
"FindGeometricTransform_Transformation_Rigid" -> "traslaci\[OAcute]n y rotaci\[OAcute]n", 
"FindGeometricTransform_Transformation_Similarity" -> "traslaci\[OAcute]n, rotaci\[OAcute]n y escala", 
"FindGeometricTransform_Transformation_Translation" -> "s\[OAcute]lo traslaci\[OAcute]n", 
"FindGraphCommunities_Method_Centrality" -> "agrupamiento basado en centralidad", 
"FindGraphCommunities_Method_CliquePercolation" -> "agrupamiento basado en percolaci\[OAcute]n de clique", 
"FindGraphCommunities_Method_Hierarchical" -> "agrupamiento basado en jerarqu\[IAcute]as", 
"FindGraphCommunities_Method_Modularity" -> "agrupamiento basado en modalidad", 
"FindGraphCommunities_Method_Spectral" -> "agrupamiento basado en espectrales", 
"FindMaximum_Method_ConjugateGradient" -> "gradiente conjugada",
"FindMaximum_Method_LevenbergMarquardt" -> "m\[EAcute]todo de Levenberg-Marquardt", 
"FindMaximum_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindMaximum_Method_PrincipalAxis" -> "eje principal", 
"FindMaxValue_Method_ConjugateGradient" -> "gradiente conjugada", 
"FindMaxValue_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindMaxValue_Method_PrincipalAxis" -> "eje principal", 
"FindMinimum_Method_ConjugateGradient" -> "gradiente conjugada",
"FindMinimum_Method_InteriorPoint" -> "punto interior", 
"FindMinimum_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindMinimum_Method_PrincipalAxis" -> "eje principal", 
"FindMinimum_Method_QuasiNewton" -> "m\[EAcute]todo de Quasi-Newton", 
"FindMinValue_Method_ConjugateGradient" -> "gradiente conjugada", 
"FindMinValue_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindMinValue_Method_PrincipalAxis" -> "eje principal", 
"FindRoot_Method_Brent" -> "m\[EAcute]todo de Brent", 
"FindRoot_Method_Newton" -> "m\[EAcute]todo de Newton", 
"FindRoot_Method_Secant" -> "secante", 
"FindShortestPath_Method_BellmanFord" -> "m\[EAcute]todo de Bellman-Ford", 
"FindShortestPath_Method_Dijkstra" -> "m\[EAcute]todo de Dijkstra", 
"FindShortestPath_Method_UnitWeight" -> "peso espec\[IAcute]fico", 
"FindShortestTour_Method_AllTours" -> "todas las rutas", 
"FindShortestTour_Method_Greedy" -> "m\[EAcute]todo voraz", 
"FindShortestTour_Method_RemoveCrossings" -> "eliminar cruces", 
"FindShortestTour_Method_SimulatedAnnealing" -> "recocido simulado", 
"FindShortestTour_Method_SpaceFillingCurve" -> "curva de compilaci\[OAcute]n", 
"FindSpanningTree_Method_Kruskal" -> "m\[EAcute]todo de Krustal", 
"FindSpanningTree_Method_MinimumCostAborescence" -> "costo m\[IAcute]nimo de cobertura", 
"FindSpanningTree_Method_Prim" -> "m\[EAcute]todo de Prim", 
"FindThreshold_Method_Cluster" -> "maximizaci\[OAcute]n de la varianza de cl\[UAcute]ster", 
"FindThreshold_Method_Entropy" -> "histograma de minimizaci\[OAcute]n de entrop\[IAcute]a", 
"FindThreshold_Method_Mean" -> "use la media como umbral", 
"FindThreshold_Method_Median" -> "use la mediana como umbral", 
"FindThreshold_Method_MinimumError" -> "error m\[IAcute]nimo", 
"FisherRatioTest_AlternativeHypothesis_Greater" -> "mayor", 
"FisherRatioTest_AlternativeHypothesis_Less" -> "manor", 
"FisherRatioTest_AlternativeHypothesis_Unequal" -> "desigual", 
"FisherRatioTest_VerifyTestAssumptions_" -> "verifica que todos los datos se distribuyen normalmente", 
"FisherRatioTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"GainPhaseMargins_FeedbackType_Positive" -> "positivo", 
"GaussianFilter_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"GaussianMatrix_Method_Bessel" -> "determina elementos matrices", 
"GaussianMatrix_Method_Gaussian" -> "gaussiano", 
"GeneralizedLinearModelFit_CovarianceEstimatorFunction_ObservedInformation" -> "informaci\[OAcute]n observada", 
"GeneralizedLinearModelFit_DispersionEstimatorFunction_PearsonChiSquare" -> "prueba \[Chi]\.b2 de Pearson", 
"GeneralizedLinearModelFit_ExponentialFamily_Binomial" -> "binomio", 
"GeneralizedLinearModelFit_ExponentialFamily_Gamma" -> "gamma", 
"GeneralizedLinearModelFit_ExponentialFamily_Gaussian" -> "gaussiano", 
"GeneralizedLinearModelFit_ExponentialFamily_InverseGaussian" -> "gaussiano invertido", 
"GeneralizedLinearModelFit_ExponentialFamily_Poisson" -> "de Poisson", 
"GeneralizedLinearModelFit_LinkFunction_IdentityLink" -> "usado para referirse a gamma", 
"GeneralizedLinearModelFit_LinkFunction_ReciprocalLink" -> "usado para referirse a gaussiano", 
"GeoRegionValuePlot_UnitSystem_Imperial" -> "imperial", 
"GeoRegionValuePlot_UnitSystem_Metric" -> "m\[EAcute]trico", 
"Get_CharacterEncoding_MacintoshRoman" -> "romano para Macintosh", 
"Get_CharacterEncoding_Symbol" -> "s\[IAcute]mbolo", 
"GoodmanKruskalGammaTest_AlternativeHypothesis_Greater" -> "mayor", "GoodmanKruskalGammaTest_AlternativeHypothesis_Less" -> "menor", 
"GoodmanKruskalGammaTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"GraphAssortativity_DataType_Quantitative" -> "cuantitativo", 
"GraphDistanceMatrix_Method_Dijkstra" -> "m\[EAcute]todo de Dijkstra", 
"GraphDistanceMatrix_Method_FloydWarshall" -> "m\[EAcute]todo de Floyd-Warshall", 
"GraphDistanceMatrix_Method_Johnson" -> "M\[EAcute]todo de Johnson", 
"GraphDistanceMatrix_Method_UnitWeight" -> "peso espec\[IAcute]fico", 
"GraphDistance_Method_Dijkstra" -> "m\[EAcute]todo de Dijkstra",
"GraphDistance_Method_FloydWarshall" -> "m\[EAcute]todo de Floyd-Warshall", 
"GraphDistance_Method_Johnson" -> "M\[EAcute]todo de Johnson", 
"GraphDistance_Method_UnitWeight" -> "peso espec\[IAcute]fico", 
"Graphics3D_Lighting_Neutral" -> "neutral", 
"GraphPlot3D_Method_RandomEmbedding" -> "v\[EAcute]rtices distribuidos de forma aleatoria", 
"GraphPlot3D_Method_SpiralEmbedding" -> "v\[EAcute]rtices en una espiral en 3D proyectada en 2D", 
"GraphPlot3D_Method_SpringElectricalEmbedding" -> "energ\[IAcute]a con bordes como resortes y v\[EAcute]rtices como cargas", "GraphPlot3D_Method_SpringEmbedding" -> "energ\[IAcute]a con bordes como resortes", 
"GraphPlot3D_PackingMethod_ClosestPacking" -> "embalaje aproximado m\[AAcute]s cercano desde la parte superior izquierda", 
"GraphPlot3D_PackingMethod_Layered" -> "organizado en capas desde la parte superior izquierda", 
"GraphPlot3D_PackingMethod_NestedGrid" -> "organizado en una parrilla anidada", 
"GraphPlot_Method_CircularEmbedding" -> "v\[EAcute]rtices en un c\[IAcute]rculo", 
"GraphPlot_Method_HighDimensionalEmbedding" -> "energ\[IAcute]a on bordes como resortes en alta dimensi\[OAcute]n",
"GraphPlot_Method_LinearEmbedding" -> "v\[EAcute]rtices en una l\[IAcute]nea", 
"GraphPlot_Method_SpringElectricalEmbedding" -> "energ\[IAcute]a con bordes como resortes y v\[EAcute]rtices como cargas", "GraphPlot_Method_SpringEmbedding" -> "energ\[IAcute]a con bordes como resortes", 
"GraphPlot_PackingMethod_ClosestPacking" -> "embalaje aproximado m\[AAcute]s cercano desde la parte superior izquierda", 
"GraphPlot_PackingMethod_ClosestPackingCenter" -> "embalaje aproximado m\[AAcute]s cercano desde el centro", 
"GraphPlot_PackingMethod_Layered" -> "organizado en capas desde la parte superior izquierda", 
"GraphPlot_PackingMethod_NestedGrid" -> "organizado en una parrilla anidada", 
"GridBox_ColumnAlignments_." -> ".", 
"GridBox_GridDefaultElement_0" -> "0", 
"Grid_DefaultElement_\[HappySmiley]" -> "\[HappySmiley]", 
"Grid_DefaultElement_\[Placeholder]" -> "\[Placeholder]", 
"GroebnerBasis_Method_Buchberger" -> "m\[EAcute]todo de Buchberger", 
"GroebnerBasis_Method_GroebnerWalk" -> "m\[EAcute]todo de GroebnerWalk", 
"HighlightImage_Method_Blur" -> "desenfocar el fondo", 
"HighlightImage_Method_Boundary" -> "resaltar el l\[IAcute]mite del primer plano con espesor predeterminado", 
"HighlightImage_Method_Brightness" -> "oscurecer el fondo", 
"HighlightImage_Method_Fade" -> "desvanecer el fondo", 
"HighlightImage_Method_Saturation" -> "convertir el fondo a escala de grises", 
"HighpassFilter_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"HilbertFilter_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"Histogram3D_ChartElementFunction_Cone" -> "cono", 
"Histogram3D_ChartElementFunction_Cylinder" -> "cilindro", 
"Histogram3D_ChartElementFunction_FadingCube" -> "cubo que desvanece", 
"Histogram3D_ChartElementFunction_GradientScaleCube" -> "cubo de escala gradiente", 
"Histogram_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"Histogram_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"Histogram_ChartElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo gradiente", 
"Histogram_ChartElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"Histogram_ScalingFunctions_Log" -> "utilizar una escala logar\[IAcute]tmica", 
"Histogram_ScalingFunctions_Reverse" -> "invertir la direcci\[OAcute]n de coordenadas", 
"HoeffdingDTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"HorizontalGauge_GaugeFaceElementFunction_ArrowRectangle" -> "flecha rectangular", 
"HorizontalGauge_GaugeFaceElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"HorizontalGauge_GaugeFaceElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"HorizontalGauge_GaugeFaceElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo gradiente", 
"HorizontalGauge_GaugeFaceElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"HorizontalGauge_GaugeFrameElementFunction_ArrowRectangle" -> "flecha rectangular", 
"HorizontalGauge_GaugeFrameElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"HorizontalGauge_GaugeFrameElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"HorizontalGauge_GaugeFrameElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"HorizontalGauge_GaugeFrameElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"Hyperlink_Appearance_DialogBox" -> "caja de di\[AAcute]logo", 
"Hyperlink_Appearance_Frameless" -> "sin marco", 
"Hyperlink_Appearance_Palette" -> "paleta", 
"ImageAccumulate_Method_CompensatedSummation" -> "suma compensada", 
"ImageAlign_Transformation_Affine" -> "transformaci\[OAcute]n linear y traslaci\[OAcute]n", 
"ImageAlign_Transformation_Perspective" -> "transformaci\[OAcute]n fraccional lineal", 
"ImageAlign_Transformation_Rigid" -> "traslaci\[OAcute]n y rotaci\[OAcute]n", 
"ImageAlign_Transformation_Similarity" -> "traslaci\[OAcute]n, rotaci\[OAcute]n y escala", 
"ImageAlign_Transformation_Translation" -> "s\[OAcute]lo traslaci\[OAcute]n", 
"Image_ColorSpace_CMYK" -> "cian, magenta, amarillo, negro", 
"Image_ColorSpace_Grayscale" -> "escala de grises", 
"Image_ColorSpace_HSB" -> "tono, saturaci\[OAcute]n, brillo", 
"Image_ColorSpace_RGB" -> "rojo, verde, azul", 
"ImageConvolve_Padding_Reversed" -> "reversiones de todo el arreglo", 
"ImageCorrespondingPoints_Transformation_Perspective" -> "transformaci\[OAcute]n fraccional lineal", 
"ImageCorrespondingPoints_Transformation_Rigid" -> "traslaci\[OAcute]n y rotaci\[OAcute]n", 
"ImageCorrespondingPoints_Transformation_Similarity" -> "traslaci\[OAcute]n, rotaci\[OAcute]n y escala", 
"ImageCorrespondingPoints_Transformation_Translation" -> "s\[OAcute]lo traslaci\[OAcute]n", 
"ImageCrop_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ImageDeconvolve_Method_DampedLS" -> "m\[IAcute]nimos cuadrados amortiguados, regularizaci\[OAcute]n generalizada de Tikhonov", 
"ImageDeconvolve_Method_Hybrid" -> "regularizaci\[OAcute]n de bidiagonalizaci\[OAcute]n de Tikhonov-Golub-Kahan", 
"ImageDeconvolve_Method_RichardsonLucy" -> "deconvoluci\[OAcute]n iterativa de Richardson-Lucy", 
"ImageDeconvolve_Method_SteepestDescent" -> "norma residual modificada de la m\[AAcute]xima pendiente", 
"ImageDeconvolve_Method_TotalVariation" -> "variaci\[OAcute]n total", 
"ImageDeconvolve_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ImageDistance_DistanceFunction_EarthMoverDistance" -> "distancia de cavadora", 
"ImageDistance_DistanceFunction_MutualInformationVariation" -> "variaci\[OAcute]n de informaci\[OAcute]n mutua", 
"ImageDistance_DistanceFunction_NormalizedMutualInformationVariation" -> "variaci\[OAcute]n de informaci\[OAcute]n mutua normalizada", 
"ImageHistogram_Appearance_RGB" -> "rojo, verde, azul", 
"ImageHistogram_Appearance_Separated" -> "hacer histogramas separados para cada canal", 
"ImageHistogram_Appearance_Stacked" -> "apilar valores para cada canal", 
"ImageHistogram_Appearance_Transparent" -> "mostrar canales superpuestos usando transparencia", 
"ImageKeypoints_KeypointStrength_Legacy" -> "Legacy", 
"ImageLines_Method_RANSAC" -> "m\[EAcute]todo de consenso de muestra aleatoria", 
"ImagePerspectiveTransformation_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ImagePerspectiveTransformation_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"ImagePerspectiveTransformation_Resampling_Bilinear" -> "bilinear", 
"ImagePerspectiveTransformation_Resampling_Nearest" -> "vecino m\[AAcute]s cercano", 
"ImageResize_Resampling_CatmullRom" -> "interpolaci\[OAcute]n polin\[OAcute]mica c\[UAcute]bica de Catmull-Rom", 
"ImageResize_Resampling_Gaussian" -> "remuestreo ponderado gaussiano", 
"ImageResize_Resampling_Linear" -> "interpolaci\[OAcute]n lineal por partes", 
"ImageResize_Resampling_Nearest" -> "vecino m\[AAcute]s cercano", 
"ImageRotate_Resampling_CatmullRom" -> "interpolaci\[OAcute]n polin\[OAcute]mica c\[UAcute]bica de Catmull-Rom", 
"ImageRotate_Resampling_Lanczos" -> "m\[EAcute]todo de Lanczos",
"ImageRotate_Resampling_Nearest" -> "vecino m\[AAcute]s cercano", 
"ImageRotate_Resampling_Quadratic" -> "interpolaci\[OAcute]n de spline de orden 2", 
"ImageTransformation_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"ImageTransformation_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"ImageValue_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"ImageValue_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"ImageValue_Padding_Reflected" -> "reflexiones del arreglo en el l\[IAcute]mite", 
"ImageValue_Padding_Reversed" -> "reversiones de todo el arreglo", 
"ImageValue_Resampling_Nearest" -> "vecino m\[AAcute]s cercano",
"IndependenceTest_AlternativeHypothesis_Greater" -> "mayor", 
"IndependenceTest_AlternativeHypothesis_Less" -> "menor", 
"IndependenceTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"IndependenceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"Inpaint_Method_Diffusion" -> "m\[EAcute]todo iterativo de difusi\[OAcute]n isotr\[OAcute]pica", 
"Inpaint_Method_FastMarching" -> "m\[EAcute]todo de avance r\[AAcute]pido", 
"Inpaint_Method_NavierStokes" -> "m\[EAcute]todo de Navier-Stokes", 
"Inpaint_Method_TextureSynthesis" -> "m\[EAcute]todo de s\[IAcute]ntesis textura de mejor ajuste  mediante muestreo aleatorio", 
"Inpaint_Method_TotalVariation" -> "m\[EAcute]todo de variaci\[OAcute]n total iterativo", 
"InputField_Appearance_Framed" -> "con marco", 
"InputField_Appearance_Frameless" -> "sin marco", 
"InteractiveTradingChart_Appearance_Line" -> "l\[IAcute]nea", 
"InteractiveTradingChart_Appearance_OHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado", 
"Interpolation_Method_Hermite" -> "m\[EAcute]todo de Hermite", 
"Interpolation_Method_Spline" -> "m\[EAcute]todo de Spline", 
"IntervalSlider_Appearance_Generic" -> "gen\[EAcute]rico", 
"IntervalSlider_Appearance_Locator" -> "localizador", 
"IntervalSlider_Appearance_Vertical" -> "vertical", 
"IntervalSlider_Method_Free" -> "libre", 
"IntervalSlider_Method_Push" -> "impulsar", 
"IntervalSlider_Method_Stop" -> "detener", 
"InverseContinuousWaveletTransform_Method_DeltaFunction" -> "funci\[OAcute]n Delta", 
"InverseContinuousWaveletTransform_Method_LeastSquares" -> "m\[IAcute]nimos cuadrados", 
"Inverse_Method_CofactorExpansion" -> "expansi\[OAcute]n de cofactores de Laplace", 
"Inverse_Method_DivisionFreeRowReduction" -> "reducci\[OAcute]n de fila sin divisi\[OAcute]n", 
"Inverse_Method_OneStepRowReduction" -> "reducci\[OAcute]n de fila en un paso", 
"JarqueBeraALMTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"JuliaSetPlot_Method_DistanceEstimation" -> "estimaci\[OAcute]n de distancia", 
"JuliaSetPlot_Method_EscapeTime" -> "tiempo de escape", 
"JuliaSetPlot_Method_InverseIteration" -> "iteraci\[OAcute]n inversa", 
"JuliaSetPlot_Method_OrbitDetection" -> "detecci\[OAcute]n de \[OAcute]rbita", 
"KagiChart_ScalingFunctions_Log" -> "utilizar una escala logar\[IAcute]tmica", 
"KalmanEstimator_Method_CurrentEstimator" -> "construye el estimador actual", 
"KalmanEstimator_Method_PredictionEstimator" -> "construye el estimador de predicci\[OAcute]n", 
"KendallTauTest_AlternativeHypothesis_Greater" -> "mayor", 
"KendallTauTest_AlternativeHypothesis_Less" -> "menor", 
"KendallTauTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"KendallTauTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"KolmogorovSmirnovTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"KuiperTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"LayeredGraphPlot_PackingMethod_ClosestPackingCenter" -> "embalaje aproximado m\[AAcute]s cercano desde el centro", 
"LayeredGraphPlot_PackingMethod_Layered" -> "organizado en capas desde la parte superior izquierda", 
"LayeredGraphPlot_PackingMethod_NestedGrid" -> "organizado en una parrilla anidada", 
"LeapYearQ_CalendarType_Islamic" -> "calendario lunar isl\[AAcute]mico", 
"LeapYearQ_CalendarType_Jewish" -> "calendario lunisolar jud\[IAcute]o", 
"LeapYearQ_CalendarType_Julian" -> "calendario solar juliano", 
"LeveneTest_AlternativeHypothesis_Greater" -> "mayor", 
"LeveneTest_AlternativeHypothesis_Less" -> "menor", 
"LeveneTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"LeveneTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"LiftingWaveletTransform_Method_IntegerLifting" -> "elevaci\[OAcute]n de n\[UAcute]mero entero", 
"LinearProgramming_Method_InteriorPoint" -> "punto interior", 
"LinearProgramming_Method_RevisedSimplex" -> "m\[EAcute]todo de s\[IAcute]mplice revisado", 
"LinearProgramming_Method_Simplex" -> "s\[IAcute]mplice", 
"LinearSolve_Method_Cholesky" -> "m\[EAcute]todo de Cholesky para matrices definidas positivas hermitianas", 
"LinearSolve_Method_CofactorExpansion" -> "expansi\[OAcute]n de cofactores de Laplace", 
"LinearSolve_Method_DivisionFreeRowReduction" -> "m\[EAcute]todo de Bareiss de reducci\[OAcute]n de filas de divisi\[OAcute]n libre", 
"LinearSolve_Method_Krylov" -> "solucionador disperso iterativo de Krylov", 
"LinearSolve_Method_Multifrontal" -> "multifrontal", 
"LineBreakChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"LineBreakChart_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"LineBreakChart_ChartElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo gradiente", 
"LineBreakChart_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo oblicuo", 
"LineBreakChart_ChartElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"LineBreakChart_ScalingFunctions_Log" -> "utilizar una escala logar\[IAcute]tmica", 
"LineBreakChart_TrendStyle_BlueYellow" -> "azul y amarillo", 
"LineLegend_LegendLayout_Column" -> "columna", 
"LineLegend_LegendLayout_ReversedColumn" -> "columna revertida",
"LineLegend_LegendLayout_ReversedRow" -> "fila revertida", 
"LineLegend_LegendLayout_Row" -> "fila", 
"LineLegend_LegendMarkers_\[FilledDiamond]" -> "\[FilledDiamond]", 
"LinkConnect_LinkProtocol_TCPIP" -> "Protocolo de Control de Transmisi\[OAcute]n y de Internet", 
"LinkCreate_LinkProtocol_TCPIP" -> "Protocolo de Control de Transmisi\[OAcute]n y de Internet", 
"ListDeconvolve_Method_DampedLS" -> "m\[IAcute]nimos cuadrados amortiguados, regularizaci\[OAcute]n generalizada de Tikhonov", 
"ListDeconvolve_Method_Hybrid" -> "regularizaci\[OAcute]n de bidiagonalizaci\[OAcute]n de Tikhonov-Golub-Kahan", 
"ListDeconvolve_Method_RichardsonLucy" -> "deconvoluci\[OAcute]n iterativa de Richardson-Lucy", 
"ListDeconvolve_Method_SteepestDescent" -> "norma residual modificada de la m\[AAcute]xima pendiente", 
"ListDeconvolve_Padding_Periodic" -> "repeticiones c\[IAcute]clicas de todo el arreglo", 
"ListInterpolation_Method_Hermite" -> "m\[EAcute]todo de Hermite", 
"ListInterpolation_Method_Spline" -> "Spline", 
"ListPicker_Appearance_Framed" -> "con marco", 
"ListPicker_Appearance_Frameless" -> "sin marco", 
"ListPolarPlot_PlotMarkers_\[FilledCircle]" -> "\[FilledCircle]", 
"LocationEquivalenceTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"LocationEquivalenceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"LocationEquivalenceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"LocationEquivalenceTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"LocationTest_AlternativeHypothesis_Greater" -> "mayor", 
"LocationTest_AlternativeHypothesis_Less" -> "menor", 
"LocationTest_AlternativeHypothesis_Unequal" -> "desigual", 
"LocationTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"LocationTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"LocationTest_VerifyTestAssumptions_EqualVariance" -> "igual varianza", 
"LocationTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"LogRankTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"LowpassFilter_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"LunarEclipse_EclipseType_Partial" -> "devuelve el siguiente eclipse parcial", 
"LunarEclipse_EclipseType_Total" -> "devuelve el siguiente eclipse total", 
"Manipulate_ControllerMethod_Absolute" -> "absoluto", 
"Manipulate_ControllerPath_BuiltIn" -> "controlador integrado en un equipo", 
"Manipulate_ControllerPath_Detachable" -> "controlador no integrado en un equipo", 
"Manipulate_ControllerPath_Gamepad" -> "controlador que t\[IAcute]picamente incluye dos controles anal\[OAcute]gicos", 
"Manipulate_ControllerPath_Joystick" -> "controlador que t\[IAcute]picamente incluye un control anal\[OAcute]gico primario", 
"Manipulator_Appearance_Labeled" -> "etiquetado", 
"Manipulator_Appearance_Open" -> "abierto", 
"MannWhitneyTest_AlternativeHypothesis_Greater" -> "mayor", 
"MannWhitneyTest_AlternativeHypothesis_Less" -> "menor", 
"MannWhitneyTest_AlternativeHypothesis_Unequal" -> "desigual", 
"MannWhitneyTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"MannWhitneyTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"MardiaCombinedTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"MardiaKurtosisTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"MardiaKurtosisTest_Method_MonteCarlo" -> "metodo de Montecarlo", 
"MardiaSkewnessTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"MardiaSkewnessTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"MatrixFunction_Method_Jordan" -> "m\[EAcute]todo de descomposici\[OAcute]n de Jordan", 
"MatrixFunction_Method_Schur" -> "descomposici\[OAcute]n de Schur con recursividad de bloque de Parlett", 
"MatrixLog_Method_Jordan" -> "m\[EAcute]todo de descomposici\[OAcute]n de Jordan", 
"MatrixLog_Method_Schur" -> "descomposici\[OAcute]n de Schur de matrices num\[EAcute]ricas inexactas", 
"MaxDetect_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"MeanGraphDistance_Method_UnitWeight" -> "peso espec\[IAcute]fico", 
"MoonPosition_CelestialSystem_Equatorial" -> "devuelve los resultados como un par de valores correctos de ascensi\[OAcute]n/declinaci\[OAcute]n", 
"MoonPosition_CelestialSystem_Horizon" -> "devuelve los resultados como un par de valores de altitud/acimut", 
"MorphologicalComponents_Method_BoundingBox" -> "encuentra cajas delimitadoras que no se superponen", 
"MorphologicalComponents_Method_BoundingDisk" -> "encuentra discos delimitadores que no se superponen", 
"MorphologicalComponents_Method_Convex" -> "etiqueta objetos dentro de las regiones convexas que no se superponen", 
"MorphologicalComponents_Method_ConvexHull" -> "encuentra cascos convexos que no se superponen", 
"MorphologicalComponents_Method_Nested" -> "etiqueta componentes conectados anidados", 
"NDSolve_Method_Adams" -> "m\[EAcute]todo de Adams", 
"NDSolve_Method_BDF" -> "f\[OAcute]rmula de diferenciaci\[OAcute]n de retroceso", 
"NDSolve_Method_ExplicitRungeKutta" -> "m\[EAcute]todo expl\[IAcute]cito de Runge-Kutta", 
"NDSolveValue_Method_Adams" -> "m\[EAcute]todo de Adams", 
"NDSolveValue_Method_BDF" -> "f\[OAcute]rmula de diferenciaci\[OAcute]n de retroceso", 
"NDSolveValue_Method_ExplicitRungeKutta" -> "m\[EAcute]todo expl\[IAcute]cito de Runge-Kutta", 
"NDSolveValue_Method_ImplicitRungeKutta" -> "m\[EAcute]todo impl\[IAcute]cito de Runge-Kutta", 
"NDSolveValue_Method_SymplecticPartitionedRungeKutta" -> "m\[EAcute]todo de particiones simpl\[EAcute]citas de Runge-Kutta", 
"NeedlemanWunschSimilarity_SimilarityRules_BLAST" -> "alineaci\[OAcute]n de secuencias de nucle\[OAcute]tidos", 
"NeedlemanWunschSimilarity_SimilarityRules_BLOSUM62" -> "alineamiento local de secuencias de amino\[AAcute]cidos relacionados", 
"NeedlemanWunschSimilarity_SimilarityRules_BLOSUM80" -> "alineamiento local de secuencias similares", 
"NeedlemanWunschSimilarity_SimilarityRules_PAM30" -> "alineamiento global de secuencias de amino\[AAcute]cidos muy similares", 
"NeedlemanWunschSimilarity_SimilarityRules_PAM70" -> "alineamiento global de secuencias relacionadas", 
"NExpectation_Method_MonteCarlo" -> "integraci\[OAcute]n de Montecarlo", 
"NIntegrate_Method_AdaptiveMonteCarlo" -> "integraci\[OAcute]n adaptable de Montecarlo", 
"NIntegrate_Method_AdaptiveQuasiMonteCarlo" -> "quasi integraci\[OAcute]n adaptable de ontecarlo", 
"NIntegrate_Method_CartesianRule" -> "producto multidimensional de reglas cartesianas", 
"NIntegrate_Method_ClenshawCurtisRule" -> "regla Clenshaw-Curtis", 
"NIntegrate_Method_DoubleExponential" -> "doble cuadratura exponencial", 
"NIntegrate_Method_DoubleExponentialOscillatory" -> "doble cuadratura exponencial oscilatoria", 
"NIntegrate_Method_ExtrapolatingOscillatory" -> "extrapolaci\[OAcute]n oscilatoria", 
"NIntegrate_Method_GaussBerntsenEspelidRule" -> "regla Gauss-Berntsen-Espelid", 
"NIntegrate_Method_GaussKronrodRule" -> "puntos de Gauss con extensi\[OAcute]n de Kronrod", 
"NIntegrate_Method_GlobalAdaptive" -> "subdivisi\[OAcute]n basada en estimaciones de error globales", 
"NIntegrate_Method_LevinRule" -> "reglas oscilatorias de tipo Levin", 
"NIntegrate_Method_LobattoKronrodRule" -> "puntos de Gauss-Lobatto con extensi\[OAcute]n de Kronrod", 
"NIntegrate_Method_LocalAdaptive" -> "subdivisi\[OAcute]n basada \[UAcute]nicamente en estimaciones de error locales", 
"NIntegrate_Method_MonteCarlo" -> "integraci\[OAcute]n de Montecarlo", 
"NIntegrate_Method_MonteCarloRule" -> "regla de integraci\[OAcute]n de Montecarlo", 
"NIntegrate_Method_MultidimensionalRule" -> "regla sim\[EAcute]trica multidimensional", 
"NIntegrate_Method_MultipanelRule" -> "combinaci\[OAcute]n de reglas 1D", 
"NIntegrate_Method_MultiPeriodic" -> "multiper\[IAcute]odica", 
"NIntegrate_Method_NewtonCotesRule" -> "regla de Newton-Cotes", 
"NIntegrate_Method_QuasiMonteCarlo" -> "quasi integraci\[OAcute]n de Montecarlo", 
"NIntegrate_Method_Trapezoidal" -> "puntos uniformes en una dimensi\[OAcute]n", 
"NIntegrate_Method_TrapezoidalRule" -> "regla de puntos uniformes en una dimensi\[OAcute]n", 
"NMaximize_Method_DifferentialEvolution" -> "evoluci\[OAcute]n diferencial", 
"NMaximize_Method_NelderMead" -> "m\[EAcute]todo de Nelder-Mead", 
"NMaximize_Method_RandomSearch" -> "b\[UAcute]squeda aleatoria",
"NMaximize_Method_SimulatedAnnealing" -> "recocido simulado", 
"NMinimize_Method_DifferentialEvolution" -> "evoluci\[OAcute]n diferencial", 
"NMinimize_Method_NelderMead" -> "m\[EAcute]todo de Nelder-Mead", 
"NMinimize_Method_RandomSearch" -> "b\[UAcute]squeda aleatoria",
"NMinimize_Method_SimulatedAnnealing" -> "recocido simulado", 
"NonlinearModelFit_Method_ConjugateGradient" -> "gradiente conjugada", 
"NonlinearModelFit_Method_Gradient" -> "gradiente", 
"NonlinearModelFit_Method_LevenbergMarquardt" -> "m\[EAcute]todo de Levenberg-Marquardt", 
"NonlinearModelFit_Method_Newton" -> "m\[EAcute]todo de Newton",
"Notebook_WindowFrameElements_CloseBox" -> "caja cerrada", 
"Notebook_WindowFrame_Frameless" -> "ventana com\[UAcute]n sin marco", 
"Notebook_WindowFrame_Generic" -> "ventana con borde gen\[EAcute]rico", 
"Notebook_WindowFrame_Normal" -> "ventana ordinaria", 
"Notebook_WindowFrame_Palette" -> "paleta", 
"Notebook_WindowFrame_ThinFrame" -> "ventana ordinaria con borde delgado", 
"NProbability_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"NProbability_Method_WynnEpsilon" -> "m\[EAcute]todo de extrapolaci\[OAcute]n de Wynn-Epsilon", 
"NProduct_Method_WynnEpsilon" -> "m\[EAcute]todo de extrapolaci\[OAcute]n de Wynn-Epsilon", 
"NSum_Method_AlternatingSigns" -> "m\[EAcute]todo para sumandos con signos alternantes", 
"NSum_Method_EulerMaclaurin" -> "m\[EAcute]todo de sumatoria Euler-Maclaurin", 
"NSum_Method_WynnEpsilon" -> "m\[EAcute]todo de extrapolaci\[OAcute]n de Wynn-Epsilon", 
"NyquistPlot_FeedbackType_Negative" -> "sistema con retroalimentaci\[OAcute]n negativa", 
"NyquistPlot_FeedbackType_Positive" -> "sistema con retroalimentaci\[OAcute]n positiva", 
"ObservableModelQ_Method_Gramian" -> "prueba si la capacidad de control de Gramian es positiva definida",
"ObservableModelQ_Method_Matrix" -> "prueba si la matriz de capacidad de control tiene rango completo", 
"ObservableModelQ_Method_PBH" -> "prueba de rangos Popov\[Dash]Belevitch\[Dash]Hautus", 
"Orthogonalize_Method_GramSchmidt" -> "m\[EAcute]todo de Gram-Schmidt", 
"Orthogonalize_Method_Householder" -> "m\[EAcute]todo de Householder", 
"Orthogonalize_Method_ModifiedGramSchmidt" -> "m\[EAcute]todo de Gram-Schmidt modificado", 
"Orthogonalize_Method_Reorthogonalization" -> "reortogonalizaci\[OAcute]n", 
"PairedBarChart_ChartElementFunction_ArrowRectangle" -> "flecha rectangular", 
"PairedBarChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"PairedBarChart_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"PairedBarChart_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo oblicuo", 
"PairedHistogram_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"PairedHistogram_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"PairedHistogram_ChartElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo gradiente", 
"PairedHistogram_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo gradiente", 
"PairedHistogram_ChartElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"PairedTTest_AlternativeHypothesis_Greater" -> "mayor", 
"PairedTTest_AlternativeHypothesis_Less" -> "menor", 
"PairedTTest_AlternativeHypothesis_Unequal" -> "desigual", 
"PairedTTest_VerifyTestAssumptions_" -> "verifica que todos los datos se distribuyen normalmente", 
"PairedTTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"PairedZTest_VerifyTestAssumptions_" -> "verifica que todos los datos se distribuyen normalmente", 
"PairedZTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"Pane_ImageSizeAction_Clip" -> "verifica que todos los datos se distribuyen normalmente", 
"Pane_ImageSizeAction_ResizeToFit" -> "cambia el tama\[NTilde]o para que los contenidos se ajusten exactamente a ImageSize", 
"Pane_ImageSizeAction_Scrollable" -> "hace que el contenido sea desplazable si es necesario", 
"Pane_ImageSizeAction_ShrinkToFit" -> "reduce el tama\[NTilde]o para que los contenidos calcen si es necesario", 
"Panel_Appearance_DialogBox" -> "caja de di\[AAcute]logo", 
"Panel_Appearance_Frameless" -> "sin marco", 
"Panel_Appearance_Palette" -> "paleta", 
"ParallelArray_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelArray_Method_EvaluationsPerKernel" -> "evaluaciones por k\[EAcute]rnel", 
"ParallelArray_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelArray_Method_ItemsPerEvaluation" -> "\[IAcute]tems por evaluaci\[OAcute]n", 
"ParallelCombine_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelCombine_Method_EvaluationsPerKernel" -> "evaluaciones por k\[EAcute]rnel", 
"ParallelCombine_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelCombine_Method_ItemsPerEvaluation" -> "\[IAcute]tems por evaluaci\[OAcute]n", 
"ParallelDo_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelDo_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"Parallelize_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"Parallelize_Method_EvaluationsPerKernel" -> "evaluaciones por k\[EAcute]rnel", 
"Parallelize_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"Parallelize_Method_ItemsPerEvaluation" -> "\[IAcute]tems por evaluaci\[OAcute]n", 
"ParallelMap_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelMap_Method_EvaluationsPerKernel" -> "evaluaciones por k\[EAcute]rnel", 
"ParallelMap_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelMap_Method_ItemsPerEvaluation" -> "\[IAcute]tems por evaluaci\[OAcute]n", 
"ParallelProduct_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelProduct_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelSum_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelSum_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelTable_Method_CoarsestGrained" -> "granulado m\[AAcute]s grueso", 
"ParallelTable_Method_EvaluationsPerKernel" -> "evaluaciones por k\[EAcute]rnel", 
"ParallelTable_Method_FinestGrained" -> "granulado m\[AAcute]s fino", 
"ParallelTable_Method_ItemsPerEvaluation" -> "\[IAcute]tems por evaluaci\[OAcute]n", 
"ParametricPlot3D_Lighting_Neutral" -> "neutral", 
"PasteButton_Appearance_FramedPalette" -> "paleta enmarcada", 
"PasteButton_Appearance_Pressed" -> "prensado", 
"PearsonChiSquareTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"PearsonCorrelationTest_AlternativeHypothesis_Greater" -> "mayor", "PearsonCorrelationTest_AlternativeHypothesis_Less" -> "menor", 
"PearsonCorrelationTest_AlternativeHypothesis_Unequal" -> "desigual", 
"PearsonCorrelationTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"PearsonCorrelationTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"PearsonCorrelationTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"Periodogram_ScalingFunctions_Absolute" -> "absoluto", 
"PIDTune_Method_CharacteristicArea" -> "utiliza la zona caracter\[IAcute]stica de la respuesta a escal\[OAcute]n", 
"PIDTune_Method_GainMargins" -> "utiliza la frecuencia de cruce de fase y margen de ganancia", 
"PIDTune_Method_InflectionPoint" -> "utiliza el punto de inflexi\[OAcute]n de la respuesta a escal\[OAcute]n", 
"PIDTune_Method_MethodOfMoments" -> "coincide momentos", 
"PIDTune_Method_TwoPointSampling" -> "utiliza los puntos al 28% y 63% de la respuesta a escal\[OAcute]n",
"PieChart3D_ChartElementFunction_CylindricalSector3D" -> "sector cil\[IAcute]ndrico en 3D", 
"PieChart3D_ChartElementFunction_ProfileSector3D" -> "perfil de sector en 3D", 
"PieChart3D_ChartElementFunction_TorusSector3D" -> "sector de toro en 3D", 
"PieChart_ChartElementFunction_GlassSector" -> "sector de vidrio", 
"PieChart_ChartElementFunction_PlateauSector" -> "sector de meseta", 
"PieChart_ChartElementFunction_Sector" -> "sector", 
"PieChart_LegendAppearance_Column" -> "columna", 
"PieChart_LegendAppearance_Row" -> "fila", 
"PillaiTraceTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"PillaiTraceTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"PillaiTraceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"Plot3D_Lighting_Neutral" -> "neutral", 
"Plot_PerformanceGoal_Quality" -> "calidad", 
"Plot_PerformanceGoal_Speed" -> "velocidad", 
"PointFigureChart_ChartElementFunction_ArrowRectangle" -> "flecha rectangular", 
"PointFigureChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"PointFigureChart_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo oblicuo", 
"PointFigureChart_ScalingFunctions_Log" -> "utilizar una escala logar\[IAcute]tmica", 
"PointFigureChart_TrendStyle_BlackWhite" -> "blanco y negro", 
"PointFigureChart_TrendStyle_RedGreen" -> "rojo y verde", 
"PointLegend_LegendFunction_Frame" -> "marco", 
"PointLegend_LegendFunction_Panel" -> "panel", 
"PointLegend_LegendLayout_Column" -> "columna", 
"PointLegend_LegendLayout_ReversedColumn" -> "columna revertida", 
"PointLegend_LegendLayout_ReversedRow" -> "fila revertida", 
"PointLegend_LegendLayout_Row" -> "fila", 
"PointLegend_LegendMarkers_\[FilledDiamond]" -> "\[FilledDiamond]", 
"PossibleZeroQ_Method_ExactAlgebraics" -> "algebraicos exactos",
"Predict_Method_LinearRegression" -> "predice a partir de combinaciones lineales de funciones", 
"Predict_Method_NearestNeighbors" -> "predice a partir de ejemplos de vecinos m\[AAcute]s cercanos", 
"Predict_Method_RandomForest" -> "predice a partir de los conjuntos de \[AAcute]rboles de decisi\[OAcute]n de Breiman-Cutler", 
"Predict_PerformanceGoal_Memory" -> "minimiza los requisitos de almacenamiento del predictor", 
"Predict_PerformanceGoal_Quality" -> "calidad", 
"Predict_PerformanceGoal_Speed" -> "velocidad", 
"Predict_PerformanceGoal_TrainingSpeed" -> "minimiza el tiempo de producci\[OAcute]n del predictor", 
"PrincipalComponents_Method_Correlation" -> "correlaci\[OAcute]n", 
"PrincipalComponents_Method_Covariance" -> "covarianza", 
"Probability_Method_CDF" -> "funci\[OAcute]n de distribuci\[OAcute]n", 
"Probability_Method_PDF" -> "funci\[OAcute]n de densidad de probabilidad", 
"Probability_Method_Quantile" -> "de porcentaje", 
"Product_Regularization_Dirichlet" -> "distribuci\[OAcute]n de Dirichlet", 
"RadioButtonBar_Appearance_Horizontal" -> "horizontal", 
"RadioButtonBar_Appearance_Row" -> "fila", 
"RadioButtonBar_Appearance_Vertical" -> "vertical", 
"Radon_Method_Hough" -> "transformada de Hough", 
"Radon_Method_Radon" -> "transformada de Randon", 
"RandomImage_ColorSpace_CMYK" -> "cian, magenta, amarillo, negro", 
"RandomImage_ColorSpace_HSB" -> "tono, saturaci\[OAcute]n, brillo", 
"RandomImage_ColorSpace_RGB" -> "rojo, verde, azul", 
"RectangleChart3D_ChartElementFunction_Cone" -> "cono", 
"RectangleChart3D_ChartElementFunction_Cube" -> "cubo", 
"RectangleChart3D_ChartElementFunction_Cylinder" -> "cilindro", 
"RectangleChart3D_ChartElementFunction_FadingCube" -> "cubo que desvanece", 
"RectangleChart3D_ChartElementFunction_ProfileCube" -> "perfil de cubo", 
"RectangleChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"RectangleChart_ChartElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"RectangleChart_ChartElementFunction_GradientRectangle" -> "rect\[AAcute]ngulo gradiente", 
"RectangleChart_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo oblicuo", 
"RectangleChart_ChartElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"ReliefPlot_Method_AspectBasedShading" -> "sombreado basado en orientaci\[OAcute]n", 
"ReliefPlot_Method_DiffuseReflection" -> "reflexi\[OAcute]n difusa", 
"ReliefPlot_PerformanceGoal_Quality" -> "optimiza la calidad de los resultados finales", 
"ReliefPlot_PerformanceGoal_Speed" -> "velocidad", 
"RenkoChart_ChartElementFunction_ArrowRectangle" -> "flecha rectangular", 
"RenkoChart_ChartElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"RenkoChart_ChartElementFunction_ObliqueRectangle" -> "rect\[AAcute]ngulo oblicuo", 
"RenkoChart_ScalingFunctions_Log" -> "utilizar una escala logar\[IAcute]tmica", 
"RenkoChart_TrendStyle_BlackWhite" -> "blanco y negro", 
"RenkoChart_TrendStyle_RedGreen" -> "rojo y verde", 
"Resultant_Method_BezoutMatrix" -> "matriz de Bezout", 
"Resultant_Method_SylvesterMatrix" -> "matriz de Sylvester", 
"RiccatiSolve_Method_Eigensystem" -> "m\[EAcute]todo basado en la descomposici\[OAcute]n de Eigen", 
"RiccatiSolve_Method_Schur" -> "m\[EAcute]todo basado en la descomposici\[OAcute]n de Schur", 
"RootLocusPlot_FeedbackType_Negative" -> "sistema con retroalimentaci\[OAcute]n negativa", 
"RootLocusPlot_FeedbackType_Positive" -> "sistema con retroalimentaci\[OAcute]n positiva", 
"RootLocusPlot_Method_GenericSolve" -> "soluci\[OAcute]n gen\[EAcute]rica", 
"RootLocusPlot_Method_NDSolve" -> "encuentra una soluci\[OAcute]n num\[EAcute]rica a ecuaciones diferenciales ordinarias", 
"RootReduce_Method_NumberField" -> "campo de n\[UAcute]mero", 
"RootReduce_Method_Recursive" -> "recursivo", 
"SectorChart3D_ChartElementFunction_CylindricalSector3D" -> "sector cil\[IAcute]ndrico en 3D", 
"SectorChart3D_ChartElementFunction_ProfileSector3D" -> "sector de perfil en 3D", 
"SectorChart3D_ChartElementFunction_TorusSector3D" -> "sector de toro en 3D", 
"SectorChart_ChartElementFunction_BezelSector" -> "sector de basil", 
"SectorChart_ChartElementFunction_PlateauSector" -> "sector de meseta", 
"SectorChart_ChartElementFunction_Sector" -> "sector", 
"SectorChart_ChartElementFunction_SquareWaveSector" -> "sector de ondas de cuadrado", 
"SectorChart_ChartElementFunction_TriangleWaveSector" -> "sector de ondas de tri\[AAcute]ngulo", 
"SeedRandom_Method_MersenneTwister" -> "generador de n\[UAcute]meros Mersenne Twister", 
"SequenceAlignment_Method_Local" -> "local", 
"SequenceAlignment_SimilarityRules_BLAST" -> "alineaci\[OAcute]n de secuencias de nucle\[OAcute]tidos", 
"SequenceAlignment_SimilarityRules_BLOSUM62" -> "alineamiento local de secuencias de amino\[AAcute]cidos relacionados", 
"SequenceAlignment_SimilarityRules_BLOSUM80" -> "alineamiento local de secuencias similares", 
"SequenceAlignment_SimilarityRules_PAM30" -> "alineamiento global de secuencias de amino\[AAcute]cidos muy similares", 
"SequenceAlignment_SimilarityRules_PAM70" -> "alineamiento global de secuencias relacionadas", 
"SeriesCoefficient_Method_Holonomic" -> "hol\[OAcute]nico", 
"Setter_Appearance_AbuttingLeftRight" -> "colindante inquierda-derecha", 
"Setter_Appearance_Frameless" -> "sin marco", 
"Setter_Appearance_Palette" -> "paleta", 
"SetterBar_Appearance_Horizontal" -> "horizontal", 
"SetterBar_Appearance_Row" -> "fila", 
"SetterBar_Appearance_Vertical" -> "vertical", 
"ShapiroWilkTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"SiegelTukeyTest_AlternativeHypothesis_Greater" -> "mayor", 
"SiegelTukeyTest_AlternativeHypothesis_Less" -> "menor", 
"SiegelTukeyTest_AlternativeHypothesis_Unequal" -> "desigual", 
"SiegelTukeyTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"SiegelTukeyTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"SignedRankTest_AlternativeHypothesis_Greater" -> "mayor", 
"SignedRankTest_AlternativeHypothesis_Less" -> "menor", 
"SignedRankTest_AlternativeHypothesis_Unequal" -> "desigual", 
"SignedRankTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"SignedRankTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"SignedRankTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"SignedRankTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"SignTest_AlternativeHypothesis_Greater" -> "mayor", 
"SignTest_AlternativeHypothesis_Less" -> "menor", 
"SignTest_AlternativeHypothesis_Unequal" -> "desigual", 
"SignTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"SignTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"Slider_Appearance_Labeled" -> "etiquetado", 
"SolarEclipse_EclipseType_Annular" -> "devuelve el pr\[OAcute]ximo eclipse anular", 
"SolarEclipse_EclipseType_Hybrid" -> "devuelve el pr\[OAcute]ximo eclipse h\[IAcute]brido", 
"SolarEclipse_EclipseType_Partial" -> "devuelve el siguiente eclipse parcial", 
"SolarEclipse_EclipseType_Total" -> "devuelve el siguiente eclipse total", 
"SpearmanRankTest_AlternativeHypothesis_Greater" -> "mayor", 
"SpearmanRankTest_AlternativeHypothesis_Less" -> "menor", 
"SpearmanRankTest_AlternativeHypothesis_Unequal" -> "desigual", 
"SpearmanRankTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"SpearmanRankTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"StandardAtmosphereData_Method_InternationalStandardAtmosphere" -> "modelo de atm\[OAcute]sfera est\[AAcute]ndar internacional de 1964", "StandardAtmosphereData_Method_Jacchia" -> "modelo de atm\[OAcute]sfera de temperatura exosf\[EAcute]rica a 1000 K de Jacchia de 1977", 
"StandardAtmosphereData_Method_USStandardAtmosphere" -> "modelo estadounidense de atm\[OAcute]sfera est\[AAcute]ndar de 1976", "StateFeedbackGains_Method_Ackermann" -> "m\[EAcute]todo de Ackerman", 
"StateFeedbackGains_Method_KNVD" -> "m\[EAcute]todo de Kautsky\[Dash]Nichols\[Dash]Van Dooren", 
"StateOutputEstimator_Method_CurrentEstimator" -> "construye el estimador actual", 
"StateOutputEstimator_Method_PredictionEstimator" -> "construye el estimador de predicci\[OAcute]n", 
"StateSpaceModel_StateSpaceRealization_ControllableCompanion" -> "realizaci\[OAcute]n de compa\[NTilde]ero controlable", 
"StateSpaceModel_StateSpaceRealization_ObservableCompanion" -> "realizaci\[OAcute]n de compa\[NTilde]ero observable", 
"Style_ControlsRendering_Generic" -> "utiliza aspectos de control gen\[EAcute]ricos", 
"Style_FontTracking_Condensed" -> "condensado", 
"Style_FontTracking_Narrow" -> "angosto", 
"Style_FontTracking_SemiCondensed" -> "semicondensado", 
"SumConvergence_Method_IntegralTest" -> "prueba de integrales", 
"SumConvergence_Method_RaabeTest" -> "prueba de Raabe", 
"SumConvergence_Method_RatioTest" -> "prueba de relaci\[OAcute]n de D'Alembert", 
"SumConvergence_Method_RootTest" -> "prueba de ra\[IAcute]z de Cauchy", 
"Sum_Method_Logarithmic" -> "suma de serie logar\[IAcute]tmica",
"Sum_Method_Polynomial" -> "suma de polinomios", 
"Sum_Method_Procedural" -> "calcula la suma procesalmente", 
"Sum_Method_RationalFunction" -> "suma de funciones racionales",
"Sum_Method_TableLookup" -> "suma basada en la tabla de consulta", 
"Sum_Regularization_Abel" -> "sumaci\[OAcute]n de Abel", 
"Sum_Regularization_Borel" -> "sumaci\[OAcute]n de Borel", 
"Sum_Regularization_Cesaro" -> "sumaci\[OAcute]n de Cesaro", 
"Sum_Regularization_Dirichlet" -> "sumaci\[OAcute]n de Dirichlet", 
"Sum_Regularization_Euler" -> "sumaci\[OAcute]n de Euler", 
"SunPosition_CelestialSystem_Equatorial" -> "devuelve los resultados como un par de valores correctos de ascensi\[OAcute]n/declinaci\[OAcute]n", 
"SunPosition_CelestialSystem_Horizon" -> "devuelve los resultados como un par de valores de altitud/acimut", 
"SurvivalDistribution_Method_KaplanMeier" -> "estimador Kaplan-Meier de l\[IAcute]mite de producto para datos correctamente censurados", 
"SurvivalDistribution_Method_NelsonAalen" -> "basado en el estimador de impacto acumulado de Nelson-Aalen", 
"SurvivalDistribution_Method_Noncensored" -> "ignora censura y se utilizan puntos medios de intervalo", 
"SurvivalDistribution_Method_SelfConsistency" -> "\[Placeholder]", 
"SurvivalDistribution_Method_Turnbull" -> "algoritmo de Turnbull para datos censurados por intervalos", 
"SurvivalModelFit_Method_KaplanMeier" -> "estimador Kaplan-Meier de l\[IAcute]mite de producto para datos correctamente censurados", 
"SurvivalModelFit_Method_NelsonAalen" -> "basado en el estimador de impacto acumulado de Nelson-Aalen", 
"SurvivalModelFit_Method_Noncensored" -> "ignora censura y se utilizan puntos medios de intervalo", 
"SurvivalModelFit_Method_SelfConsistency" -> "algoritmo de Turnbull para los datos doblemente censurados", 
"SurvivalModelFit_Method_Turnbull" -> "algoritmo de Turnbull para datos censurados por intervalos", 
"SwatchLegend_LegendFunction_Frame" -> "marco", 
"SwatchLegend_LegendFunction_Panel" -> "panel", 
"SwatchLegend_LegendLayout_Column" -> "columna", 
"SwatchLegend_LegendLayout_ReversedColumn" -> "columna revertida", 
"SwatchLegend_LegendLayout_ReversedRow" -> "fila revertida", 
"SwatchLegend_LegendLayout_Row" -> "fila", 
"SwatchLegend_LegendMarkers_Bubble" -> "burbuja", 
"SwatchLegend_LegendMarkers_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"SwatchLegend_LegendMarkers_Square" -> "cuadrado", 
"TextCell_CellDingbat_+++++" -> "+++++", 
"TextCell_CellDingbat_\[SmallCircle]" -> "\[SmallCircle]", 
"TextCell_CellLabel_Example" -> "ejemplo", 
"TextCell_CellTags_tag" -> "etiqueta", 
"ThermometerGauge_GaugeFaceElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"ThermometerGauge_GaugeFaceElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"ThermometerGauge_GaugeFaceElementFunction_SegmentScaleRectangle" -> "rect\[AAcute]ngulo de escala de segmento", 
"ThermometerGauge_GaugeFrameElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"ThermometerGauge_GaugeFrameElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"ThermometerGauge_GaugeFrameElementFunction_SegmentScaleRectangle" -> "rect\[AAcute]ngulo de escala de segmento", 
"Thinning_Method_MedialAxis" -> "eje medial aproximado", 
"Thinning_Method_Morphological" -> "adelgazamiento morfol\[OAcute]gico (predeterminado)", 
"Thinning_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"Thumbnail_Padding_Fixed" -> "repeticiones de elementos en cada l\[IAcute]mite", 
"TimeSeriesForecast_Method_AR" -> "aproximado con un proceso AR de gran pedido", 
"TimeSeriesForecast_Method_Covariance" -> "covarianza exacta basada en funciones", 
"TimeSeriesForecast_Method_Kalman" -> "utiliza el filtro de Kalman", 
"ToContinuousTimeModel_Method_BackwardRectangularRule" -> "m\[EAcute]todo inverso de Euler", 
"ToContinuousTimeModel_Method_BilinearTransform" -> "aproximaci\[OAcute]n lineal de Tustin", 
"ToContinuousTimeModel_Method_FirstOrderHold" -> "aproximaci\[OAcute]n lineal (triangular )por tramos", 
"ToContinuousTimeModel_Method_ForwardRectangularRule" -> "m\[EAcute]todo hacia adelante de Euler", 
"ToContinuousTimeModel_Method_ZeroPoleMapping" -> "concordancia exacta de ceros y polos", 
"ToDiscreteTimeModel_Method_BackwardRectangularRule" -> "m\[EAcute]todo inverso de Euler", 
"ToDiscreteTimeModel_Method_ForwardRectangularRule" -> "m\[EAcute]todo hacia adelante de Euler", 
"ToDiscreteTimeModel_Method_ZeroOrderHold" -> "aproximaci\[OAcute]n constante por tramos", 
"TogglerBar_Appearance_Horizontal" -> "equidistantes horizontalmente", 
"TogglerBar_Appearance_Row" -> "dispuestos como texto, lo que permite el ajuste de l\[IAcute]nea", 
"TogglerBar_Appearance_Vertical" -> "equidistantes verticalmente", 
"Tooltip_DefaultTooltipStyle_TooltipLabel" -> "etiqueta de informaci\[OAcute]n de herramientas", 
"ToString_CharacterEncoding_ASCII" -> "sistema de codificaci\[OAcute]n de caracteres alfanum\[EAcute]ricos ", 
"ToString_CharacterEncoding_Symbol" -> "s\[IAcute]mbolo", 
"TotalVariationFilter_Method_Gaussian" -> "m\[EAcute]todo de Gauss", 
"TotalVariationFilter_Method_Laplacian" -> "m\[EAcute]todo de Laplace", 
"TotalVariationFilter_Method_Poisson" -> "m\[EAcute]todo de Poisson", 
"TradingChart_Appearance_Candlestick" -> "candelero", 
"TradingChart_Appearance_Line" -> "l\[IAcute]nea", 
"TradingChart_Appearance_OHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado", 
"TradingChart_ChartElementFunction_ArrowCandlestick" -> "flecha tipo candelero", 
"TradingChart_ChartElementFunction_Candlestick" -> "candelero", 
"TradingChart_ChartElementFunction_FadingOHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado que desvanece", 
"TradingChart_ChartElementFunction_OHLC" -> "gr\[AAcute]fico abierto-alto-bajo-cerrado", 
"TreePlot_PackingMethod_ClosestPackingCenter" -> "embalaje aproximado m\[AAcute]s cercano desde el centro", 
"TreePlot_PackingMethod_LayeredTop" -> "organiza en capas empezando desde la parte superior", 
"TreePlot_PackingMethod_NestedGrid" -> "organizado en una parrilla anidada", 
"TTest_AlternativeHypothesis_Greater" -> "mayor", 
"TTest_AlternativeHypothesis_Less" -> "menor", 
"TTest_AlternativeHypothesis_Unequal" -> "desigual", 
"TTest_VerifyTestAssumptions_EqualVariance" -> "igual varianza",
"TTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"URLFetch_Method_HEAD" -> "cabecera", 
"URLFetch_UserAgent_Web Browser" -> "navegador web", 
"URLSave_Method_HEAD" -> "cabecera", 
"URLSave_UserAgent_Web Browser" -> "navegador web", 
"VarianceEquivalenceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"VarianceEquivalenceTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"VarianceTest_AlternativeHypothesis_Greater" -> "mayor", 
"VarianceTest_AlternativeHypothesis_Less" -> "menor", 
"VarianceTest_AlternativeHypothesis_Unequal" -> "desigual", 
"VarianceTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"VarianceTest_VerifyTestAssumptions_Symmetry" -> "simetr\[IAcute]a", 
"VerticalGauge_GaugeFaceElementFunction_ArrowRectangle" -> "flecha rectangular", 
"VerticalGauge_GaugeFaceElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"VerticalGauge_GaugeFaceElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"VerticalGauge_GaugeFaceElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"VerticalGauge_GaugeFaceElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"VerticalGauge_GaugeFrameElementFunction_ArrowRectangle" -> "flecha rectangular", 
"VerticalGauge_GaugeFrameElementFunction_FadingRectangle" -> "rect\[AAcute]ngulo que desvanece", 
"VerticalGauge_GaugeFrameElementFunction_GlassRectangle" -> "rect\[AAcute]ngulo de vidrio", 
"VerticalGauge_GaugeFrameElementFunction_GradientScaleRectangle" -> "rect\[AAcute]ngulo de escala gradiente", 
"VerticalGauge_GaugeFrameElementFunction_Rectangle" -> "rect\[AAcute]ngulo", 
"VerticalSlider_Appearance_LeftArrow" -> "flecha izquierda", 
"VerticalSlider_Appearance_RightArrow" -> "flecha derecha", 
"WatershedComponents_Method_Basins" -> "algoritmo de cuenca modificado (Beucher, Meyer)", 
"WatershedComponents_Method_Immersion" -> "algoritmo de inmersi\[OAcute]n de cuenca (Vincent-Soille)", 
"WatershedComponents_Method_Rainfall" -> "gradiente de descenso o algoritmo de precipitaciones (Osma-Ruiz)", 
"WatsonUSquareTest_Method_MonteCarlo" -> "m\[EAcute]todo de Montecarlo", 
"WaveletImagePlot_Method_InverseTransform" -> "transformada inversa", 
"WaveletImagePlot_PlotLayout_Grid" -> "parrilla", 
"WaveletImagePlot_PlotLayout_Pyramid" -> "pir\[AAcute]mide", 
"WaveletListPlot_Method_InverseTransform" -> "transformada inversa", 
"WaveletListPlot_PlotLayout_CommonXAxis" -> "eje com\[UAcute]n x", 
"WaveletListPlot_PlotLayout_CommonYAxis" -> "eje com\[UAcute]n y", 
"WaveletMatrixPlot_Method_InverseTransform" -> "transformada inversa", 
"WhenEvent_DetectionMethod_DerivativeSign" -> "usa cambio de signo y derivada de tiempo", 
"WhenEvent_DetectionMethod_Interpolation" -> "usa la interpolaci\[OAcute]n de salida de soluci\[OAcute]n densa", 
"WhenEvent_DetectionMethod_Sign" -> "usa un cambio de signo", 
"WhenEvent_LocationMethod_LinearInterpolation" -> "interpola linealmente en un paso", 
"WhenEvent_LocationMethod_StepBegin" -> "localiza el evento al comienzo de una etapa", 
"WhenEvent_LocationMethod_StepEnd" -> "localiza el evento al final de una etapa", 
"WilksWTest_Method_Asymptotic" -> "asint\[OAcute]tica", 
"WilksWTest_Method_Permutation" -> "permutaci\[OAcute]n", 
"WilksWTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"WindDirectionData_UnitSystem_Imperial" -> "imperial", 
"WindDirectionData_UnitSystem_Metric" -> "m\[EAcute]trico", 
"WindSpeedData_UnitSystem_Imperial" -> "imperial", 
"WindSpeedData_UnitSystem_Metric" -> "m\[EAcute]trico", 
"WindVectorData_UnitSystem_Imperial" -> "imperial", 
"WindVectorData_UnitSystem_Metric" -> "m\[EAcute]trico", 
"ZTest_AlternativeHypothesis_Greater" -> "mayor", 
"ZTest_AlternativeHypothesis_Less" -> "menor", 
"ZTest_AlternativeHypothesis_Unequal" -> "desigual", 
"ZTest_VerifyTestAssumptions_Normality" -> "verifica que todos los datos se distribuyen normalmente", 
"ZTransform_Method_Holonomic" -> "hol\[OAcute]nico"
}