(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



{
"TITLE"->"\:d65c\:b3d9App",
"ACTIONS-NAME"->"\:d65c\:b3d9",
"STOP-NAME"->"\:c815\:c9c0",
"STOP-TOOLTIP"->"\:c815\:c9c0 \:c0c1\:d0dc\:c5d0 \:c2a4\:c704\:ce58",
"STOP-MESSAGE"->"\:bd80\:b974\:b294 \:c815\:c9c0\n",
"START-NAME"->"\:c2dc\:c791",
"START-TOOLTIP"->"\:c2e4\:d589 \:c0c1\:d0dc\:c5d0 \:c2a4\:c704\:ce58",
"START-MESSAGE"->"\:bd80\:b974\:b294 \:c2dc\:c791\n",
"FORWARD-NAME"->"\:c55e\:c73c\:b85c",
"FORWARD-TOOLTIP"->"\:c6c0\:c9c1\:c784\:c740 1\:ac1c \:b2e8\:acc4\:b97c \:bc1c\:c1a1\:d55c\:b2e4","FORWARD-MESSAGE"->"\:bd80\:b974\:b294 \:bc1c\:c1a1\:d558\:c2ed\ \:c2dc\:c694\n",
"BACK-NAME"->"\:b4a4",
"BACK-TOOLTIP"->"\:d6c4\:c5d0\:c758 \:c6c0\:c9c1\:c784 1\:ac1c \:b2e8\:acc4",
"BACK-MESSAGE"->"\:bd80\:b974\:b294 \:b4a4\n",
"CLEAR-NAME"->"\:acf5\:ac04",
"CLEAR-TOOLTIP"->"\:ba85\:d655\:d55c \:d1b5\:c2e0 \:ad6c\:c5ed"
}
