(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



{
"TITLE"->"\:0414\:0435\:0439\:0441\:0442\:0432\:0438\:0435App",
"ACTIONS-NAME"->"\:0414\:0435\:0439\:0441\:0442\:0432\:0438\:044f",
"STOP-NAME"->"\:0421\:0442\:043e\:043f",
"STOP-TOOLTIP"->"\:041f\:0435\:0440\:0435\:043a\:043b\:044e\:0447\:0438\:0442\:0435 \:043a \:043e\:0441\:0442\:0430\:043d\:043e\:0432\:043b\:0435\:043d\:043d\:043e\:043c\:0443 \:043f\:043e\:043b\:043e\:0436\:0435\:043d\:0438\:044e",
"STOP-MESSAGE"->"\:0412\:044b\:0437\:0432\:0430\:043d\:043d\:044b\:0439 \:0441\:0442\:043e\:043f...\n",
"START-NAME"->"\:0421\:0442\:0430\:0440\:0442",
"START-TOOLTIP"->"\:041f\:0435\:0440\:0435\:043a\:043b\:044e\:0447\:0438\:0442\:0435 \:043a \:0438\:0434\:0443\:0449\:0435\:043c\:0443 \:043f\:043e\:043b\:043e\:0436\:0435\:043d\:0438\:044e",
"START-MESSAGE"->"\:0412\:044b\:0437\:0432\:0430\:043d\:043d\:044b\:0439 \:0441\:0442\:0430\:0440\:0442...\n",
"FORWARD-NAME"->"\:041f\:0435\:0440\:0435\:0434\:043d\:0435",
"FORWARD-TOOLTIP"->"\:0414\:0432\:0438\:043d\:044c\:0442\:0435 \:0432\:043f\:0435\:0440\:0435\:0434 \:043e\:0434\:0438\:043d \:0448\:0430\:0433",
"FORWARD-MESSAGE"->"\:041f\:0440\:0435\:043f\:0440\:043e\:0432\:043e\:0436\:0434\:0430\:0439\:0442\:0435 \:0432\:044b\:0437\:0432\:0430\:043d\:043e...\n",
"BACK-NAME"->"\:0417\:0430\:0434\:043d\:044f\:044f \:0447\:0430\:0441\:0442\:044c",
"BACK-TOOLTIP"->"\:0414\:0432\:0438\:043d\:044c\:0442\:0435 \:043d\:0430\:0437\:0430\:0434 \:043e\:0434\:0438\:043d \:0448\:0430\:0433",
"BACK-MESSAGE"->"\:0412\:044b\:0437\:0432\:0430\:043d\:043d\:0430\:044f \:0437\:0430\:0434\:043d\:044f\:044f \:0447\:0430\:0441\:0442\:044c...\n",
"CLEAR-NAME"->"\:042f\:0441\:043d\:043e\:0441\:0442\:044c",
"CLEAR-TOOLTIP"->"\:0417\:043e\:043d\:0430 \:044f\:0441\:043d\:043e \:0432\:044b\:0440\:0430\:0436\:0435\:043d\:043d\:043e\:0435 \:043f\:043e\:0441\:043b\:0430\:043d\:0438\:0435"
}
