{"I", "Sqrt", "E", "Pi", "Exp", "Log", "Sin", "Abs", "Cos", "Re", "Im", 
 "Subscript", "ArcTan", "ArcSin", "Tan", "D", "Quantity", "Conjugate", 
 "Sinh", "Derivative", "Integrate", "Cosh", "Cot", "None", "ArcTanh", 
 "BesselI", "Arg", "Tanh", "Rational", "Csc", "Sec", "Infinity", "ArcCos", 
 "FresnelC", "FourierSeries", "HeavisideTheta", "Sinc", "Hypergeometric2F1", 
 "Degree", "BaseForm", "Norm", "ComplexExpand", "Floor", "Sum", "Gamma", 
 "BesselJ", "Together", "Sech", "Plus", "Product", "Log2", "Coth", "ArcCoth", 
 "ArcCosh", "PrimePi", "Limit", "EulerGamma", "ArcSinh", "Sign", 
 "InverseLaplaceTransform", "Eigenvectors", "Zeta", "Residue", "Max", 
 "LucasL", "Inverse", "EllipticPi", "ArcSech", "ArcCot", "ZetaZero", 
 "Transpose", "RowReduce", "RotationMatrix", "NestList", "MatrixPower", 
 "FourierTransform", "UnitStep", "PrimeOmega", "PlusMinus", "MatrixExp", 
 "LogicalExpand", "Log10", "LaplaceTransform", "HypergeometricU", 
 "ExpToTrig", "Erfi", "EllipticE", "DSolve", "Csch", "Catalan", "Beta", 
 "Apart", "UnitBox", "TrigToExp", "TargetFunctions", "SinIntegral", 
 "SeriesCoefficient", "Ratios", "Range", "ProductLog", "Prime", 
 "ModularLambda", "Mod", "LogIntegral", "InverseFourierTransform", 
 "IdentityMatrix", "Grad", "GoldenRatio", "Function", "FullSimplify", 
 "FresnelS", "ExpIntegralEi", "EulerE", "Equivalent", "EllipticTheta", 
 "Eigenvalues", "DiracDelta", "Ceiling", "ArcSec"}
