{"Pi", "ArcSin", "Degree", "ArcTan", "Sqrt", "Cos", "Sin", "ArcCos", "Log", 
 "E", "Tan", "I", "Abs", "Quantity", "Sec", "ArcCot", "ArcSec", "None", 
 "PrimePi", "Exp", "Derivative", "Cot", "Plus", "ArcCsc", "Rational", 
 "Infinity", "InverseFunction", "Csc", "D", "Sinh", "Subscript", "Floor", 
 "Inverse", "HeavisideTheta", "ArcSinh", "Cosh", "Root", "EllipticPi", 
 "Integrate", "Tanh", "Beta", "Arg", "GoldenRatio", "Mod", "VectorAngle", 
 "ArcCosh", "Gamma", "BaseForm", "Log10", "Sign", "Quotient", "Range", 
 "Limit", "ArcTanh", "Conjugate", "Sum", "JacobiSN", "Sech", 
 "FourierTransform", "Zeta", "ArcCoth", "N", "PlusMinus", "IntegerPart", 
 "EulerGamma", "Max", "Log2", "Ratios", "EllipticTheta", "EulerPhi", "Erf", 
 "Norm", "Re", "Expand", "Round", "Sinc", "RandomReal", "UnitBox", "BesselI", 
 "Automatic", "Prime", "Identity", "Coth", "FractionalPart", "Im", 
 "DiracDelta", "Interval", "EulerE", "Ceiling", "Cross", "HoldPattern", 
 "ProductLog", "PrimeNu", "EvenQ", "UnitStep", "TriangleWave", 
 "Subfactorial", "Exponent", "AiryAi", "ExpIntegralEi", "SinIntegral", 
 "BesselJ", "ChebyshevT", "UnitTriangle", "Min", "Less", "FresnelC", 
 "MatrixExp", "HypergeometricPFQ", "LessEqual", "Fibonacci", 
 "DateDifference", "BesselY", "LogIntegral", "ZetaZero", "Product", "Grad", 
 "MatrixPower", "FourierSeries", "EllipticE", "Csch", "BitOr", "BesselK", 
 "ArcCsch", "SawtoothWave", "RandomInteger", "Numerator", "Convergents", 
 "Normalize", "ModularLambda", "JacobiAmplitude", "Implies", "Gudermannian", 
 "Coefficient", "Transpose", "HarmonicNumber", "Factor", "EllipticK", 
 "ArcSech", "SinhIntegral", "SeriesData", "QGamma", "Divide", "DawsonF", 
 "CoshIntegral", "Catalan", "Apart", "SphericalBesselJ", "Power", 
 "LegendreP", "KroneckerDelta", "Fit", "Direction", "BitAnd", "Times", 
 "RiemannSiegelZ", "PauliMatrix", "LaplaceTransform", "JacobiZeta", 
 "Intersection", "HeavisideLambda", "First", "Chop", "C", "Binomial", "Sort", 
 "PrimeZetaP", "Null", "NevilleThetaN", "MatrixForm", "JacobiSC", 
 "Interpolation", "FresnelS", "Fourier", "Erfc", "Equal", "Dot", 
 "DivisorSigma", "CenterDot", "BesselJZero", "BernoulliB", "Tr", "Style", 
 "StieltjesGamma", "QPolyGamma", "Projection", "Piecewise", "NevilleThetaS", 
 "Mean", "InverseGudermannian", "Integer", "If", "HypergeometricU", 
 "Haversine", "GreaterEqual", "Greater", "GCD", "GammaRegularized", 
 "ExpectedValue", "Erfi", "EllipticF", "Det", "CosIntegral", "Complement", 
 "WeierstrassP", "Variance", "Unequal", "Tally", "Symbol", "StringMatchQ", 
 "SquareWave", "Slot", "RootMeanSquare", "RiemannR", "Reverse", 
 "Rationalize", "RamanujanTau", "PrimeQ", "PolyLog", "PolyGamma", "OddQ", 
 "Negative", "MinusPlus", "LCM", "Last", "KelvinBei", "JacobiCN", 
 "InverseLaplaceTransform", "InverseErf", "IdentityMatrix", 
 "Hypergeometric2F1", "GroebnerBasis", "GeneratingFunction", "Flatten", 
 "Evaluate", "Equivalent", "Eigenvectors", "Div", "Discriminant", 
 "DedekindEta", "Curl", "Convolve", "ContinuedFraction", "Complex", 
 "BitShiftLeft", "BarnesG", "Assuming", "Apply"}
