{"Cos", "Sin", "I", "E", "Sqrt", "Exp", "D", "Pi", "Quantity", "Log", "Cosh", 
 "Sinh", "None", "MatrixPower", "Det", "Subscript", "Tan", "Abs", 
 "Derivative", "Inverse", "Array", "Rational", "Plus", "Binomial", 
 "BaseForm", "MatrixForm", "Transpose", "Root", "Beta", "Sec", "RandomReal", 
 "Floor", "Sum", "Ratios", "JacobiSymbol", "Mod", "Cot", "ArcCos", "ArcTan", 
 "Table", "Identity", "Gamma", "ArcSin", "IdentityMatrix", "Csc", 
 "Integrate", "BesselI", "Eigenvalues", "Degree", "Cross", "Norm", 
 "Conjugate", "Range", "RowReduce", "ExpIntegralEi", "Last", "First", 
 "Prime", "MatrixExp", "BitAnd", "Eigenvectors", "Log2", "Coefficient", 
 "HilbertMatrix", "Coth", "BitOr", "GoldenRatio", "Resolve", "Product", 
 "Log10", "Zeta", "RandomInteger", "Projection", "KroneckerDelta", "DawsonF", 
 "ConjugateTranspose", "MatrixRank", "Infinity", "EllipticE", "BarnesG", 
 "ToeplitzMatrix", "HeavisideTheta", "UnitStep", "Tr", "RotationMatrix", 
 "Outer", "Diagonal", "Column", "Automatic", "Wronskian", "Times", "Im", 
 "If", "Grad", "Expand", "Append", "Quotient", "ProductLog", "PrimeNu", 
 "Partition", "N", "Map", "Limit", "Join", "CharacteristicPolynomial", 
 "BesselK", "BesselJ", "ArcCot", "Part", "List", "Integer", "GCD", "Factor", 
 "Dot", "AiryBi", "AiryAi", "UpperTriangularize", "Tuples", "Normalize", 
 "ModularLambda", "ListConvolve", "LaplaceTransform", "Hypergeometric2F1", 
 "HurwitzZeta", "HankelMatrix", "Fibonacci", "EllipticK", "Drop", 
 "Direction", "DateDifference", "ConstantArray", "Ceiling", "Assumptions", 
 "VectorQ", "Unequal", "Style", "StringMatchQ", "Round", "Reverse", "Rest", 
 "Polygon", "PauliMatrix", "Modulus", "LUDecomposition", "Length", 
 "KroneckerProduct", "JacobiZeta", "GeneratingFunction", "EvenQ", "Equal", 
 "Eigensystem", "DedekindEta", "Curl", "Count", "Complement", "Apply", "And"}
