{"Sqrt", "I", "E", "Quantity", "None", "Cos", "Cyclotomic", "Pi", "Sin", 
 "Resultant", "GammaRegularized", "Plus", "Subscript", "Log", "Sum", 
 "MinimalPolynomial", "Integrate", "D", "Discriminant", "Root", "Derivative", 
 "Exp", "EulerE", "Beta", "BaseForm", "Abs", "Ratios", "BellB", "UnitStep", 
 "LegendreP", "Det", "DawsonF", "RiemannSiegelZ", "Expand", "Tan", "Zeta", 
 "Mod", "MatrixForm", "EulerGamma", "Array", "PlusMinus", "FresnelC", 
 "Gamma", "CharacteristicPolynomial", "Intersection", "ChebyshevT", "ArcSin", 
 "Union", "N", "Log2", "Limit", "Interval", "Identity", "GroebnerBasis", 
 "EllipticNomeQ", "EllipticK", "ChebyshevU", "Ceiling", "Apart", "Transpose", 
 "Tr", "Together", "Subfactorial", "Sec", "Rationalize", "PrimePi", "Normal", 
 "Log10", "Inverse", "Infinity", "Grad", "FromDigits", "FourierTransform", 
 "Factor", "Degree", "Cot", "Cells", "BitAnd", "ArrayPad", "AiryAi"}
