{"I", "Sqrt", "Cos", "Sin", "E", "Subscript", "Pi", "Exp", "Transpose", 
 "Quantity", "Conjugate", "None", "Ratios", "MatrixPower", "Inverse", "D", 
 "Plus", "Abs", "Derivative", "RandomReal", "PauliMatrix", "MatrixForm", 
 "Rational", "IdentityMatrix", "KroneckerDelta", "N", "Beta", "Sinh", "Cosh", 
 "Gamma", "MatrixExp", "Infinity", "ArcTan", "KroneckerProduct", "BaseForm", 
 "Table", "DiagonalMatrix", "Sinc", "Cot", "Tan", "Limit", "Diagonal", 
 "RiemannR", "Degree", "Cross", "EulerGamma", "ConstantArray", 
 "ConjugateTranspose", "NullSpace", "Normalize", "ModularLambda", "If", 
 "BitOr", "FourierTransform", "BesselI", "Re", "Range", "Prime", "Log", 
 "DiracDelta", "Det", "Covariance", "BitAnd", "BarnesG", "Assumptions", 
 "Zeta", "SparseArray", "RowReduce", "Quotient", "JordanDecomposition", 
 "Integrate", "In", "Identity", "Eigenvalues", "Eigensystem", "Dot", 
 "CholeskyDecomposition", "BitXor", "Array", "ArcSin"}
