{"Sqrt", "Integrate", "Pi", "E", "I", "Sin", "Log", "Cos", "BitOr", "Tan", 
 "ArcSinh", "Quantity", "Sec", "Exp", "JacobiAmplitude", "Sinh", "NextPrime", 
 "EllipticPi", "Range", "Floor", "ArcSin", "Infinity", "Cosh", "Abs", 
 "JacobiSN", "None", "Csc", "BesselY", "EllipticE", "Union", "Ratios", 
 "ArcTan", "Sum", "Subscript", "Cot", "ArcCos", "Sech", "Plus", "Limit", 
 "Gamma", "FresnelS", "FresnelC", "EllipticF", "Derivative", "Degree", 
 "BaseForm", "WeierstrassSigma", "Tanh", "StringJoin", "Sign", "Root", 
 "Prime", "PolyLog", "Norm", "MatrixRank", "Log2", "LessEqual", "Less", 
 "InverseFunction", "HeavisidePi", "Gudermannian", "GammaRegularized", 
 "Factor", "EulerE", "EllipticK", "DiracDelta", "D", "Binomial", "And"}
