{"Pi", "ArcSin", "Sqrt", "I", "Sin", "ArcSinh", "Cos", "BitOr", "E", 
 "ArcCos", "ArcTan", "Exp", "Log", "Csc", "Tan", "Sinc", "Degree", 
 "Infinity", "EllipticE", "Abs", "DiracDelta", "Quantity", "None", 
 "JacobiAmplitude", "Derivative", "D", "SinIntegral", "LogIntegral", 
 "HeavisideTheta", "Beta", "Zeta", "UnitStep", "EllipticF", "Sign", "Range", 
 "MeijerG", "GoldenRatio", "Erf", "UnitBox", "Re", "Rational", "JacobiSN", 
 "Integrate", "Erfi", "EllipticPi", "CosIntegral", "Cosh", "ArcCsch", "Tanh", 
 "Subscript", "Sinh", "Sec", "HypergeometricU", "Dt", "Coth", "Cot", 
 "BesselJ", "BaseForm", "WeierstrassP", "Union", "SquareWave", "ProductLog", 
 "PrimePi", "PlusMinus", "Intersection", "Gudermannian", "Gamma", "FresnelC", 
 "Fibonacci", "EulerE", "ArcCsc", "ArcCot"}
