{"Pi", "Sin", "MinimalPolynomial", "Sqrt", "ArcTan", "E", "I", "ArcCos", 
 "ArcSin", "Log", "VectorAngle", "Cos", "Quantity", "Tan", "Arg", 
 "Integrate", "Subscript", "GammaRegularized", "Ratios", "Rational", "Norm", 
 "Abs", "Degree", "Expand", "Derivative", "None", "Exp", "Root", "Mod", 
 "Table", "Product", "PolynomialGCD", "Im", "Function", "EulerPhi", 
 "EulerGamma", "Denominator", "Cot", "Zeta", "Tanh", "Sum", "Re", "Range", 
 "ProductLog", "N", "Map", "Log2", "Log10", "List", "Limit", "Join", 
 "JacobiAmplitude", "Inverse", "Infinity", "Identity", "GeneratingFunction", 
 "GCD", "Dot", "Cyclotomic", "Cross", "CosineDistance", "Conjugate", 
 "BesselI", "ArcCot"}
