{"Pi", "Sin", "Cos", "Abs", "E", "I", "Exp", "Piecewise", "HeavisideTheta", 
 "UnitBox", "SquareWave", "Subscript", "Less", "LessEqual", "UnitStep", 
 "Sign", "Infinity", "DiracDelta", "Sqrt", "Sum", "Floor", "Quantity", 
 "Cosh", "None", "Log", "Max", "TriangleWave", "Range", "SawtoothWave", 
 "Cot", "Sinh", "PolyLog", "Tan", "Ratios", "EllipticPi", "Csc", "Plus", 
 "Interval", "ArcCos", "Mod", "Integrate", "AiryAi", "UnitTriangle", "Sec", 
 "IntegerPart", "HeavisidePi", "HarmonicNumber", "ArcSin", "Tanh", 
 "Derivative", "AiryBi", "Zeta", "Sinc", "Re", "Rational", "PrimePi", "Min", 
 "KroneckerDelta", "JacobiCN", "If", "HypergeometricU", "Expand", "Erf", 
 "Equal", "Degree", "DawsonF", "BitOr", "BesselK", "Arg"}
