{"RotationMatrix", "Line", "EdgeForm", "AbsoluteThickness", "Dynamic", 
 "RGBColor", "Polygon", "AbsolutePointSize", "Thickness", 
 "RotationTransform", "Circle", "CapForm", "Thick", "PointSize", "Point", 
 "Map", "GraphicsComplex", "Black", "TranslationTransform", "Text", 
 "ShearingTransform", "ReflectionTransform", "Red", "GrayLevel", 
 "GeometricTransformation", "Blue", "LightRed", "Composition", 
 "TransformationFunction", "Table", "Style", "Sphere", "Sin", 
 "ScalingTransform", "ScalingMatrix", "RescalingTransform", "Rectangle", 
 "Purple", "ParametricPlot3D", "Opacity", "Mean", "Inset", "Gray", "First", 
 "FaceForm", "Disk", "Dashing", "Cuboid", "Cos", "ControlActive", 
 "AffineTransform"}
