{"Polygon", "Text", "Line", "If", "Translate", "Cylinder", "Point", 
 "RGBColor", "Cuboid", "False", "Opacity", "Sphere", "Arrow", "Boxed", 
 "Rotate", "ImageSize", "Hue", "True", "GrayLevel", "PlotRange", "Thickness", 
 "Style", "ViewPoint", "Lighting", "Table", "PointSize", "Automatic", "Tube", 
 "Specularity", "Map", "Lighter", "Green", "Yellow", "Axes", "EdgeForm", 
 "AspectRatio", "ColorData", "SphericalRegion", "Red", "Dynamic", "White", 
 "GraphicsComplex", "ViewCenter", "Gray", "Switch", "Pink", "Flatten", "D", 
 "ContentSelectable", "Black", "Thin", "Scale", "Medium", "BoxRatios", 
 "AxesLabel", "AbsoluteThickness", "Thick", "Pi", "Join", "Inset", 
 "FaceForm", "Directive", "Dashed", "Darker", "CapForm", "Background", 
 "Arrowheads", "ToString", "Function", "Sin", "Apply", "ViewVertical", 
 "ViewAngle", "PlotLabel", "GeometricTransformation", "Cos", "Brown", 
 "Tooltip", "Take", "None", "ImageScaled", "Graphics3D", "Glow", "Cone", 
 "Blue", "All", "Sqrt", "Rectangle", "ParametricPlot3D", "LabelStyle", 
 "Texture", "SurfaceGraphics", "N", "MapThread", "Epilog", "C", "With", 
 "ViewVector", "Row", "Range", "PlotRangePadding", "Orange", "Options", "O", 
 "NumericQ", "Method", "List", "LightBlue", "ImagePadding", "First", 
 "FaceGrids", "Degree", "Dashing", "ControlActive", "BoxStyle", "AxesEdge", 
 "AbsolutePointSize", "Round", "Re", "NumberQ", "NestList", "IntegerDigits", 
 "Identity", "Cell", "BSplineFunction", "Break", "Which", "ViewRange", 
 "ViewMatrix", "Union", "TraditionalForm", "Top", "Tiny", "TicksStyle", 
 "Ticks", "Thread", "Symbol", "Small", "Select", "SeedRandom", "Scaled", 
 "RotationAction", "Rescale", "RenderAll", "Purple", "Prolog", 
 "PreserveImageOptions", "Prepend", "PolyhedronData", "PlotRegion", "Pick", 
 "PerformanceGoal", "Part", "NSolve", "Normalize", "Normal", "Nest", 
 "Module", "Min", "Max", "MatrixQ", "MatchQ", "MapIndexed", "Magenta", 
 "LightYellow", "LightRed", "LightGreen", "LightGray", "LightCyan", "Large", 
 "JoinForm", "Infinity", "In", "ImageMargins", "I", "HoldPattern", "Grid", 
 "Full", "Front", "FontSize", "FontFamily", "FoldList", "Fold", 
 "FaceGridsStyle", "Exp", "EventHandler", "Evaluate", "E", "Dotted", 
 "DotDashed", "Disk", "DeleteCases", "DateString", "Cyan", "Column", "Chop", 
 "Ceiling", "BSplineSurface", "BSplineCurve", "Bottom", "Bold", "Blend", 
 "BaseStyle", "AxesStyle", "AxesOrigin", "Array"}
