{"Sqrt", "KroneckerDelta", "E", "I", "Sin", "Quantity", "Cos", "Pi", "None", 
 "Log", "Integrate", "Subscript", "D", "BaseForm", "Tan", "Mod", "Sinh", 
 "Floor", "PrimeZetaP", "DivisorSigma", "DiracDelta", "Limit", "DawsonF", 
 "Abs", "Plus", "Infinity", "Exp", "Cross", "Re", "Norm", "Im", "Gamma", 
 "FractionalPart", "Derivative", "ArcTan", "SquareWave", "Sign", "Fibonacci", 
 "Degree", "Beta", "Sum", "Ratios", "Log10", "RiemannSiegelZ", "Quotient", 
 "N", "LogIntegral", "Log2", "LeviCivitaTensor", "GammaRegularized", "Dt", 
 "BarnesG", "Transpose", "Tanh", "Sinc", "MatrixPower", "MatrixForm", "LCM", 
 "JacobiSN", "HypergeometricU", "HoldPattern", "EulerGamma", "EllipticPi", 
 "Csc", "Cosh", "Conjugate", "BitXor", "Arg", "ArcSin", "ArcCos"}
