{"Cos", "Pi", "Sqrt", "Sin", "E", "Expand", "I", "Range", "Abs", "BitOr", 
 "Tanh", "RandomReal", "Cosh", "Quantity", "LegendreP", "Exp", "Degree", 
 "Tan", "RandomInteger", "None", "Ratios", "Piecewise", "LessEqual", "Less", 
 "Coefficient", "ArcTan", "Log", "Derivative", "Sign", "DiracDelta", "Coth", 
 "PrimeZetaP", "Integrate", "ArcCos", "Quotient", "Log2", "HeavisideTheta", 
 "Beta", "Zeta", "Sum", "SphericalHarmonicY", "Round", "Floor", "Automatic", 
 "UnitStep", "Sinh", "PrimePi", "Norm", "Mod", "JacobiP", "Interpolation", 
 "GeneratingFunction", "GegenbauerC", "Erfc", "Plus", "LaguerreL", 
 "JacobiSymbol", "Infinity", "Im", "Gamma", "FractionalPart", 
 "EllipticNomeQ", "D", "Arg", "ArcCot", "Apart", "WeierstrassP", "Subscript", 
 "Rational", "Projection", "Prime", "N", "MatrixExp", "Log10", "JacobiZeta", 
 "HermiteH", "GroebnerBasis", "FourierTransform", "FourierSeries", 
 "Fibonacci", "ExpIntegralEi", "EvenQ", "Erf", "DivisorSigma", 
 "DateDifference", "Csc", "BitAnd", "BesselI", "ArcSin"}
