{"Cos", "Sin", "Sqrt", "Tan", "Pi", "O", "VertexColors", "Normalize", "Map", 
 "Last", "Table", "First", "E", "Flatten", "D", "Cot", "Red", "Max", "Green", 
 "InverseCDF", "Length", "Blue", "Offset", "Magenta", "Dynamic", "Which", 
 "List", "If", "Log", "StringForm", "N", "ColorData", "RotationMatrix", 
 "Quantile", "Append", "Min", "Re", "Point", "Norm", "Mean", "Function", 
 "Transpose", "SequenceForm", "Line", "Integer", "Im", "Sort", "PDF", 
 "ArcCos", "Take", "Sec", "Quotient", "IntegerPart", "Evaluate", "Join", 
 "Eigenvectors", "Degree", "Abs", "TranslationTransform", "Sign", 
 "RandomReal", "MapAt", "Exp", "All", "Sinh", "Scaled", "RGBColor", 
 "Position", "Hue", "EuclideanDistance", "Cosh", "Thread", "Sum", "Select", 
 "RotationTransform", "Rotate", "Range", "Random", "Quiet", "Partition", 
 "Normal", "NestList", "MousePosition", "Most", "Mod", "MatrixQ", "Log10", 
 "Intersection", "Graphics", "Floor", "DeleteCases", "Cross", "C", "Black", 
 "VectorAngle", "String", "Sequence", "Right", "ReplacePart", "Release", 
 "Positive", "NumericQ", "MemberQ", "Median", "Limit", "Left", "Khinchin", 
 "In", "ImageScaled", "Chop", "CDF", "Boole", "Apply", "$Line", "With", 
 "Union", "Tuples", "True", "Tr", "Total", "ToString", "Switch", "Subsets", 
 "Rule", "Round", "Riffle", "Rest", "Projection", "Prepend", "Polygon", 
 "PlotPoints", "Outer", "NumberQ", "None", "Nest", "MapThread", "MapIndexed", 
 "Insert", "ImageSize", "ImageDimensions", "I", "Histogram", "Head", 
 "Graphics3D", "FoldList", "Fold", "FindRoot", "False", "Csc", 
 "ContourGraphics", "Complement", "Ceiling", "Block", "Arrow"}
