{"I", "Sqrt", "Plus", "Pi", "E", "Subscript", "Quantity", "Transpose", "Sin", 
 "Cos", "Exp", "None", "IdentityMatrix", "Abs", "Log", "Mod", "Degree", 
 "Sinh", "Gamma", "Cosh", "Derivative", "Inverse", "MatrixPower", "N", 
 "Table", "Rational", "HarmonicNumber", "Modulus", "Beta", "All", "Method", 
 "HilbertMatrix", "D", "UnitStep", "Identity", "HypergeometricU", 
 "Eigenvectors", "ConstantArray", "SparseArray", "RandomReal", "Log10", 
 "First", "Covariance", "BaseForm", "Append", "Zeta", "Thread", "FresnelC", 
 "Drop", "DiagonalMatrix", "Cross", "Column", "ZeroTest", "Prepend", 
 "MatrixForm", "Map", "Limit", "Function", "Flatten", "Det", "Conjugate", 
 "Cells", "C"}
