{"Function", "Rule", "If", "Transpose", "Range", "List", "Flatten", "Table", 
 "Pi", "Drop", "RotateLeft", "Map", "RotateRight", "Reverse", "RandomSample", 
 "Dot", "Take", "Apply", "Times", "Sqrt", "Rest", "Partition", "Max", 
 "Append", "Re", "RandomReal", "Min", "MapThread", "Im", "Complement", "C", 
 "Array", "Union", "True", "Text", "TagSet", "ReplacePart", "Prepend", 
 "Nest", "Length", "Join", "Head", "False", "Dt", "Dimensions", "Cross", 
 "Cases", "Arrow", "Accumulate", "Yellow", "Uncompress", "Tuples", "Tooltip", 
 "Thread", "Style", "Square", "SeedRandom", "ReplaceAll", "Red", "Purple", 
 "Power", "Position", "Plus", "Pink", "Part", "Pane", "Orange", "Options", 
 "NumberQ", "Normalize", "Normal", "Most", "Mod", "MemberQ", "Magenta", 
 "LightRed", "LightBlue", "Last", "IntegerDigits", "Green", "Floor", "First", 
 "Extract", "Evaluate", "Dotted", "D", "Cyan", "ColorSeparate", "ColorData", 
 "Brown", "Blue", "BinCounts"}
