{"I", "Pi", "Log", "Sqrt", "Sin", "Cos", "E", "Quantity", "Exp", "Subscript", 
 "Fit", "None", "PauliMatrix", "Beta", "Integrate", "Table", "Inverse", 
 "FourierSeries", "MatrixExp", "KroneckerProduct", "FourierTransform", 
 "Sinh", "MatrixPower", "Prime", "Plus", "IdentityMatrix", "Cosh", 
 "Interpolation", "ArcCos", "Transpose", "JordanDecomposition", "ArcSin", 
 "GeneratingFunction", "Gamma", "ArcTan", "Rational", "Expand", 
 "Eigenvalues", "MatrixForm", "HeavisideTheta", "DiagonalMatrix", 
 "MoebiusMu", "D", "HermiteH", "Erf", "Abs", "Range", "Log2", "Cot", 
 "Normal", "Derivative", "Conjugate", "BitOr", "Automatic", "ArcTanh", 
 "ArcSinh", "Tan", "Sign", "HarmonicNumber", "Degree", "Cross", "Tr", "Tanh", 
 "Sum", "RotationMatrix", "Mod", "Mean", "Log10", "JacobiAmplitude", 
 "Fibonacci", "EulerGamma", "DivisorSigma", "Coth", "Times", 
 "StandardDeviation", "SparseArray", "Sinc", "PrimePi", "N", "MemberQ", 
 "Limit", "Infinity", "Identity", "GroebnerBasis", "FresnelC", "Exponent", 
 "EllipticPi", "Dot", "DateDifference", "Convolve", "Composition", 
 "Coefficient", "CharacteristicFunction", "Binomial", "BesselJ", "BaseForm", 
 "Arg"}
