{"Sin", "Function", "Integrate", "Nest", "Cos", "Sqrt", "RandomInteger", "E", 
 "ArcTan", "Log", "Exp", "I", "Quantity", "Floor", "N", "Expand", "None", 
 "FractionalPart", "Subsuperscript", "Tan", "RandomChoice", "Mod", "Factor", 
 "Differences", "Table", "Pi", "If", "D", "Prime", "PlusMinus", "Derivative", 
 "Random", "Identity", "Round", "Plus", "EvenQ", "And", "StringReplace", 
 "Range", "SinIntegral", "NextPrime", "Most", "Max", "Length", "Last", 
 "Join", "JacobiSymbol", "Inverse", "IntegerDigits", "Circle", "Ceiling", 
 "Accumulate", "Abs", "With", "White", "Take", "StringTake", "SetPrecision", 
 "SeedRandom", "Scale", "SawtoothWave", "RotateRight", "RotateLeft", 
 "Rotate", "ReplacePart", "Quotient", "Polygon", "PadRight", "Null", 
 "Normal", "Min", "MapAt", "Map", "List", "Line", "Integer", "First", 
 "FieldSize", "EllipticE", "Dot", "Cot", "ControlActive", "Binomial", 
 "Automatic", "Array", "ArcSin"}
