{"Cos", "Sqrt", "Sin", "Log", "E", "Floor", "Pi", "Round", "I", "Mod", 
 "Function", "Exp", "Sign", "Quantity", "Map", "Gamma", "D", "Tan", "Min", 
 "None", "Subsuperscript", "N", "Log10", "Length", "Sequence", "Sum", 
 "Range", "Power", "PadRight", "Derivative", "Xor", "TensorRank", "RiemannR", 
 "Nest", "First", "ReplacePart", "PowerMod", "Line", "Join", "ArcSin", 
 "Piecewise", "Ceiling", "Zeta", "SawtoothWave", "PlusMinus", "Infinity", 
 "Identity", "Head", "Flatten", "Coth", "Circle", "Transpose", "Tr", "Total", 
 "Table", "Subscript", "StringReplace", "Sec", "Rectangle", "RandomInteger", 
 "PolyhedronData", "Plus", "Partition", "Outer", "Log2", "List", "Last", 
 "LaplaceTransform", "Integer", "If", "Drop", "Divide", "Degree", 
 "Conjugate", "Characters", "Automatic", "Abs"}
