{"Sqrt", "I", "Cos", "Sin", "E", "Cross", "Pi", "Normalize", "Exp", 
 "Eigenvectors", "D", "Abs", "Quantity", "Subscript", "Log", "Infinity", 
 "Integrate", "RandomReal", "N", "RotationTransform", "Tan", "None", 
 "Rational", "Orthogonalize", "Degree", "Csc", "Norm", "Product", 
 "Projection", "Eigensystem", "Ratios", "Inverse", "Column", "Zeta", 
 "Transpose", "Sec", "LegendreP", "PauliMatrix", "Log10", "Grad", "Cosh", 
 "Beta", "Piecewise", "List", "Erfc", "Eigenvalues", "ArcSin", "Sinh", 
 "Range", "LessEqual", "HeavisideTheta", "FourierTransform", "Expand", 
 "Diagonal", "SphericalHarmonicY", "Sech", "Plus", "Less", "IntegerDigits", 
 "Floor", "Evaluate", "C", "BaseForm", "With", "Symbol", "Rule", "RowReduce", 
 "RotationMatrix", "Root", "RandomInteger", "PrimeZetaP", "PrimePi", 
 "NonlinearModelFit", "ModularLambda", "Min", "Mean", "ListCorrelate", 
 "Last", "Interval", "HypergeometricU", "GreaterEqual", "Function", "First", 
 "FilterRules", "Erf", "Dt", "Dot", "Curl", "Conjugate", "BesselJ", "ArcTan", 
 "ArcCos"}
