{"Cell", "False", "Automatic", "WindowTitle", "WindowSize", "WindowMargins", 
 "WindowElements", "True", "Inherited", "Fit", "WindowToolbars", 
 "WindowFrameElements", "WindowFrame", "WindowFloating", "WindowClickSelect", 
 "TaggingRules", "StyleDefinitions", "ShowCellTags", "ShowCellLabel", 
 "ShowCellBracket", "Selectable", "ScreenRectangle", "Saveable", "RGBColor", 
 "PrivateNotebookOptions", "None", "Manual", "Magnification", "ImageMargins", 
 "GrayLevel", "Editable", "DockedCells", "Deployed", "Copyable", 
 "ClosingAutoSave", "CellOpen", "CellMargins", "CellGrouping", "Background", 
 "AutoGeneratedPackage"}
