{"Sqrt", "Log", "E", "Subscript", "Exp", "Sin", "Pi", "Cos", "I", 
 "Derivative", "Cosh", "Quantity", "Integrate", "D", "Abs", "Tan", "Norm", 
 "Erf", "Log2", "None", "Infinity", "Zeta", "Product", "HermiteH", "Cot", 
 "Conjugate", "Binomial", "Flatten", "First", "ArcCos", "$MaxExtraPrecision", 
 "Sum", "SphericalBesselJ", "Sec", "PlusMinus", "Plus", "Mod", "Log10", "If", 
 "EuclideanDistance", "WorkingPrecision", "Transpose", "Sinh", "PolyGamma", 
 "Normalize", "NIntegrate", "Last", "Floor", "EllipticTheta", "EllipticE", 
 "BesselJ", "Table", "Re", "Prime", "Pochhammer", "Numerator", "Normal", 
 "LessEqual", "Less", "LegendreP", "Function", "Dt", "Denominator", "Degree", 
 "Chop", "C", "ArcTan", "ArcSin", "ArcCot", "Apply"}
