{"I", "Sqrt", "Transpose", "Quantity", "None", "Cos", "Sin", "Eigenvectors", 
 "Plus", "Integrate", "Orthogonalize", "Abs", "Subscript", "Exp", "E", 
 "NullSpace", "D", "Pi", "Eigenvalues", "GroebnerBasis", "Infinity", 
 "MatrixForm", "MatrixPower", "Projection", "BitOr", "RowReduce", "Ratios", 
 "FourierTransform", "Dot", "Table", "Rational", "Range", "Product", 
 "HilbertMatrix", "Coefficient", "UnitStep", "True", "Sinh", "Sinc", "Root", 
 "NIntegrate", "Method", "MatrixExp", "Inverse", "Column", "Beta", "Sec", 
 "LegendreP", "LatticeReduce", "Join", "False", "Factor", "Eigensystem", 
 "Diagonal", "Degree", "Csc", "Cross", "Coth", "Complement", "Binomial", 
 "BaseForm"}
