{"Sin", "Cos", "Pi", "Sqrt", "List", "C", "NumericQ", "Table", "Last", "Map", 
 "Log", "E", "If", "First", "Tan", "RotationTransform", "Apply", "Re", "Im", 
 "Graph", "Function", "Polygon", "Transpose", "N", "Flatten", "Evaluate", 
 "DeleteCases", "Cot", "All", "Point", "Dynamic", "Circle", "Append", 
 "Sequence", "Rescale", "Integer", "Indeterminate", "In", "FontSize", 
 "VertexColors", "Switch", "String", "Sinh", "Sign", "RotationMatrix", 
 "Reverse", "Range", "RandomReal", "Quantile", "Offset", "NumberQ", "Mod", 
 "Log10", "FractionalPart", "Exp", "Cosh", "Abs", "With", "Take", "Sum", 
 "Select", "RandomSample", "Random", "Radon", "Quiet", "PolyhedronData", 
 "PlotPoints", "Piecewise", "Partition", "O", "Norm", "Length", "D", "Chop", 
 "Center", "Cases", "Boole", "ArcTan", "ArcSin", "Which", "VertexNormals", 
 "VectorQ", "Tuples", "Total", "Together", "Through", "Thread", "Tanh", 
 "Symbol", "Solve", "Set", "Sech", "Red", "Position", "Pink", "Or", 
 "Normalize", "None", "NestList", "Most", "Min", "Median", "Mean", "MatrixQ", 
 "MapIndexed", "ListCorrelate", "Limit", "LightBrown", "Join", "IntegerPart", 
 "ImageSize", "Green", "Graphics3D", "Graphics", "Floor", "FindRoot", "Drop", 
 "Det", "Cyan", "Csc", "Cross", "ContourGraphics", "Complement", "Ceiling", 
 "Black", "Automatic", "Array"}
