{"Sqrt", "Cos", "Sin", "Tan", "List", "Map", "RGBColor", "Join", "Table", 
 "Polygon", "VertexColors", "Lighter", "Fibonacci", "Reverse", "Which", "Pi", 
 "Mod", "Flatten", "Append", "Transpose", "Dynamic", "Yellow", "IntegerPart", 
 "Hue", "First", "Apply", "Darker", "Red", "Function", "Normalize", "Min", 
 "MatrixQ", "If", "Graphics3D", "Black", "VertexTextureCoordinates", 
 "Offset", "I", "C", "Select", "Round", "Range", "Green", "Chop", "Blue", 
 "With", "Sum", "Real", "Line", "Last", "ColorData", "AffineTransform", 
 "White", "VectorQ", "Take", "Sort", "RotationMatrix", "RandomReal", 
 "Prepend", "Max", "MapThread", "Integer", "D", "CMYKColor", "Tr", 
 "Together", "Sequence", "RotationTransform", "Riffle", "Re", "Point", 
 "MapAt", "LightGray", "Length", "Inverse", "In", "Im", "HoldPattern", 
 "Gray", "Fold", "FindRoot", "E", "Ceiling", "All", "Union", "Tuples", 
 "TrueQ", "Thread", "Subsets", "Show", "Rule", "RotateLeft", "Rest", 
 "ReflectionMatrix", "Quiet", "Positive", "Outer", "OptionsPattern", "Null", 
 "N", "Most", "Module", "InterpolatingPolynomial", "IntegerDigits", "Inner", 
 "Identity", "Find", "Drop", "Delete", "Array", "Arg"}
