{"Pi", "Mesh", "False", "Tan", "PlotStyle", "None", "BoundaryStyle", "Black", 
 "Automatic", "Sin", "Cos", "PlotRange", "Boxed", "PerformanceGoal", "Axes", 
 "PlotPoints", "AspectRatio", "RGBColor", "ControlActive", "All", "Gray", 
 "FaceForm", "Darker", "Thick", "Text", "Sqrt", "RevolutionAxis", 
 "MeshStyle", "MeshShading", "If", "Function", "ColorFunction", "BoxRatios", 
 "Log", "Dynamic", "Brown", "ViewVertical", "ViewPoint", "ViewAngle", "True", 
 "Ticks", "Tanh", "Style", "SphericalRegion", "Sech", "Reverse", 
 "RegionFunction", "PlotLabel", "Opacity", "NormalsFunction", "Medium", 
 "MaxRecursion", "ImageSize", "GrayLevel", "FaceGridsStyle", "FaceGrids", 
 "Exclusions", "Evaluate", "Directive", "ColorFunctionScaling", "Blue", 
 "Blend", "Background", "AxesLabel"}
