{"Pi", "Polygon", "Rotate", "Translate", "Degree", "Cylinder", "Scale", 
 "Line", "RGBColor", "Text", "Cuboid", "If", "Rectangle", "Opacity", "Disk", 
 "Arrow", "Sphere", "ArcTan", "Thick", "Table", "Sin", "PolyhedronData", 
 "Normal", "Glow", "N", "Black", "Normalize", "Cos", "Tube", "Point", 
 "Circle", "Style", "Gray", "EdgeForm", "Dynamic", "Cases", "White", 
 "RevolutionPlot3D", "Map", "Last", "Sqrt", "Mod", "Hue", "Blue", "NumberQ", 
 "Sign", "PointSize", "Orange", "List", "Floor", "ArcCos", "Which", 
 "Thickness", "Square", "RegionPlot3D", "Red", "Plot", "ParametricPlot3D", 
 "Green", "First", "FaceForm", "Cone", "ColorData", "ArcSin", "Tr", "O", 
 "Mean", "Log", "LightBrown", "GrayLevel", "Graphics", "D", "CapForm", 
 "BezierCurve", "Abs", "Yellow", "With", "Through", "Thread", "Tanh", 
 "Switch", "SphericalPlot3D", "Specularity", "Round", "RotationTransform", 
 "Raster", "Purple", "Pink", "Piecewise", "Offset", "Null", "MatrixPlot", 
 "LightBlue", "Inset", "Image", "Function", "Flatten", "Erfc", "Dashing", 
 "Dashed", "Cyan", "Cross", "Cot", "ControlActive", "Brown", "Blend", 
 "Arrowheads", "ArrayPlot", "Arg", "ArcCot", "Apply", "Append", 
 "AbsoluteThickness"}
