{"Sin", "Sqrt", "Log", "Exp", "E", "Cos", "I", "Pi", "Sum", "ArcTan", 
 "Infinity", "Tan", "Cot", "Plus", "Sinh", "Product", "Cosh", "Abs", "Sec", 
 "Quantity", "ArcSin", "Coth", "BesselJ", "Zeta", "Integrate", "Subscript", 
 "Gamma", "Csc", "ZetaZero", "AiryAi", "Tanh", "Log10", "Binomial", 
 "SeriesCoefficient", "RiemannSiegelZ", "None", "Floor", "Assumptions", 
 "ArcCos", "ExpIntegralEi", "Range", "PolyGamma", "ArcCot", "ProductLog", 
 "PolynomialMod", "Log2", "Limit", "InverseGammaRegularized", "Expand", 
 "Cross", "Sinc", "BesselY", "Prime", "Degree", "Csch", "BesselK", 
 "StirlingS2", "PolynomialQuotientRemainder", "Norm", "MatrixPower", 
 "Hypergeometric0F1Regularized", "DawsonF", "Sign", "Sech", "Ratios", 
 "PolynomialGCD", "GeneratingFunction", "Erf", "DedekindEta", "AiryAiPrime", 
 "WeierstrassZeta", "Rational", "PolyLog", "Mod", 
 "HypergeometricPFQRegularized", "Hypergeometric2F1", "Hypergeometric0F1", 
 "Hyperfactorial", "FindGeneratingFunction", "Fibonacci", "ExpIntegralE", 
 "EllipticK", "Derivative", "D", "BaseForm", "Apart"}
