{"Pi", "Log", "I", "Sqrt", "ArcSinh", "ArcCosh", "Cosh", "E", "ArcTanh", 
 "Sin", "Sinh", "Cos", "ArcSin", "Tan", "Abs", "Tanh", "Quantity", "Exp", 
 "Degree", "ArcTan", "ArcCos", "Rational", "None", "Derivative", "Coth", 
 "ArcCoth", "Cot", "Log2", "Plus", "Subscript", "PrimePi", "Sec", "Log10", 
 "Integrate", "BesselI", "GoldenRatio", "BaseForm", "ArcSech", "Sech", 
 "ArcCsch", "Inverse", "Identity", "D", "Infinity", "EllipticPi", "Csch", 
 "Root", "RandomReal", "Im", "Arg", "InverseFunction", "Floor", "ArcCot", 
 "Gamma", "Csc", "Conjugate", "PlusMinus", "Ceiling", "Automatic", "Re", 
 "PauliMatrix", "MatrixExp", "Zeta", "Erf", "BesselJZero", "ArcSec", 
 "ArcCsc", "Beta", "Range", "ProductLog", "EllipticK", "Sum", "SinIntegral", 
 "Sinc", "Ratios", "ModularLambda", "LogIntegral", "ExpIntegralEi", 
 "EulerGamma", "EulerE", "BesselJ", "ZetaZero", "UnitStep", "Quotient", 
 "Mod", "FractionalPart", "Fit", "DateDifference", "Transpose", "Tr", 
 "Symbol", "Subtract", "Subfactorial", "StringTake", "Sort", "SinhIntegral", 
 "Sign", "Quantile", "PrimeZetaP", "Prime", "NMaxValue", "MatrixPower", 
 "Interval", "HeavisideTheta", "FresnelC", "FourierTransform", "Flatten", 
 "EulerPhi", "Erfc", "EllipticE", "DiracDelta", "DawsonF", "Count", "BitOr", 
 "BesselK"}
