{"Polygon", "Rotate", "Disk", "EdgeForm", "Translate", "Opacity", "Line", 
 "If", "Orange", "Sqrt", "RGBColor", "GrayLevel", "Sin", "Normalize", "Cos", 
 "Black", "Table", "Green", "Cylinder", "Scale", "Pink", "White", "Darker", 
 "LightBlue", "Sphere", "Cuboid", "Tube", "Thickness", "RevolutionPlot3D", 
 "Rectangle", "Pi", "ParametricPlot3D", "ControlActive", "GraphicsComplex", 
 "ViewPoint", "Thick", "Text", "Sum", "Specularity", "RegionPlot3D", "Red", 
 "Options", "Mod", "Map", "GridGraph", "First", "Cyan", "Arrow", "Point", 
 "Norm", "Log", "Exp", "Cone", "Yellow", "Tr", "Total", "Through", "Thin", 
 "Tan", "Symbol", "Switch", "Style", "Show", "Sec", "Quotient", 
 "PolyhedronData", "PointSize", "NumberQ", "Min", "Mean", "MapIndexed", 
 "List", "Length", "Inset", "Gray", "Function", "Floor", "Flatten", 
 "FilledCurve", "FaceForm", "Dynamic", "Drop", "DotDashed", "D", "ColorData", 
 "Circle", "BSplineSurface", "BSplineCurve", "Brown", "Blue", "Blend", 
 "Append", "Abs"}
