(* Created with the Wolfram Language : www.wolfram.com *)
BeginPackage["OpenLibraryFunctions`"];

mapLanguage::usage = "";
mapPublishCountryCode::usage = "";

Begin["`Private`"];

mapLanguage[language_] := Module[{aux},(
		aux = StringTrim[language];
		If[KeyExistsQ[languagesMap,ToString[aux]],ToString[aux] /. languagesMap,Missing["NotAvailable"]]
	)]
	
mapPublishCountryCode[code_] := Module[{aux},(
		aux = StringTrim[code];
		If[KeyExistsQ[publishCountryCodeMap,ToString[aux]],ToString[aux] /. publishCountryCodeMap,Missing["NotAvailable"]]
	)]

languagesMap = {"ady" -> Entity["Language", "Adyghe"], 
 "arc" -> {"Imperial Aramaic (700-300 BCE)", 
   "Official Aramaic (700-300 BCE)"}, 
 "arn" -> Entity["Language", "Mapudungun"], 
 "ast" -> {"Bable", "Leonese", Entity["Language", "Asturian"]}, 
 "bej" -> Entity["Language", "Bedawi"], 
 "bin" -> {"Edo", Entity["Language", "Edo"]}, 
 "byn" -> {"Blin", Entity["Language", "Bilen"]}, 
 "cat" -> {"Valencian", Entity["Language", "CatalanValencianBalear"]}, 
 "chp" -> {"Dene Suline", Entity["Language", "Chipewyan"]}, 
 "chu" -> {"Church Slavic", "Church Slavonic", "Old Bulgarian", 
   "Old Church Slavonic", "Old Slavonic"}, 
 "crh" -> Entity["Language", "CrimeanTurkish"], 
 "div" -> {"Dhivehi", Entity["Language", "Maldivian"]}, 
 "dut" -> {Entity["Language", "Dutch"], Entity["Language", "Vlaams"]}, 
 "nld" -> {Entity["Language", "Dutch"], Entity["Language", "Vlaams"]}, 
 "fil" -> Entity["Language", "Filipino"], 
 "gla" -> {"Gaelic", Entity["Language", "ScottishGaelic"]}, 
 "gsw" -> {"Alemannic", "Alsatian", Entity["Language", "Schwyzerdutsch"]}, 
 "hat" -> {"Haitian", Entity["Language", "HaitianCreoleFrench"]}, 
 "him" -> {"Western Pahari languages", Entity["Language", "Mandeali"]}, 
 "hmn" -> {"Hmong", "Mong"}, 
 "iii" -> {"Nuosu", Entity["Language", "YiSichuan"]}, 
 "ile" -> {"Occidental", Entity["Language", "Interlingua"]}, 
 "kac" -> Entity["Language", "Jingpho"], 
 "kal" -> Entity["Language", "InuktitutGreenlandic"], 
 "kho" -> {Entity["Language", "Dzongkha"], Entity["Language", "Sakan"]}, 
 "kik" -> Entity["Language", "Gikuyu"], 
 "kir" -> Entity["Language", "Kirghiz"], 
 "kua" -> Entity["Language", "Kwanyama"], 
 "lim" -> {"Limburgan", "Limburger", Entity["Language", "Limburgisch"]}, 
 "ltz" -> Entity["Language", "Luxembourgeois"], 
 "mic" -> {"Mi'kmaq", Entity["Language", "Micmac"]}, 
 "nav" -> Entity["Language", "Navajo"], 
 "nbl" -> {"Ndebele, South", "South Ndebele"}, 
 "nde" -> {"Ndebele, North", "North Ndebele"}, 
 "nds" -> {"German, Low", "Saxon, Low", Entity["Language", "Plautdietsch"], 
   Entity["Language", "SaxonLow"]}, "new" -> Entity["Language", "Newar"], 
 "nno" -> {"Nynorsk, Norwegian", Entity["Language", "NorwegianNynorsk"]}, 
 "nob" -> {"Bokm\[ARing]l, Norwegian", Entity["Language", 
    "NorwegianBokmal"]}, "nso" -> Entity["Language", "SothoNorthern"], 
 "nwc" -> {"Classical Nepal Bhasa", "Classical Newari", "Old Newari"}, 
 "nya" -> {"Chichewa", Entity["Language", "Nyanja"]}, 
 "oss" -> {"Ossetic", Entity["Language", "Osetin"]}, 
 "pam" -> {"Pampanga", Entity["Language", "Pampangan"]}, 
 "pan" -> Entity["Language", "PanjabiEastern"], 
 "pro" -> {"Occitan, Old (to 1500)", "Proven\[CCedilla]al, Old (to 1500)"}, 
 "pus" -> {"Pashto", Entity["Language", "PashtoNorthern"]}, 
 "rar" -> Entity["Language", "Rarotongan"], 
 "rum" -> Entity["Language", "Romanian"], 
 "ron" -> Entity["Language", "Romanian"], 
 "rup" -> {"Macedo-Romanian", Entity["Language", "RomanianMacedo"]}, 
 "sin" -> Entity["Language", "Sinhala"], 
 "spa" -> Entity["Language", "Spanish"], 
 "tlh" -> {"Klingon", "tlhIngan-Hol"}, "uig" -> Entity["Language", "Uyghur"], 
 "wal" -> Entity["Language", "Wolaytta"], 
 "xal" -> {"Kalmyk", Entity["Language", "KalmykOirat"]}, 
 "zbl" -> {"Bliss", "Blissymbolics", "Blissymbols"}, 
 "zha" -> {"Zhuang", Entity["Language", "ZhuangNorthern"]}, 
 "zxx" -> {"No linguistic content", "Not applicable"}, 
 "zza" -> {Entity["Language", "Dimli"], Entity["Language", "Karata"], 
   Entity["Language", "Kirmanjki"]}, "aar" -> Entity["Language", "Afar"], 
 "abk" -> "Abkhazian", "ace" -> Entity["Language", "Aceh"], 
 "ach" -> Entity["Language", "Acholi"], 
 "ada" -> Entity["Language", "Dangme"], "afa" -> "Afro-Asiatic languages", 
 "afh" -> Entity["Language", "Bare"], 
 "afr" -> Entity["Language", "Afrikaans"], 
 "ain" -> Entity["Language", "Ainu"], "aka" -> Entity["Language", "Akan"], 
 "akk" -> Entity["Language", "Akkadian"], "alb" -> "Albanian", 
 "ale" -> Entity["Language", "Aleut"], "alg" -> "Algonquian languages", 
 "alt" -> Entity["Language", "AltaiSouthern"], 
 "amh" -> Entity["Language", "Amharic"], 
 "ang" -> "English, Old (ca.450-1100)", 
 "anp" -> Entity["Language", "Angika"], "apa" -> "Apache languages", 
 "ara" -> Entity["Language", "Arabic"], 
 "arg" -> Entity["Language", "Aragonese"], 
 "arm" -> Entity["Language", "Armenian"], 
 "arp" -> Entity["Language", "Arapaho"], "art" -> "Artificial languages", 
 "arw" -> Entity["Language", "Arawak"], 
 "asm" -> Entity["Language", "Assamese"], "ath" -> "Athapascan languages", 
 "aus" -> "Australian languages", "ava" -> "Avaric", 
 "ave" -> Entity["Language", "Avestan"], 
 "awa" -> Entity["Language", "Awadhi"], 
 "aym" -> Entity["Language", "AymaraCentral"], "aze" -> "Azerbaijani", 
 "bad" -> Entity["Language", "Banda"], "bai" -> "Bamileke languages", 
 "bak" -> Entity["Language", "Bashkir"], 
 "bal" -> Entity["Language", "BalochiEastern"], 
 "bam" -> Entity["Language", "Bamanankan"], "ban" -> "Balinese", 
 "baq" -> Entity["Language", "Basque"], "bas" -> Entity["Language", "Basa"], 
 "bat" -> "Baltic languages", "bel" -> Entity["Language", "Belarusan"], 
 "bem" -> Entity["Language", "Bemba"], 
 "ben" -> Entity["Language", "Bengali"], "ber" -> "Berber languages", 
 "bho" -> Entity["Language", "Bhojpuri"], 
 "bih" -> Entity["Language", "Bhojpuri"], 
 "bik" -> Entity["Language", "BicolanoCentral"], 
 "bis" -> Entity["Language", "Bislama"], "bla" -> Entity["Language", "Sika"], 
 "bnt" -> "Bantu languages", "bod" -> Entity["Language", "TibetanCentral"], 
 "bos" -> Entity["Language", "Bosnian"], 
 "bra" -> Entity["Language", "BrajBhasha"], 
 "bre" -> Entity["Language", "Breton"], "btk" -> Entity["Language", "Batak"], 
 "bua" -> "Buriat", "bug" -> Entity["Language", "Bugis"], 
 "bul" -> Entity["Language", "Bulgarian"], 
 "bur" -> Entity["Language", "Burmese"], 
 "cad" -> Entity["Language", "Caddo"], 
 "cai" -> "Central American Indian languages", "car" -> "Galibi Carib", 
 "cau" -> "Caucasian languages", "ceb" -> Entity["Language", "Cebuano"], 
 "cel" -> "Celtic languages", "ces" -> Entity["Language", "Czech"], 
 "cha" -> Entity["Language", "Chamorro"], 
 "chb" -> Entity["Language", "Chibcha"], 
 "che" -> Entity["Language", "Chechen"], 
 "chg" -> Entity["Language", "Chagatai"], 
 "chi" -> Entity["Language", "ChineseMandarin"], 
 "chk" -> Entity["Language", "Chuukese"], 
 "chm" -> Entity["Language", "KaronDori"], 
 "chn" -> Entity["Language", "ChinookWawa"], 
 "cho" -> Entity["Language", "Choctaw"], 
 "chr" -> Entity["Language", "Cherokee"], 
 "chv" -> Entity["Language", "Chuvash"], 
 "chy" -> Entity["Language", "Cheyenne"], "cmc" -> "Chamic languages", 
 "cop" -> Entity["Language", "Coptic"], 
 "cor" -> Entity["Language", "Cornish"], 
 "cos" -> Entity["Language", "Corsican"], 
 "cpe" -> "Creoles and pidgins, English based", 
 "cpf" -> "Creoles and pidgins, French-based", 
 "cpp" -> "Creoles and pidgins, Portuguese-based", 
 "cre" -> Entity["Language", "OjibwaSevern"], "crp" -> "Creoles and pidgins", 
 "csb" -> Entity["Language", "Kashubian"], "cus" -> "Cushitic languages", 
 "cym" -> Entity["Language", "Welsh"], "cze" -> Entity["Language", "Czech"], 
 "dak" -> "Dakota", "dan" -> Entity["Language", "Danish"], 
 "dar" -> Entity["Language", "Dargwa"], 
 "day" -> Entity["Language", "DayakLand"], 
 "del" -> Entity["Language", "Munsee"], "den" -> "Slave (Athapascan)", 
 "deu" -> Entity["Language", "German"], 
 "dgr" -> Entity["Language", "Dogrib"], "din" -> "Dinka", 
 "doi" -> Entity["Language", "Dogri"], "dra" -> "Dravidian languages", 
 "dsb" -> Entity["Language", "SorbianLower"], 
 "dua" -> Entity["Language", "Dhuwal"], 
 "dum" -> "Dutch, Middle (ca.1050-1350)", 
 "dyu" -> Entity["Language", "Jula"], 
 "dzo" -> Entity["Language", "Dzongkha"], 
 "efi" -> Entity["Language", "Efik"], "egy" -> "Egyptian (Ancient)", 
 "eka" -> Entity["Language", "Ekajuk"], "ell" -> "Greek, Modern (1453-)", 
 "elx" -> "Elamite", "eng" -> Entity["Language", "English"], 
 "enm" -> "English, Middle (1100-1500)", 
 "epo" -> Entity["Language", "Esperanto"], 
 "est" -> Entity["Language", "Estonian"], 
 "eus" -> Entity["Language", "Basque"], "ewe" -> "Ewe", 
 "ewo" -> Entity["Language", "Ewondo"], "fan" -> Entity["Language", "Fang"], 
 "fao" -> Entity["Language", "Faroese"], 
 "fas" -> Entity["Language", "FarsiEastern"], "fat" -> "Fanti", 
 "fij" -> Entity["Language", "Fijian"], 
 "fin" -> Entity["Language", "Finnish"], "fiu" -> "Finno-Ugrian languages", 
 "fon" -> "Fon", "fra" -> Entity["Language", "French"], 
 "fre" -> Entity["Language", "French"], 
 "frm" -> "French, Middle (ca.1400-1600)", 
 "fro" -> "French, Old (842-ca.1400)", 
 "frr" -> Entity["Language", "FrisianNorthern"], 
 "frs" -> Entity["Language", "FrisianEastern"], 
 "fry" -> Entity["Language", "FrisianWestern"], "ful" -> "Fulah", 
 "fur" -> Entity["Language", "Friulian"], "gaa" -> "Ga", 
 "gay" -> Entity["Language", "Gayo"], "gba" -> Entity["Language", "Gbaya"], 
 "gem" -> "Germanic languages", "geo" -> Entity["Language", "Georgian"], 
 "ger" -> Entity["Language", "German"], "gez" -> Entity["Language", "Geez"], 
 "gil" -> Entity["Language", "Kiribati"], 
 "gle" -> Entity["Language", "IrishGaelic"], 
 "glg" -> Entity["Language", "Galician"], 
 "glv" -> Entity["Language", "Manx"], 
 "gmh" -> "German, Middle High (ca.1050-1500)", 
 "goh" -> "German, Old High (ca.750-1050)", 
 "gon" -> Entity["Language", "GondiNorthern"], 
 "gor" -> Entity["Language", "Gorontalo"], 
 "got" -> Entity["Language", "Gothic"], "grb" -> "Grebo", 
 "grc" -> "Greek, Ancient (to 1453)", "gre" -> "Greek, Modern (1453-)", 
 "grn" -> Entity["Language", "Chiripa"], 
 "guj" -> Entity["Language", "Gujarati"], "gwi" -> "Gwich'in", 
 "hai" -> "Haida", "hau" -> Entity["Language", "Hausa"], 
 "haw" -> Entity["Language", "Hawaiian"], 
 "heb" -> Entity["Language", "Hebrew"], 
 "her" -> Entity["Language", "Herero"], 
 "hil" -> Entity["Language", "Hiligaynon"], 
 "hin" -> Entity["Language", "Hindi"], 
 "hit" -> Entity["Language", "Hittite"], 
 "hmo" -> Entity["Language", "MotuHiri"], 
 "hrv" -> Entity["Language", "Croatian"], 
 "hsb" -> Entity["Language", "SorbianUpper"], 
 "hun" -> Entity["Language", "Hungarian"], 
 "hup" -> Entity["Language", "Hupa"], 
 "hye" -> Entity["Language", "Armenian"], 
 "iba" -> Entity["Language", "Iban"], "ibo" -> Entity["Language", "Igbo"], 
 "ice" -> Entity["Language", "Icelandic"], "ido" -> "Ido", 
 "ijo" -> "Ijo languages", "iku" -> "Inuktitut", 
 "ilo" -> Entity["Language", "Ilocano"], 
 "ina" -> "Interlingua (International Auxiliary Language Association)", 
 "inc" -> "Indic languages", "ind" -> Entity["Language", "Indonesian"], 
 "ine" -> "Indo-European languages", "inh" -> Entity["Language", "Ingush"], 
 "ipk" -> Entity["Language", "InupiatunNorthAlaskan"], 
 "ira" -> "Iranian languages", "iro" -> "Iroquoian languages", 
 "isl" -> Entity["Language", "Icelandic"], 
 "ita" -> Entity["Language", "Italian"], 
 "jav" -> Entity["Language", "Javanese"], "jbo" -> "Lojban", 
 "jpn" -> Entity["Language", "Japanese"], "jpr" -> "Judeo-Persian", 
 "jrb" -> "Judeo-Arabic", "kaa" -> "Kara-Kalpak", 
 "kab" -> Entity["Language", "Kabyle"], 
 "kam" -> Entity["Language", "Akaselem"], 
 "kan" -> Entity["Language", "Kannada"], "kar" -> "Karen languages", 
 "kas" -> Entity["Language", "Kashmiri"], 
 "kat" -> Entity["Language", "Georgian"], "kau" -> "Kanuri", "kaw" -> "Kawi", 
 "kaz" -> Entity["Language", "Kazakh"], 
 "kbd" -> Entity["Language", "Kabardian"], 
 "kha" -> Entity["Language", "Khasi"], "khi" -> "Khoisan languages", 
 "khm" -> Entity["Language", "KhmerCentral"], 
 "kin" -> Entity["Language", "Rwanda"], 
 "kmb" -> Entity["Language", "Mbundu"], 
 "kok" -> Entity["Language", "Konkani"], 
 "kom" -> Entity["Language", "KomiZyrian"], 
 "kon" -> Entity["Language", "Koongo"], 
 "kor" -> Entity["Language", "Korean"], 
 "kos" -> Entity["Language", "Kosraean"], "kpe" -> "Kpelle", 
 "krc" -> "Karachay-Balkar", "krl" -> Entity["Language", "Karelian"], 
 "kro" -> "Kru languages", "kru" -> Entity["Language", "Kurux"], 
 "kum" -> Entity["Language", "Kumyk"], "kur" -> "Kurdish", 
 "kut" -> Entity["Language", "Kutenai"], 
 "lad" -> Entity["Language", "Ladino"], 
 "lah" -> Entity["Language", "PanjabiWestern"], 
 "lam" -> Entity["Language", "Lamba"], "lao" -> "Lao", 
 "lat" -> Entity["Language", "Latin"], 
 "lav" -> Entity["Language", "Latvian"], 
 "lez" -> Entity["Language", "Lezgi"], 
 "lin" -> Entity["Language", "Lingala"], 
 "lit" -> Entity["Language", "Lithuanian"], 
 "lol" -> Entity["Language", "Bushoong"], 
 "loz" -> Entity["Language", "Lodhi"], "lua" -> "Luba-Lulua", 
 "lub" -> "Luba-Katanga", "lug" -> Entity["Language", "Gaanda"], 
 "lui" -> Entity["Language", "Luiseno"], 
 "lun" -> Entity["Language", "Lunda"], "luo" -> "Luo (Kenya and Tanzania)", 
 "lus" -> Entity["Language", "Mizo"], 
 "mac" -> Entity["Language", "Macedonian"], 
 "mad" -> Entity["Language", "Madura"], 
 "mag" -> Entity["Language", "Magahi"], 
 "mah" -> Entity["Language", "Marshallese"], 
 "mai" -> Entity["Language", "Maithili"], 
 "mak" -> Entity["Language", "Makasar"], 
 "mal" -> Entity["Language", "Malayalam"], 
 "man" -> Entity["Language", "Mandinka"], 
 "mao" -> Entity["Language", "Maori"], "map" -> "Austronesian languages", 
 "mar" -> Entity["Language", "Marathi"], 
 "mas" -> Entity["Language", "Maasai"], "may" -> Entity["Language", "Malay"], 
 "mdf" -> Entity["Language", "Moksha"], 
 "mdr" -> Entity["Language", "Mandar"], "men" -> Entity["Language", "Mende"], 
 "mga" -> "Irish, Middle (900-1200)", 
 "min" -> Entity["Language", "Minangkabau"], "mis" -> "Uncoded languages", 
 "mkd" -> Entity["Language", "Macedonian"], 
 "mkh" -> Entity["Language", "KhmerCentral"], "mlg" -> "Malagasy", 
 "mlt" -> Entity["Language", "Maltese"], 
 "mnc" -> Entity["Language", "Manchu"], 
 "mni" -> Entity["Language", "Meitei"], "mno" -> "Manobo languages", 
 "moh" -> Entity["Language", "Mohawk"], "mon" -> "Mongolian", 
 "mos" -> Entity["Language", "Moore"], "mri" -> Entity["Language", "Maori"], 
 "msa" -> Entity["Language", "Malay"], "mul" -> "Multiple languages", 
 "mun" -> Entity["Language", "Mundari"], 
 "mus" -> Entity["Language", "Muskogee"], 
 "mwl" -> Entity["Language", "MirandaDoDouro"], 
 "mwr" -> Entity["Language", "Marwari"], 
 "mya" -> Entity["Language", "Burmese"], 
 "myn" -> Entity["Language", "MayaYucatan"], 
 "myv" -> Entity["Language", "Erzya"], "nah" -> "Nahuatl languages", 
 "nai" -> "North American Indian languages", "nap" -> "Neapolitan", 
 "nau" -> "Nauru", "ndo" -> Entity["Language", "Ndonga"], 
 "nep" -> Entity["Language", "Nepali"], "nia" -> Entity["Language", "Nias"], 
 "nic" -> "Niger-Kordofanian languages", "niu" -> Entity["Language", "Niue"], 
 "nog" -> Entity["Language", "Nogai"], "non" -> "Norse, Old", 
 "nor" -> Entity["Language", "Norwegian"], "nqo" -> "N'Ko", 
 "nub" -> "Nubian languages", "nym" -> Entity["Language", "Nyamwezi"], 
 "nyn" -> Entity["Language", "Nyankore"], 
 "nyo" -> Entity["Language", "Hema"], "nzi" -> Entity["Language", "Nzema"], 
 "oci" -> "Occitan (post 1500)", "oji" -> "Ojibwa", 
 "ori" -> Entity["Language", "Oriya"], 
 "orm" -> Entity["Language", "OromoBoranaArsiGuji"], 
 "osa" -> Entity["Language", "Osage"], 
 "ota" -> "Turkish, Ottoman (1500-1928)", "oto" -> "Otomian languages", 
 "paa" -> "Papuan languages", "pag" -> Entity["Language", "Pangasinan"], 
 "pal" -> "Pahlavi", "pap" -> Entity["Language", "Papiamentu"], 
 "pau" -> Entity["Language", "Palauan"], 
 "peo" -> "Persian, Old (ca.600-400 B.C.)", 
 "per" -> Entity["Language", "FarsiEastern"], 
 "phi" -> Entity["Language", "Cebuano"], 
 "phn" -> Entity["Language", "Phoenician"], 
 "pli" -> Entity["Language", "BareliPalya"], 
 "pol" -> Entity["Language", "Polish"], 
 "pon" -> Entity["Language", "Pohnpeian"], 
 "por" -> Entity["Language", "Portuguese"], "pra" -> "Prakrit languages", 
 "qaa-qtz" -> "Reserved for local use", 
 "que" -> Entity["Language", "QuechuaClassical"], 
 "raj" -> Entity["Language", "Marwari"], "rap" -> "Rapanui", 
 "roa" -> "Romance languages", "roh" -> Entity["Language", "Romansch"], 
 "rom" -> "Romany", "run" -> Entity["Language", "Rundi"], 
 "rus" -> Entity["Language", "Russian"], 
 "sad" -> Entity["Language", "Sandawe"], 
 "sag" -> Entity["Language", "Sango"], "sah" -> Entity["Language", "Yakut"], 
 "sai" -> "South American Indian languages", "sal" -> "Salishan languages", 
 "sam" -> Entity["Language", "SamaritanAramaic"], 
 "san" -> Entity["Language", "Sanskrit"], 
 "sas" -> Entity["Language", "Sasak"], 
 "sat" -> Entity["Language", "Santali"], 
 "scn" -> Entity["Language", "Sicilian"], 
 "sco" -> Entity["Language", "Scots"], "sel" -> Entity["Language", "Selkup"], 
 "sem" -> "Semitic languages", "sga" -> "Irish, Old (to 900)", 
 "sgn" -> "Sign Languages", "shn" -> Entity["Language", "Shan"], 
 "sid" -> Entity["Language", "Sidamo"], "sio" -> "Siouan languages", 
 "sit" -> "Sino-Tibetan languages", "sla" -> "Slavic languages", 
 "slk" -> Entity["Language", "Slovak"], 
 "slo" -> Entity["Language", "Slovak"], 
 "slv" -> Entity["Language", "Slovenian"], "sma" -> "Southern Sami", 
 "sme" -> "Northern Sami", "smi" -> Entity["Language", "SaamiInari"], 
 "smj" -> "Lule Sami", "smn" -> "Inari Sami", 
 "smo" -> Entity["Language", "Samoan"], "sms" -> "Skolt Sami", 
 "sna" -> Entity["Language", "Shona"], "snd" -> Entity["Language", "Sindhi"], 
 "snk" -> Entity["Language", "Soninke"], 
 "sog" -> Entity["Language", "Sogdian"], 
 "som" -> Entity["Language", "Somali"], 
 "son" -> Entity["Language", "Songhay"], "sot" -> "Sotho, Southern", 
 "sqi" -> "Albanian", "srd" -> "Sardinian", 
 "srn" -> Entity["Language", "Sranan"], 
 "srp" -> Entity["Language", "Serbian"], 
 "srr" -> Entity["Language", "SererSine"], "ssa" -> "Nilo-Saharan languages", 
 "ssw" -> Entity["Language", "Swati"], "suk" -> Entity["Language", "Sukuma"], 
 "sun" -> Entity["Language", "Sunda"], "sus" -> Entity["Language", "Susu"], 
 "sux" -> Entity["Language", "Sumerian"], 
 "swa" -> Entity["Language", "Swahili"], 
 "swe" -> Entity["Language", "Swedish"], 
 "syc" -> Entity["Language", "Syriac"], 
 "syr" -> Entity["Language", "Syriac"], 
 "tah" -> Entity["Language", "Tahitian"], "tai" -> "Tai languages", 
 "tam" -> Entity["Language", "Tamil"], "tat" -> Entity["Language", "Tatar"], 
 "tel" -> Entity["Language", "Telugu"], 
 "tem" -> Entity["Language", "Themne"], 
 "ter" -> Entity["Language", "Terena"], "tet" -> Entity["Language", "Tetun"], 
 "tgk" -> Entity["Language", "FarsiEastern"], 
 "tgl" -> Entity["Language", "Tagalog"], "tha" -> Entity["Language", "Thai"], 
 "tib" -> Entity["Language", "TibetanCentral"], 
 "tig" -> Entity["Language", "Tigre"], 
 "tir" -> Entity["Language", "Tigrigna"], "tiv" -> "Tiv", 
 "tkl" -> Entity["Language", "Tokelauan"], 
 "tli" -> Entity["Language", "Tlingit"], 
 "tmh" -> Entity["Language", "TamahaqTahaggart"], "tog" -> "Tonga (Nyasa)", 
 "ton" -> "Tonga (Tonga Islands)", "tpi" -> Entity["Language", "TokPisin"], 
 "tsi" -> Entity["Language", "Tsimshian"], 
 "tsn" -> Entity["Language", "Tswana"], 
 "tso" -> Entity["Language", "Tsonga"], 
 "tuk" -> Entity["Language", "Turkmen"], 
 "tum" -> Entity["Language", "Tumbuka"], "tup" -> Entity["Language", "Tupi"], 
 "tur" -> Entity["Language", "Turkish"], "tut" -> "Altaic languages", 
 "tvl" -> Entity["Language", "Tuvaluan"], "twi" -> "Twi", 
 "tyv" -> Entity["Language", "Tuvin"], "udm" -> Entity["Language", "Udmurt"], 
 "uga" -> Entity["Language", "Ugaritic"], 
 "ukr" -> Entity["Language", "Ukrainian"], 
 "umb" -> Entity["Language", "Umbundu"], "und" -> "Undetermined", 
 "urd" -> Entity["Language", "Urdu"], "uzb" -> "Uzbek", "vai" -> "Vai", 
 "ven" -> Entity["Language", "Venda"], 
 "vie" -> Entity["Language", "Vietnamese"], "vol" -> "Volap\[UDoubleDot]k", 
 "vot" -> Entity["Language", "Vod"], "wak" -> "Wakashan languages", 
 "war" -> Entity["Language", "Waray"], "was" -> Entity["Language", "Washo"], 
 "wel" -> Entity["Language", "Welsh"], "wen" -> "Sorbian languages", 
 "wln" -> Entity["Language", "Walloon"], 
 "wol" -> Entity["Language", "Wolof"], "xho" -> Entity["Language", "Xhosa"], 
 "yao" -> "Yao", "yap" -> Entity["Language", "Yapese"], 
 "yid" -> Entity["Language", "YiddishEastern"], 
 "yor" -> Entity["Language", "Yoruba"], "ypk" -> "Yupik languages", 
 "zap" -> "Zapotec", "zen" -> Entity["Language", "Zenaga"], 
 "zgh" -> "Standard Moroccan Tamazight", 
 "zho" -> Entity["Language", "ChineseMandarin"], 
 "znd" -> Entity["Language", "Zande"], "zul" -> Entity["Language", "Zulu"], 
 "zun" -> Entity["Language", "Zuni"]};

publishCountryCodeMap = {"aa" -> Entity["Country", "Albania"], 
 "abc" -> Entity["AdministrativeDivision", {"Alberta", "Canada"}], 
 "-ac" -> Entity["AdministrativeDivision", {"AshmoreAndCartierIslands", 
    "Australia"}], "aca" -> "Australian Capital Territory", 
 "ae" -> Entity["Country", "Algeria"], 
 "af" -> Entity["Country", "Afghanistan"], 
 "ag" -> Entity["Country", "Argentina"], 
 "-ai" -> Entity["Country", "Anguilla"], 
 "ai" -> Entity["Country", "Armenia"], "-air" -> "Armenian S.S.R.", 
 "aj" -> Entity["Country", "Azerbaijan"], "-ajr" -> "Azerbaijan S.S.R.", 
 "aku" -> Entity["AdministrativeDivision", {"Alaska", "UnitedStates"}], 
 "alu" -> Entity["AdministrativeDivision", {"Alabama", "UnitedStates"}], 
 "am" -> Entity["Country", "Anguilla"], "an" -> Entity["Country", "Andorra"], 
 "ao" -> Entity["Country", "Angola"], 
 "aq" -> Entity["Country", "AntiguaBarbuda"], 
 "aru" -> Entity["AdministrativeDivision", {"Arkansas", "UnitedStates"}], 
 "as" -> Entity["Country", "AmericanSamoa"], 
 "at" -> Entity["Country", "Australia"], 
 "au" -> Entity["Country", "Austria"], "aw" -> Entity["Country", "Aruba"], 
 "ay" -> "Antarctica", "azu" -> Entity["AdministrativeDivision", 
   {"Arizona", "UnitedStates"}], "ba" -> Entity["Country", "Bahrain"], 
 "bb" -> Entity["Country", "Barbados"], 
 "bcc" -> Entity["AdministrativeDivision", {"BritishColumbia", "Canada"}], 
 "bd" -> Entity["Country", "Burundi"], "be" -> Entity["Country", "Belgium"], 
 "bf" -> Entity["Country", "Bahamas"], 
 "bg" -> Entity["Country", "Bangladesh"], 
 "bh" -> Entity["Country", "Belize"], 
 "bi" -> "British Indian Ocean Territory", 
 "bl" -> Entity["Country", "Brazil"], "bm" -> "Bermuda Islands", 
 "bn" -> Entity["Country", "BosniaHerzegovina"], 
 "bo" -> Entity["Country", "Bolivia"], 
 "bp" -> Entity["Country", "SolomonIslands"], 
 "br" -> Entity["Country", "Myanmar"], "bs" -> Entity["Country", "Botswana"], 
 "bt" -> Entity["Country", "Bhutan"], "bu" -> Entity["Country", "Bulgaria"], 
 "bv" -> "Bouvet Island", "bw" -> Entity["Country", "Belarus"], 
 "-bwr" -> "Byelorussian S.S.R.", "bx" -> Entity["Country", "Brunei"], 
 "ca" -> "Caribbean Netherlands", "cau" -> Entity["AdministrativeDivision", 
   {"California", "UnitedStates"}], "cb" -> Entity["Country", "Cambodia"], 
 "cc" -> Entity["Country", "China"], "cd" -> Entity["Country", "Chad"], 
 "ce" -> Entity["Country", "SriLanka"], 
 "cf" -> Entity["Country", "RepublicCongo"], 
 "cg" -> Entity["Country", "DemocraticRepublicCongo"], 
 "ch" -> "China (Republic : 1949- )", "ci" -> Entity["Country", "Croatia"], 
 "cj" -> Entity["Country", "CaymanIslands"], 
 "ck" -> Entity["Country", "Colombia"], "cl" -> Entity["Country", "Chile"], 
 "cm" -> Entity["Country", "Cameroon"], "-cn" -> Entity["Country", "Canada"], 
 "co" -> Entity["Country", "Curacao"], 
 "cou" -> Entity["AdministrativeDivision", {"Colorado", "UnitedStates"}], 
 "-cp" -> "Canton and Enderbury Islands", 
 "cq" -> Entity["Country", "Comoros"], 
 "cr" -> Entity["Country", "CostaRica"], "-cs" -> "Czechoslovakia", 
 "ctu" -> Entity["AdministrativeDivision", {"Connecticut", "UnitedStates"}], 
 "cu" -> Entity["Country", "Cuba"], "cv" -> Entity["Country", "CapeVerde"], 
 "cw" -> Entity["Country", "CookIslands"], 
 "cx" -> Entity["Country", "CentralAfricanRepublic"], 
 "cy" -> Entity["Country", "Cyprus"], "-cz" -> "Canal Zone", 
 "dcu" -> Entity["AdministrativeDivision", {"DistrictOfColumbia", 
    "UnitedStates"}], "deu" -> Entity["AdministrativeDivision", 
   {"Delaware", "UnitedStates"}], "dk" -> Entity["Country", "Denmark"], 
 "dm" -> Entity["Country", "Benin"], "dq" -> Entity["Country", "Dominica"], 
 "dr" -> Entity["Country", "DominicanRepublic"], 
 "ea" -> Entity["Country", "Eritrea"], "ec" -> Entity["Country", "Ecuador"], 
 "eg" -> Entity["Country", "EquatorialGuinea"], 
 "em" -> Entity["Country", "EastTimor"], 
 "enk" -> Entity["AdministrativeDivision", {"England", "UnitedKingdom"}], 
 "er" -> Entity["Country", "Estonia"], 
 "-err" -> Entity["Country", "Estonia"], 
 "es" -> Entity["Country", "ElSalvador"], 
 "et" -> Entity["Country", "Ethiopia"], 
 "fa" -> Entity["Country", "FaroeIslands"], 
 "fg" -> Entity["Country", "FrenchGuiana"], 
 "fi" -> Entity["Country", "Finland"], "fj" -> Entity["Country", "Fiji"], 
 "fk" -> Entity["Country", "FalklandIslands"], 
 "flu" -> Entity["AdministrativeDivision", {"Florida", "UnitedStates"}], 
 "fm" -> "Micronesia (Federated States)", 
 "fp" -> Entity["Country", "FrenchPolynesia"], 
 "fr" -> Entity["Country", "France"], 
 "fs" -> "Terres australes et antarctiques fran\[CCedilla]aises", 
 "ft" -> Entity["Country", "Djibouti"], 
 "gau" -> Entity["AdministrativeDivision", {"Georgia", "UnitedStates"}], 
 "gb" -> Entity["Country", "Kiribati"], "gd" -> Entity["Country", "Grenada"], 
 "-ge" -> "Germany (East)", "gh" -> Entity["Country", "Ghana"], 
 "gi" -> Entity["Country", "Gibraltar"], 
 "gl" -> Entity["Country", "Greenland"], "gm" -> Entity["Country", "Gambia"], 
 "-gn" -> "Gilbert and Ellice Islands", "go" -> Entity["Country", "Gabon"], 
 "gp" -> Entity["Country", "Guadeloupe"], 
 "gr" -> Entity["Country", "Greece"], "gs" -> Entity["Country", "Georgia"], 
 "-gsr" -> "Georgian S.S.R.", "gt" -> Entity["Country", "Guatemala"], 
 "gu" -> Entity["Country", "Guam"], "gv" -> Entity["Country", "Guinea"], 
 "gw" -> Entity["Country", "Germany"], "gy" -> Entity["Country", "Guyana"], 
 "gz" -> Entity["Country", "GazaStrip"], 
 "hiu" -> Entity["AdministrativeDivision", {"Hawaii", "UnitedStates"}], 
 "-hk" -> "Hong Kong", "hm" -> "Heard and McDonald Islands", 
 "ho" -> Entity["Country", "Honduras"], "ht" -> Entity["Country", "Haiti"], 
 "hu" -> Entity["Country", "Hungary"], 
 "iau" -> Entity["AdministrativeDivision", {"Iowa", "UnitedStates"}], 
 "ic" -> Entity["Country", "Iceland"], 
 "idu" -> Entity["AdministrativeDivision", {"Idaho", "UnitedStates"}], 
 "ie" -> Entity["Country", "Ireland"], "ii" -> Entity["Country", "India"], 
 "ilu" -> Entity["AdministrativeDivision", {"Illinois", "UnitedStates"}], 
 "inu" -> Entity["AdministrativeDivision", {"Indiana", "UnitedStates"}], 
 "io" -> Entity["Country", "Indonesia"], "iq" -> Entity["Country", "Iraq"], 
 "ir" -> Entity["Country", "Iran"], "is" -> Entity["Country", "Israel"], 
 "it" -> Entity["Country", "Italy"], 
 "-iu" -> "Israel-Syria Demilitarized Zones", 
 "iv" -> Entity["Country", "IvoryCoast"], 
 "-iw" -> "Israel-Jordan Demilitarized Zones", 
 "iy" -> "Iraq-Saudi Arabia Neutral Zone", 
 "ja" -> Entity["Country", "Japan"], "ji" -> "Johnston Atoll", 
 "jm" -> Entity["Country", "Jamaica"], 
 "-jn" -> Entity["Country", "Svalbard"], "jo" -> Entity["Country", "Jordan"], 
 "ke" -> Entity["Country", "Kenya"], "kg" -> Entity["Country", "Kyrgyzstan"], 
 "-kgr" -> "Kirghiz S.S.R.", "kn" -> Entity["Country", "NorthKorea"], 
 "ko" -> Entity["Country", "SouthKorea"], 
 "ksu" -> Entity["AdministrativeDivision", {"Kansas", "UnitedStates"}], 
 "ku" -> Entity["Country", "Kuwait"], "kv" -> Entity["Country", "Kosovo"], 
 "kyu" -> Entity["AdministrativeDivision", {"Kentucky", "UnitedStates"}], 
 "kz" -> Entity["Country", "Kazakhstan"], "-kzr" -> "Kazakh S.S.R.", 
 "lau" -> Entity["AdministrativeDivision", {"Louisiana", "UnitedStates"}], 
 "lb" -> Entity["Country", "Liberia"], "le" -> Entity["Country", "Lebanon"], 
 "lh" -> Entity["Country", "Liechtenstein"], 
 "li" -> Entity["Country", "Lithuania"], 
 "-lir" -> Entity["Country", "Lithuania"], 
 "-ln" -> "Central and Southern Line Islands", 
 "lo" -> Entity["Country", "Lesotho"], "ls" -> Entity["Country", "Laos"], 
 "lu" -> Entity["Country", "Luxembourg"], 
 "lv" -> Entity["Country", "Latvia"], "-lvr" -> Entity["Country", "Latvia"], 
 "ly" -> Entity["Country", "Libya"], 
 "mau" -> Entity["AdministrativeDivision", {"Massachusetts", 
    "UnitedStates"}], "mbc" -> Entity["AdministrativeDivision", 
   {"Manitoba", "Canada"}], "mc" -> Entity["Country", "Monaco"], 
 "mdu" -> Entity["AdministrativeDivision", {"Maryland", "UnitedStates"}], 
 "meu" -> Entity["AdministrativeDivision", {"Maine", "UnitedStates"}], 
 "mf" -> Entity["Country", "Mauritius"], 
 "mg" -> Entity["Country", "Madagascar"], 
 "-mh" -> Entity["Country", "Macau"], 
 "miu" -> Entity["AdministrativeDivision", {"Michigan", "UnitedStates"}], 
 "mj" -> Entity["Country", "Montserrat"], "mk" -> Entity["Country", "Oman"], 
 "ml" -> Entity["Country", "Mali"], "mm" -> Entity["Country", "Malta"], 
 "mnu" -> Entity["AdministrativeDivision", {"Minnesota", "UnitedStates"}], 
 "mo" -> Entity["Country", "Montenegro"], 
 "mou" -> Entity["AdministrativeDivision", {"Missouri", "UnitedStates"}], 
 "mp" -> Entity["Country", "Mongolia"], 
 "mq" -> Entity["Country", "Martinique"], 
 "mr" -> Entity["Country", "Morocco"], 
 "msu" -> Entity["AdministrativeDivision", {"Mississippi", "UnitedStates"}], 
 "mtu" -> Entity["AdministrativeDivision", {"Montana", "UnitedStates"}], 
 "mu" -> Entity["Country", "Mauritania"], 
 "mv" -> Entity["Country", "Moldova"], "-mvr" -> "Moldavian S.S.R.", 
 "mw" -> Entity["Country", "Malawi"], "mx" -> Entity["Country", "Mexico"], 
 "my" -> Entity["Country", "Malaysia"], 
 "mz" -> Entity["Country", "Mozambique"], 
 "-na" -> Entity["Country", "NetherlandsAntilles"], 
 "nbu" -> Entity["AdministrativeDivision", {"Nebraska", "UnitedStates"}], 
 "ncu" -> Entity["AdministrativeDivision", {"NorthCarolina", 
    "UnitedStates"}], "ndu" -> Entity["AdministrativeDivision", 
   {"NorthDakota", "UnitedStates"}], 
 "ne" -> Entity["Country", "Netherlands"], 
 "nfc" -> Entity["AdministrativeDivision", {"NewfoundlandAndLabrador", 
    "Canada"}], "ng" -> Entity["Country", "Niger"], 
 "nhu" -> Entity["AdministrativeDivision", {"NewHampshire", "UnitedStates"}], 
 "nik" -> Entity["AdministrativeDivision", {"NorthernIreland", 
    "UnitedKingdom"}], "nju" -> Entity["AdministrativeDivision", 
   {"NewJersey", "UnitedStates"}], 
 "nkc" -> Entity["AdministrativeDivision", {"NewBrunswick", "Canada"}], 
 "nl" -> Entity["Country", "NewCaledonia"], 
 "-nm" -> Entity["Country", "NorthernMarianaIslands"], 
 "nmu" -> Entity["AdministrativeDivision", {"NewMexico", "UnitedStates"}], 
 "nn" -> Entity["Country", "Vanuatu"], "no" -> Entity["Country", "Norway"], 
 "np" -> Entity["Country", "Nepal"], "nq" -> Entity["Country", "Nicaragua"], 
 "nr" -> Entity["Country", "Nigeria"], 
 "nsc" -> Entity["AdministrativeDivision", {"NovaScotia", "Canada"}], 
 "ntc" -> Entity["AdministrativeDivision", {"NorthwestTerritories", 
    "Canada"}], "nu" -> Entity["Country", "Nauru"], 
 "nuc" -> Entity["AdministrativeDivision", {"Nunavut", "Canada"}], 
 "nvu" -> Entity["AdministrativeDivision", {"Nevada", "UnitedStates"}], 
 "nw" -> Entity["Country", "NorthernMarianaIslands"], 
 "nx" -> Entity["Country", "NorfolkIsland"], 
 "nyu" -> Entity["AdministrativeDivision", {"NewYork", "UnitedStates"}], 
 "nz" -> Entity["Country", "NewZealand"], 
 "ohu" -> Entity["AdministrativeDivision", {"Ohio", "UnitedStates"}], 
 "oku" -> Entity["AdministrativeDivision", {"Oklahoma", "UnitedStates"}], 
 "onc" -> Entity["AdministrativeDivision", {"Ontario", "Canada"}], 
 "oru" -> Entity["AdministrativeDivision", {"Oregon", "UnitedStates"}], 
 "ot" -> Entity["Country", "Mayotte"], 
 "pau" -> Entity["AdministrativeDivision", {"Pennsylvania", "UnitedStates"}], 
 "pc" -> Entity["Country", "PitcairnIslands"], 
 "pe" -> Entity["Country", "Peru"], "pf" -> "Paracel Islands", 
 "pg" -> Entity["Country", "GuineaBissau"], 
 "ph" -> Entity["Country", "Philippines"], 
 "pic" -> Entity["AdministrativeDivision", {"PrinceEdwardIsland", "Canada"}], 
 "pk" -> Entity["Country", "Pakistan"], "pl" -> Entity["Country", "Poland"], 
 "pn" -> Entity["Country", "Panama"], "po" -> Entity["Country", "Portugal"], 
 "pp" -> Entity["Country", "PapuaNewGuinea"], 
 "pr" -> Entity["Country", "PuertoRico"], "-pt" -> "Portuguese Timor", 
 "pw" -> Entity["Country", "Palau"], "py" -> Entity["Country", "Paraguay"], 
 "qa" -> Entity["Country", "Qatar"], "qea" -> "Queensland", 
 "quc" -> Entity["AdministrativeDivision", {"Quebec", "Canada"}], 
 "rb" -> Entity["Country", "Serbia"], "re" -> Entity["Country", "Reunion"], 
 "rh" -> Entity["Country", "Zimbabwe"], 
 "riu" -> Entity["AdministrativeDivision", {"RhodeIsland", "UnitedStates"}], 
 "rm" -> Entity["Country", "Romania"], "ru" -> Entity["Country", "Russia"], 
 "-rur" -> "Russian S.F.S.R.", "rw" -> Entity["Country", "Rwanda"], 
 "-ry" -> "Ryukyu Islands, Southern", 
 "sa" -> Entity["Country", "SouthAfrica"], 
 "-sb" -> Entity["Country", "Svalbard"], "sc" -> "Saint-Barth\[EAcute]lemy", 
 "scu" -> Entity["AdministrativeDivision", {"SouthCarolina", 
    "UnitedStates"}], "sd" -> Entity["Country", "SouthSudan"], 
 "sdu" -> Entity["AdministrativeDivision", {"SouthDakota", "UnitedStates"}], 
 "se" -> Entity["Country", "Seychelles"], 
 "sf" -> Entity["Country", "SaoTomePrincipe"], 
 "sg" -> Entity["Country", "Senegal"], "sh" -> "Spanish North Africa", 
 "si" -> Entity["Country", "Singapore"], "sj" -> Entity["Country", "Sudan"], 
 "-sk" -> Entity["AdministrativeDivision", {"EastSikkim", "Sikkim", 
    "India"}], "sl" -> Entity["Country", "SierraLeone"], 
 "sm" -> Entity["Country", "SanMarino"], 
 "sn" -> Entity["Country", "SintMaarten"], 
 "snc" -> Entity["AdministrativeDivision", {"Saskatchewan", "Canada"}], 
 "so" -> Entity["Country", "Somalia"], "sp" -> Entity["Country", "Spain"], 
 "sq" -> Entity["Country", "Swaziland"], 
 "sr" -> Entity["Country", "Suriname"], 
 "ss" -> Entity["Country", "WesternSahara"], "st" -> "Saint-Martin", 
 "stk" -> Entity["AdministrativeDivision", {"Scotland", "UnitedKingdom"}], 
 "su" -> Entity["Country", "SaudiArabia"], "-sv" -> "Swan Islands", 
 "sw" -> Entity["Country", "Sweden"], "sx" -> Entity["Country", "Namibia"], 
 "sy" -> Entity["Country", "Syria"], 
 "sz" -> Entity["Country", "Switzerland"], 
 "ta" -> Entity["Country", "Tajikistan"], "-tar" -> "Tajik S.S.R.", 
 "tc" -> Entity["Country", "TurksCaicosIslands"], 
 "tg" -> Entity["Country", "Togo"], "th" -> Entity["Country", "Thailand"], 
 "ti" -> Entity["Country", "Tunisia"], 
 "tk" -> Entity["Country", "Turkmenistan"], "-tkr" -> "Turkmen S.S.R.", 
 "tl" -> Entity["Country", "Tokelau"], "tma" -> "Tasmania", 
 "tnu" -> Entity["AdministrativeDivision", {"Tennessee", "UnitedStates"}], 
 "to" -> Entity["Country", "Tonga"], 
 "tr" -> Entity["Country", "TrinidadTobago"], 
 "ts" -> Entity["Country", "UnitedArabEmirates"], 
 "-tt" -> "Trust Territory of the Pacific Islands", 
 "tu" -> Entity["Country", "Turkey"], "tv" -> Entity["Country", "Tuvalu"], 
 "txu" -> Entity["AdministrativeDivision", {"Texas", "UnitedStates"}], 
 "tz" -> Entity["Country", "Tanzania"], "ua" -> Entity["Country", "Egypt"], 
 "uc" -> "United States Misc. Caribbean Islands", 
 "ug" -> Entity["Country", "Uganda"], 
 "-ui" -> "United Kingdom Misc. Islands", 
 "uik" -> Entity["Country", "UnitedKingdom"], "-uk" -> "United Kingdom", 
 "un" -> Entity["Country", "Ukraine"], 
 "-unr" -> Entity["Country", "Ukraine"], 
 "up" -> "United States Misc. Pacific Islands", "-ur" -> "Soviet Union", 
 "-us" -> Entity["Country", "UnitedStates"], 
 "utu" -> Entity["AdministrativeDivision", {"Utah", "UnitedStates"}], 
 "uv" -> Entity["Country", "BurkinaFaso"], 
 "uy" -> Entity["Country", "Uruguay"], 
 "uz" -> Entity["Country", "Uzbekistan"], "-uzr" -> "Uzbek S.S.R.", 
 "vau" -> Entity["AdministrativeDivision", {"Virginia", "UnitedStates"}], 
 "vb" -> Entity["Country", "BritishVirginIslands"], 
 "vc" -> Entity["Country", "VaticanCity"], 
 "ve" -> Entity["Country", "Venezuela"], 
 "vi" -> Entity["Country", "UnitedStatesVirginIslands"], 
 "vm" -> Entity["Country", "Vietnam"], "-vn" -> "Vietnam, North", 
 "vp" -> "Various places", "vra" -> "Victoria", "-vs" -> "Vietnam, South", 
 "vtu" -> Entity["AdministrativeDivision", {"Vermont", "UnitedStates"}], 
 "wau" -> Entity["AdministrativeDivision", {"Washington", "UnitedStates"}], 
 "-wb" -> "West Berlin", "wea" -> "Western Australia", 
 "wf" -> Entity["Country", "WallisFutuna"], 
 "wiu" -> Entity["AdministrativeDivision", {"Wisconsin", "UnitedStates"}], 
 "wj" -> "West Bank of the Jordan River", "wk" -> "Wake Island", 
 "wlk" -> Entity["AdministrativeDivision", {"Wales", "UnitedKingdom"}], 
 "ws" -> Entity["Country", "Samoa"], 
 "wvu" -> Entity["AdministrativeDivision", {"WestVirginia", "UnitedStates"}], 
 "wyu" -> Entity["AdministrativeDivision", {"Wyoming", "UnitedStates"}], 
 "xa" -> "Christmas Island (Indian Ocean)", 
 "xb" -> Entity["Country", "CocosKeelingIslands"], 
 "xc" -> Entity["Country", "Maldives"], 
 "xd" -> Entity["Country", "SaintKittsNevis"], 
 "xe" -> Entity["Country", "MarshallIslands"], "xf" -> "Midway Islands", 
 "xga" -> "Coral Sea Islands Territory", "xh" -> Entity["Country", "Niue"], 
 "-xi" -> "Saint Kitts-Nevis-Anguilla", 
 "xj" -> Entity["Country", "SaintHelena"], 
 "xk" -> Entity["Country", "SaintLucia"], 
 "xl" -> Entity["Country", "SaintPierreMiquelon"], 
 "xm" -> Entity["Country", "SaintVincentGrenadines"], 
 "xn" -> Entity["Country", "Macedonia"], "xna" -> "New South Wales", 
 "xo" -> Entity["Country", "Slovakia"], "xoa" -> "Northern Territory", 
 "xp" -> "Spratly Island", "xr" -> Entity["Country", "CzechRepublic"], 
 "xra" -> "South Australia", 
 "xs" -> "South Georgia and the South Sandwich Islands", 
 "xv" -> Entity["Country", "Slovenia"], 
 "xx" -> "No place, unknown, or undetermined", 
 "xxc" -> Entity["Country", "Canada"], 
 "xxk" -> Entity["Country", "UnitedKingdom"], "-xxr" -> "Soviet Union", 
 "xxu" -> Entity["Country", "UnitedStates"], 
 "ye" -> Entity["Country", "Yemen"], 
 "ykc" -> Entity["AdministrativeDivision", {"YukonTerritory", "Canada"}], 
 "-ys" -> "Yemen (People's Democratic Republic)", 
 "-yu" -> "Serbia and Montenegro", "za" -> Entity["Country", "Zambia"]};

 End[];
 
 EndPackage[];
 
