

#ifndef WGL_Error_define
#error "WGL_Error_define must be defined"
#endif

WGL_Error_define(WGL_Success, "succ", "")
WGL_Error_define(WGL_Error_Invalid_Version, "invver", "Invalid version.") 
WGL_Error_define(WGL_Error_Invalid_State, "invstt", "Encountered an invalid state.") 
WGL_Error_define(WGL_Error_Invalid_Value, "invval", "Encountered an invalid value.") 
WGL_Error_define(WGL_Error_Invalid_Input, "invinpt", "Encountered invalid input.") 
WGL_Error_define(WGL_Error_Out_Of_Memory, "outmem", "Out of memory.")
WGL_Error_define(WGL_Error_Not_Initialized, "notinit", "Not initialized.")
WGL_Error_define(WGL_Error_Deinitialized, "nodeinit", "Failed to deinitialize.")
WGL_Error_define(WGL_Error_Device_Not_Found, "nodev", "Device was not found.")
WGL_Error_define(WGL_Error_Device_Not_Available, "nodeva", "Device is not available.")
WGL_Error_define(WGL_Error_Device_Prohibited, "prohb", "Device is prohibited from use by OS.")
WGL_Error_define(WGL_Error_Invalid_WolframLibraryData, "invwld", "Invalid WolframLibraryData object.")
WGL_Error_define(WGL_Error_Invalid_Platform, "invplt", "Invalid platform")
WGL_Error_define(WGL_Error_Invalid_Device, "invdev", "Invalid device.")
WGL_Error_define(WGL_Error_Invalid_Device_Type, "invdevt", "Invalid device type.")
WGL_Error_define(WGL_Error_Invalid_Context, "invctx", "Invalid context.")
WGL_Error_define(WGL_Error_Invalid_Queue_Properties, "invqup", "Invalid queue property.")
WGL_Error_define(WGL_Error_Invalid_Command_Queue, "invcmdcq", "Invalid command queue.")
WGL_Error_define(WGL_Error_Invalid_Binary, "invbin", "Invalid binary.")
WGL_Error_define(WGL_Error_Invalid_Source, "invsrc", "Invalid source.")
WGL_Error_define(WGL_Error_Invalid_SourceFile, "invsrcf", "Invalid source file.")
WGL_Error_define(WGL_Error_Invalid_OutputFile, "invout", "Invalid output file.")
WGL_Error_define(WGL_Error_Invalid_Memory, "invmem", "Invalid memory.")
WGL_Error_define(WGL_Error_Invalid_Residence_Property, "invresp", "Invalid residence.")
WGL_Error_define(WGL_Error_Invalid_Sharing_Property, "invshrp", "Invalid sharing.")
WGL_Error_define(WGL_Error_No_Compiler, "nocmp", "No compiler found.")
WGL_Error_define(WGL_Error_No_XCompiler, "noxcmp", "No C compiler found.")
WGL_Error_define(WGL_Error_Program_Build_Failure, "cmpf", "Compilation failed.")
WGL_Error_define(WGL_Error_Invalid_Bulid_Options, "invbldopt", "Invalid build options.")
WGL_Error_define(WGL_Error_Invalid_Property, "invprop", "Invalid property.")
WGL_Error_define(WGL_Error_Invalid_Program, "invprog", "Invalid program.")
WGL_Error_define(WGL_Error_Invalid_Kernel, "invker", "Invalid kernel.")
WGL_Error_define(WGL_Error_Invalid_Kernel_Name, "invkernam", "Invalid kernel name.")
WGL_Error_define(WGL_Error_Invalid_Type, "invtyp", "Invalid type.")
WGL_Error_define(WGL_Error_Invalid_Rank, "invrnk", "Invalid rank.")
WGL_Error_define(WGL_Error_Invalid_Dimensions, "invdim", "Invalid dimensions.")
WGL_Error_define(WGL_Error_Invalid_Image, "invimg", "Invalid image.") 
WGL_Error_define(WGL_Error_Not_Found, "notfnd", "Resource not found.")
WGL_Error_define(WGL_Error_Launch_Failed, "lnchfld", "Launch failed.")
WGL_Error_define(WGL_Error_Launch_Out_Of_Resource, "lchoutres", "Launch out of resources.")
WGL_Error_define(WGL_Error_Out_Of_SharedMemory, "outshrd", "Launch ran out of shared memory.")
WGL_Error_define(WGL_Error_Launch_Timeout, "lnchtout", "Launch timeout.")
WGL_Error_define(WGL_Error_Invalid_Block_Size, "invblksz", "Invalid block size.")
WGL_Error_define(WGL_Error_Invalid_Grid_Size, "invgrdsz", "Invalid grid size.")
WGL_Error_define(WGL_Error_Invalid_Block_Dimension, "invblkdim", "Invalid block dimensions.")
WGL_Error_define(WGL_Error_Invalid_Grid_Dimension, "invgrddim", "Invalid grid dimensions.")
WGL_Error_define(WGL_Error_Alloc_Failed, "allocf", "Allocation failed.")
WGL_Error_define(WGL_Error_Memory_Copy_Failed, "memcpy", "Memory copy failed.")
WGL_Error_define(WGL_Error_Internal, "internal", "Internal error.")
WGL_Error_define(WGL_Error_No_Double_Precision, "nodblp", "No double precision.")
WGL_Error_define(WGL_Error_Not_Implemented, "noimpl", "Feature has not yet been implemented.")
WGL_Error_define(WGL_Error_No_Profiler, "noprof", "No profiler was enabled.")
WGL_Error_define(WGL_Error_Invalid_Index, "invidx", "Invalid index detected.")
WGL_Error_define(WGL_Error_Invalid_Query, "invqry", "Invalid query.")
WGL_Error_define(WGL_Error_Invalid_Compiler, "invcmp", "Invalid driver.")
WGL_Error_define(WGL_Error_CastFromMTensor, "wrncastft", "Incorrect cast.")
WGL_Error_define(WGL_Error_MTensor, "mtens", "Incorrect MTensor.")
WGL_Error_define(WGL_Error_External_Evaluation, "exteval", "External Evaluation error.")
WGL_Error_define(WGL_Error_Driver_Out_Date, "olddriv", "Video driver version is out of date. Please consult the documentation on instructions on how to update the video driver.")
WGL_Error_define(WGL_Error_Numerical, "numer", "Numerical error.")
WGL_Error_define(WGL_Error_Invalid_Condition, "invcond", "Invalid condition.")
WGL_Error_define(WGL_Error_Invalid_Operation, "invop", "Invaid operation.")
WGL_Error_define(WGL_Error_Instruction_Error, "inster", "Instruction error.")
WGL_Error_define(WGL_Error_Numerical_OverFlow, "ovflw", "Overflow detected.")
WGL_Error_define(WGL_Error_Numerical_UnderFlow, "undflw", "Underflow detected.")
WGL_Error_define(WGL_Error_Numerical_OverUnderFlow, "ovundflw", "OverUnderflow detected.")
WGL_Error_define(WGL_Error_Invalid_CURAND_Generator, "invcurndg", "Invalid CURAND state.")
WGL_Error_define(WGL_Error_Invalid_API, "invapi", "Invalid API")
WGL_Error_define(WGL_Error_StackOverflow, "stkovflw", "Stack overflow.")
WGL_Error_define(WGL_Error_Standalone_Unsuported, "stndaln", "Standalone not supported")
WGL_Error_define(WGL_Error_Invalid_Argument, "cinvarg", "Invalid arguments.")
WGL_Error_define(WGL_Error_Share_Data, "shrwgl", "Was not able to share state data.")
WGL_Error_define(WGL_Error_Unknown, "unknown", "Unknown error.")

#undef WGL_Error_define


